# MXN442 - Assignment 2 and 3 Project
For Article: `Predicting pharmaceutical prices. Advances based on purchase-level data and machine learning`

## Importing Relevant Libraries

Any libraries used only in the utility functions are kept inside `report_utils.py`

In [1]:
import pandas as pd
import numpy as np

# Importing a progress bar due to how big the catalog dataset are
from tqdm.notebook import tqdm
import json

# All functions that are used in the code is stored here
from report_utils import *

# Unfortunately, as the catalogs are in Spanish, we need to translate the data dictionary to identify the columns
from deep_translator import GoogleTranslator

import aiohttp
import requests
import warnings

import os
pd.set_option('display.max_columns', None)

Processing Tender Contracts:   0%|          | 0/166010 [00:00<?, ?it/s]

In [2]:
def unit_price_mapping(df, contract_unit_prices):
    if 'unit_price' not in df.columns:
        df['unit_price'] = None

        updated_rows = 0
        total_contracts_checked = 0

        contract_groupings = df.groupby('tender_publications_lastcontract')

        for contract_uri, grouped_data_frame in tqdm(contract_groupings, desc='Mapping Contract Unit Prices'):
            total_contracts_checked += 1

            if contract_uri in contract_unit_prices:
                contract_items = contract_unit_prices[contract_uri]

                for index in grouped_data_frame.index:
                    product_code = str(df.loc[index, 'lot_productCode'])

                    if product_code in contract_items:
                        df.loc[index, 'unit_price'] = contract_items[product_code]
                        updated_rows += 1
                    else:
                        product_code_clean = product_code.replace('-', '').replace(' ', '')
                        for contract_product_id, price in contract_items.items():
                            contract_id_clean = str(contract_product_id).replace('-', '').replace(' ', '')
                            if (product_code_clean == contract_id_clean or 
                                product_code in str(contract_product_id) or 
                                str(contract_product_id) in product_code):
                                df.loc[index, 'unit_price'] = price
                                updated_rows += 1
                                break
    print(f'Unit Price Mapping Results:')
    print(f'- Total contract groups checked: {total_contracts_checked}')
    print(f'- Contracts with unit price data: {len([uri for uri in contract_groupings.groups.keys() if uri in contract_unit_prices])}')
    print(f'- Rows updated with unit prices: {updated_rows}')

    return df

## Main Directories and Variables to be used throughout the notebook

In [3]:
# Setting up the main directories
main_folder = os.getcwd()
data_folder = os.path.join(main_folder, 'data')
generated_data_folder = os.path.join(main_folder, 'generated_data')

# Locales for the Google Translator
english = 'en'
spanish = 'es'
german = 'de'

translator = GoogleTranslator(source = spanish, target = english) 

# All file names for easy code management
# Global files
world_inflation_file = 'API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_23195.csv'
unspsc_classifications_file = 'UNGM_UNSPSC_02-Oct-2025..xlsx'

# Paraguay specific files
main_paraguay_procurement_file = 'dfid2_py_210715_csv.csv'
paraguay_tender_request_metrics_file = 'paraguay_request_tracking_rate_limited.json'
paraguay_rate_limited_data_file = 'paraguay_tender_contracts_rate_limited.json'
paraguay_url_mapping_data_file = 'paraguay_url_mapping_rate_limited.json'
paraguay_catalog_matches_file = 'paraguay_catalog_matches.csv'
paraguayan_procurement_catalog_file_name = 'catalogo_n5'
paraguayan_procurement_catalog_file_path = os.path.join(data_folder, f'{paraguayan_procurement_catalog_file_name}.csv')

# Uruguay specific files
main_uruguay_procurement_file = 'dfid2_uy_210715_csv.csv'
uruguay_catalog_file_name_1 = 'ReporteBusquedaCatalogo_171025_232310.xls'
uruguay_catalog_file_name_2 = 'ReporteBusquedaCatalogo_171025_232414.xls'
uruguay_catalog_file_name_3 = 'ReporteBusquedaCatalogo_171025_232953.xls'
uruguay_procurement_catalog_file_path_1 = os.path.join(data_folder, f'{uruguay_catalog_file_name_1}.csv')
uruguay_procurement_catalog_file_path_2 = os.path.join(data_folder, f'{uruguay_catalog_file_name_2}.csv')
uruguay_procurement_catalog_file_path_3 = os.path.join(data_folder, f'{uruguay_catalog_file_name_3}.csv')

From some later preprocessing, these columns were identified as the most important:

In [4]:
relevant_cols = [
    'tender_id', 'bidder_name', 'tender_year', 'currency',
    'tender_nationalproceduretype', 'tender_supplytype', 'bidder_country',
    'buyer_id', 'bid_price', 'tender_recordedbidscount', 'bidder_id',
    'tender_publications_firstcallfor', 'tender_biddeadline',
    'tender_contractsignaturedate', 'tender_proceduretype',
    'buyer_buyertype', 'tender_title', 'lot_productCode', 'buyer_name',
    'buyer_city', 'buyer_country'
]

## Importing the Datasets

In [5]:
paraguay_procurement_data = pd.read_csv(os.path.join(data_folder, main_paraguay_procurement_file))
paraguay_procurement_data

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type
0,0000d077-12aa-48e5-8393-1f8684a17820,Adquisición de vehículos y maquinarias para la...,NaN,Licitación Pública Nacional,NaN,3,"25101507-002,",NaN,1.272480e+09,1.724800e+08,Adquisición de vehículos y maquinarias para la...,NaN,NaN,5e46b4f7-3b99-4e5f-ad7f-3dcc351262c7,Gobierno Departamental de Cordillera,NaN,NaN,NaN,NaN,80048600-5,819bbfb3-bacc-427e-946f-0d9b7ba56f8c,MOTORMARKET S.A.,NaN,FERNANDO DE LA MORA,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2017-10-23,https://www.contrataciones.gov.py:443/datos/ap...,2017,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21088.0,21137.0,21047.0,21066.0,25101507.0,CPV2008
1,0000d077-12aa-48e5-8393-1f8684a17820,Adquisición de vehículos y maquinarias para la...,NaN,Licitación Pública Nacional,NaN,3,"25181709-004,",NaN,1.272480e+09,1.100000e+09,Adquisición de vehículos y maquinarias para la...,NaN,NaN,5e46b4f7-3b99-4e5f-ad7f-3dcc351262c7,Gobierno Departamental de Cordillera,NaN,NaN,NaN,NaN,80002612-8,368896ea-2108-493c-815b-fbefc28b7b4b,RIEDER Y CIA. SACI,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2017-10-23,https://www.contrataciones.gov.py:443/datos/ap...,2017,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21088.0,21137.0,21047.0,21066.0,25181709.0,CPV2008
2,0000e371-dca5-4760-8c4e-93fd4f82bcf7,"ALQUILER DE MAQUINARIAS Y EQUIPOS, DE COMPUTAC...",NaN,Contratación Directa,NaN,1,"80161504-001,",NaN,6.300000e+06,6.300000e+06,"ALQUILER DE MAQUINARIAS Y EQUIPOS, DE COMPUTAC...",NaN,NaN,23b37914-6261-48f1-9e72-409adeff2e59,Facultad de Ciencias Economicas / Universidad ...,NaN,NaN,NaN,NaN,3358978-0,da7fbca3-024f-4b9e-b824-635fac3cae6d,DANIEL ELIAS SERVIN CESPEDES,NaN,PILAR,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-07-12,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18785.0,18820.0,18777.0,18777.0,80161504.0,CPV2008
3,0000f14e-0fae-44de-99a8-fe84adbce19c,Seguro para Vehiculos,NaN,Contratación Directa,NaN,1,"84131503-001,",NaN,6.600000e+06,6.600000e+06,Seguro para Vehiculos,NaN,NaN,3f2429eb-1fe6-46d1-94ca-b34c80e3eae6,Facultad de Ciencias Economicas / Universidad ...,NaN,NaN,NaN,NaN,80031893-5,d690b1f3-8193-41e9-bf59-1bd45fa1b185,ASEGURADORA DEL SUR SA SEGUROS GENERALES (ASUR),NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2018-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2018,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21264.0,21293.0,21210.0,21257.0,84131503.0,CPV2008
4,00020730-a5d5-4427-88d8-df38f3de5299,CONSTRUCCIÓN DE PAVIMENTO TIPO EMPEDRADO,NaN,Concurso de Ofertas,NaN,1,"72131701-002,72131601-013,72102304-005,8210150...",NaN,4.986200e+08,4.986200e+08,CONSTRUCCIÓN DE PAVIMENTO TIPO EMPEDRADO,NaN,NaN,c00fd959-35ac-4d46-bb44-25d6f65e573e,Gobierno Departamental de Canindeyú,NaN,NaN,NaN,NaN,2979720-9,a0603bb1-6c78-4e55-b36e-50389cce3506,GENARO ANDRES FARIÑA,NaN,FCO. CABALLERO ALVAREZ,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-08-14,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19211.0,19219.0,19058.0,19193.0,72131701.0,CPV2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166005,fffc0084-b859-430e-b8dc-803e242acc27,Refacción de Edificio Municipal,NaN,Concurso de Ofertas,NaN,1,"72131601-001,",NaN,3.617825e+08,3.617825e+08,Refacción de Edificio Municipal,NaN,NaN,ff6d1c89-a10a-4996-8883-0576047c0b21,Municipalidad de Yuty,NaN,NaN,NaN,NaN,1396362-7,191dd94c-a328-4465-89ea-60e8f9d93955,ESTEBAN ERMINDO GERTOPAN GOMEZ,NaN,ITA,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2013-05-16,https://www.contrataciones.gov.py:443/datos/ap...,2013,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19473.0,19480.0,19416.0,19458.0,72131601.0,CPV2008
166006,fffe1f3b-ccbc-4988-a23d-7ab821630f78,Servicio de Ceremonial - Provisión de Pasajes ...,NaN,Contratación Directa,NaN,4,"78111502-002,",NaN,1.500000e+08,1.500000e+08,Servicio de Ceremonial - Provisión de Pasajes ...,NaN,NaN,c6d4ee51-85bc-4854-a18e-4a6fadb59c60,Centro Cultural de la Republica - El Cabildo /...,NaN,NaN,NaN,NaN,80001145-7,d8a19c74-7bbb-40ae-af17-8607764a5956,PREMIER S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2017-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2017,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,20864.0,20902.0,20845.0,20845.0,78111502.0,CPV2008
166007,fffeaddf-8e21-471d-8571-98b2a8754705,Adquisición de Ambulancia,NaN,Concurso de Ofertas,NaN,2,"25101703-002,",NaN,6.380000e+08,6.380000e+08,Adquisición de Ambulancia,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80002612-8,368896ea-2108-493c-815b-fbefc28b7b4b,RIEDER Y CIA. SACI,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-10-21,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19984.0,20017.0,19946.0,19962.0,25101703.0,CPV2008
166008,fffedbdd-9ab5-4d75-a0d6-8c2f2118eb82,Adquisición de freezer,NaN,Contratación Directa,NaN,1,"52141507-001,",NaN,2.990800e+06,2.990800e+06,Adquisición de freezer,NaN,NaN,6a969918-cd10-4d6d-8cf7-aee775651172,Ministerio de la Mujer,NaN,NaN,NaN,NaN,694840-5,35ddc640-461b-4916-b439-d9a70a69fc8d,VALVINA MARIN FRANCO,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2010-11-29,https://www.contrataciones.gov.py:443/datos/ap...,2010,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18589.0,18595.0,18571.0,18581.0,52141507.0,CPV2008
166009,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,"39101605-001,31201502-003,39101601-002,3911150...",NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008

In [6]:
uruguay_procurement_data = pd.read_csv(os.path.join(data_folder, main_uruguay_procurement_file))
uruguay_procurement_data

,tender_id,tender_title,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,tender_contractsignaturedate,lot_productCode,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_nuts,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_nuts,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_publications_lastcallfort,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,currency,tender_proceduretype,tender_biddeadline,tender_awarddecisiondate,tender_publications_firstcallfor,lot_localProductCode,lot_localProductCode_type,tender_integrity_winner_ca_share
0,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,"35905,35902,1879,1880,1133,",NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN
1,UY_4939b253f303e7e80ca6747952cafbcf6e1b3d01_1,Licitación Abreviada 51/2010,Licitación Abreviada,NaN,1,NaN,"15058,15323,",NaN,NaN,R/210276500016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210276500016,9761d34b-9a31-4e73-add1-1df39efb5934,PROVIMAR LTDA.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2010-12-03,NaN,NaN,2010,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,18578.0,18599.0,NaN,"15058,15",CPV2008,NaN
2,UY_1314810c6d1f010c6123f97ae8be72ef29e884dd_1,Licitación Abreviada 10/2011,Licitación Abreviada,NaN,1,NaN,"13370,118,304,8336,185,10838,16,23,8482,6679,1...",NaN,NaN,R/214874940012,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/214874940012,f7e1bf2e-7644-4b3f-9db7-9135bff8899e,PAPELCUR SOCIEDAD ANONIMA,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2012-10-11,NaN,2012-03-12,2012,0.0,0.0,100.0,100,100.0,NaN,NaN,OPEN,19079.0,19277.0,19064.0,"13370,11",CPV2008,NaN
3,UY_ddbbcd4eb74f0a0b15fec0091738bd3f5977dc2d_1,Licitación Pública 10/2006,Licitación Pública,NaN,1,NaN,"14022,29369,148,",NaN,NaN,R/211603980013,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/211603980013,8bf14c4b-b8ba-4d1c-a1a9-6f87e544a5cf,DISTRIBUIDORA SANTA ANA S A,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2006-05-16,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,16887.0,16937.0,NaN,"14022,29",CPV2008,NaN
4,UY_b7dad33fc4bbffd6c1d004919f3c82cab54e3d99_1,Licitación Pública 7/2005,Licitación Pública,NaN,1,NaN,"16610,26399,25932,31427,31461,3222,31464,26311...",NaN,NaN,R/211396450014,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/211396450014,67c1edf3-b343-4568-91db-a6a987b8c1fb,URUFARMA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2006-04-28,NaN,NaN,2005,0.0,0.0,100.0,100,100.0,NaN,NaN,OPEN,16733.0,16919.0,NaN,"16610,26",CPV2008,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945083,UY_fce415971ee3822246a88eb29185c386bfb15739_1,NaN,NaN,NaN,1,NaN,"0,",NaN,NaN,T/99042,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/214130990011,46980efa-aae8-4ec3-8f34-eca498b5effa,ADMINISTRACION NACIONAL DE CORREOS,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2002-05-20,NaN,NaN,2002,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,15399.0,NaN,"0,",CPV2008,99.365898
945084,UY_2e76ea98af0be5415e061cfad40d11d5647e255f_1,Compra Directa 9017/2010,Compra Directa,NaN,1,NaN,"34036,8317,",NaN,NaN,R/210184230012,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210184230012,7af0c3f2-3608-4629-9bc7-601659f38420,BELLO LTDA.-,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2010-05-20,NaN,2010-04-30,2010,0.0,0.0,0.0,100,100.0,NaN,NaN,OUTRIGHT_AWARD,18393.0,18402.0,18382.0,"34036,83",CPV2008,99.899620
945085,UY_070e34fcc63f55a7019a3a90c7c0459bf82a9540_1,NaN,NaN,NaN,1,NaN,"1125,",NaN,NaN,R/150112370015,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/150112370015,f1dce34e-394a-4469-922c-e07069bb2e45,COLECTIVO MEDICO ROCHENSE I.A.M.P.P.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2016-02-05,NaN,NaN,2016,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,20404.0,NaN,"1125,",CPV2008,100.000000
945086,UY_58750a44a4fb172bfc70937ded2d4dab60326a72_1,NaN,NaN,NaN,1,NaN,"0,",NaN,NaN,R/210651680018,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210651680018,71eb3a4d-1877-48ba-91bf-b4298098fa4b,SELECTRON LTDA.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2003-08-13,NaN,NaN,2003,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,15921.0,NaN,"0,",CPV2008,99.985397
945087,UY_8f48e3f3b0257b52935d76450935f3c5b6bb3da4_1,NaN,NaN,NaN,1,NaN,"2153,",NaN,NaN,R/210218980019,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210218980019,f69883d3-3fd8-4ffd-85eb-a53dc31fe34f,LOPEZ Y PARDIÑAS LTDA,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2006-11-16,NaN,NaN,2006,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,17121.0,NaN,"2153,",CPV2008,99.424095

In [7]:
world_inflation_data = pd.read_csv(os.path.join(data_folder, world_inflation_file), skiprows = 4)
paraguay_inflation_data = world_inflation_data[world_inflation_data['Country Name'] == 'Paraguay']
world_inflation_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.315247,3.656365,2.529129,3.397787,3.608024,5.392568,8.955987,-2.135429,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.657460,8.718931,4.509237,8.459872,8.939647,5.748831,5.370290,5.245878,6.596505,6.399343,4.720805,4.644967,5.405162,7.240978,10.773751,7.126975,4.425471,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.784597,8.680571,26.418664,-6.811161,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.369135,8.452976,4.415004,2.207835,4.018699,4.578375,2.439201,1.768436,2.130817,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.930929,5.489286,3.615966,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.224144,43.542107,22.953514,13.305210,12.251497,12.475829,13.730284,14.469656,13.482468,10.277905,8.777814,7.280387,9.355972,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.621647,4.358497,9.350418,-2.410264,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691,11.580510,4.944324,1.619450,NaN
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.543562,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288877,2.102351,1.246275,1.337971,2.534989,4.069019,3.489237,3.538966,1.986134,3.238217,4.991925,5.957421,6.425676,9.433984,11.724132,13.425925,11.020411,11.151958,11.135609,13.293662,13.66024,15.254234,14.639041,12.303205,11.526481,16.294225,18.654923,16.160595,12.779553,14.730875,14.320992,15.334779,13.874704,9.717427,8.938564,8.680424,7.35412,8.597776,6.880545,5.181489,5.338959,5.701895,9.494714,5.679424,-0.692039,2.062853,3.243908,6.177812,9.909985,7.238095,4.067496,5.000853,5.737971,5.780169,6.132830,4.518691,6.602908,5.186187,4.509873,4.102851,3.232388,4.618745,7.039873,6.075244,4.361152,NaN
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.733060,22.020768,10.993204,10.884532,14.985626,NaN
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.022670,3.466130,3.725327,1.634950,-0.197785,-2.430968,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105,104.705171,NaN,NaN,NaN

### The File which Contains the UNSPSC Classifications

In [8]:
unspsc_classifications = pd.read_excel(os.path.join(data_folder, unspsc_classifications_file)).dropna(subset = ['Parent key'])
unspsc_classifications

,Key,Parent key,Code,Title
10,100001,1.000000e+02,10000000,Live Plant and Animal Material and Accessories...
11,100002,1.000010e+05,10100000,Live animals
12,100003,1.000020e+05,10101500,Livestock
13,100004,1.000030e+05,10101501,Cats
14,100005,1.000030e+05,10101502,Dogs
...,...,...,...,...
13288,2137002045,4.479407e+08,57030303,Water distribution kit
13289,2138314803,1.769071e+09,57030109,Trauma and emergency surgery kit
13290,2138640862,1.015260e+05,25131511,"Aircraft, Twin Engine"
13291,2140382544,1.075370e+05,25173121,Distance Measuring Equipment (DME) System
13292,2147080441,1.811960e+05,51192458,Calcium carbonate/calcium gluconate lactate

# Data Preprocessing

It appears that there are some obvious issues with the Classifications File, as Parent Key is looking like an integer when it is a categorical variable. Will also inspect the code and key variables

In [9]:
unspsc_classifications.dtypes

Key             int64
Parent key    float64
Code           object
Title          object
dtype: object

In [10]:
unspsc_classifications['Parent key'] = unspsc_classifications['Parent key'].astype(int)
unspsc_classifications['Parent key'] = unspsc_classifications['Parent key'].astype(str)
unspsc_classifications['Key'] = unspsc_classifications['Key'].astype(str)

In [11]:
unspsc_classifications.dtypes

Key           object
Parent key    object
Code          object
Title         object
dtype: object

In [12]:
unspsc_classifications

,Key,Parent key,Code,Title
10,100001,100,10000000,Live Plant and Animal Material and Accessories...
11,100002,100001,10100000,Live animals
12,100003,100002,10101500,Livestock
13,100004,100003,10101501,Cats
14,100005,100003,10101502,Dogs
...,...,...,...,...
13288,2137002045,447940749,57030303,Water distribution kit
13289,2138314803,1769071149,57030109,Trauma and emergency surgery kit
13290,2138640862,101526,25131511,"Aircraft, Twin Engine"
13291,2140382544,107537,25173121,Distance Measuring Equipment (DME) System
13292,2147080441,181196,51192458,Calcium carbonate/calcium gluconate lactate

### Looking at the different variables of each dataset

The variables the final dataset in the paper included information such as:
- procedure type for tendering 
- number of received bids
- names of buyers and bidders
- tender notice dates
- tender deadlines
- tender award decision dates

Names of the columns suggesting each of the above preprocessing steps:
- `tender_proceduretype`
- `tender_recordedbidscount`
- `buyer_name` and `bidder_name`
- `tender_publications_firstcallfor`
- `tender_biddeadline`
- `tender_contractsignaturedate`

In [13]:
paraguay_procurement_data.columns

Index(['tender_id', 'tender_title', 'tender_proceduretype',
       'tender_nationalproceduretype', 'tender_supplytype',
       'tender_recordedbidscount', 'lot_productCode',
       'tender_awarddecisiondate', 'tender_finalprice', 'bid_price',
       'lot_title', 'lot_bidscount', 'buyer_id', 'buyer_masterid',
       'buyer_name', 'buyer_geocodes', 'buyer_city', 'buyer_country',
       'buyer_buyertype', 'bidder_id', 'bidder_masterid', 'bidder_name',
       'bidder_geocodes', 'bidder_city', 'bidder_country', 'bid_iswinning',
       'source', 'tender_publications_lastcontract',
       'tender_publications_firstdcontra', 'notice_url', 'tender_year',
       'tender_indicator_integrity_singl', 'tender_indicator_integrity_adver',
       'tender_indicator_integrity_decis', 'tender_indicator_integrity_call_',
       'tender_indicator_integrity_proce', 'tender_indicator_integrity_tax_h',
       'tender_integrity_winner_ca_share', 'currency', 'tender_biddeadline',
       'tender_contractsignaturedate', 'tender_publications_firstcallfor',
       'tender_publications_lastcallfort', 'lot_localProductCode',
       'lot_localProductCode_type'],
      dtype='object')

Names of the columns suggesting each of the above preprocessing steps:
- `tender_proceduretype`
- `tender_recordedbidscount`
- `buyer_name` and `bidder_name`
- `tender_publications_firstcallfor`
- `tender_biddeadline`
- `tender_contractsignaturedate`

## Now Ensuring that Each Column Has the Information Required by the Paper

In [14]:
print_columns_check(uruguay_procurement_data, 'Uruguay')

Procedure Types for Tenders in Uruguay: tender_nationalproceduretype
Compra Directa                              275987
Licitación Abreviada                         63199
Licitación Pública                            9232
Compra por Excepción                          6601
Venta/Arrendamiento por Remate                 541
Procedimiento Especial                         367
PFI - Comparación de precios                   267
Concesión                                       99
Pregón                                          66
Venta/Arrendamiento Licitación Abreviada        45
Venta/Arrendamiento Directa                     30
PFI - Licitación pública internacional          22
PFI - Licitación pública nacional               16
PFI - Contratación directa                      14
Venta/Arrendamiento Licitación Pública           4
Name: count, dtype: int64

Number of Recorded Bids in Uruguay: tender_recordedbidscount
1    945088
Name: count, dtype: int64

Number of Buyers in Uruguay:  357

Number of Bidders in Uruguay:  25917

Tender Publication Call Dates in Uruguay:  tender_publications_firstcallfor
15916.0    180
17687.0    170
17623.0    166
17617.0    161
17751.0    161
          ...
17053.0      1
15714.0      1
20154.0      1
15665.0      1
19672.0      1
Name: count, Length: 4737, dtype: int64

Tender Bid Deadlines in Uruguay:  tender_biddeadline
21649.0    325
21752.0    304
21000.0    282
21682.0    265
21462.0    258
          ...
15459.0      1
17271.0      1
20308.0      1
17754.0      1
17865.0      1
Name: count, Length: 5243, dtype: int64

Tender Award Dates in Uruguay:  Series([], Name: count, dtype: int64)

In [15]:
print_columns_check(paraguay_procurement_data, 'Paraguay')

Procedure Types for Tenders in Paraguay: tender_nationalproceduretype
Contratación Directa                                                                                90265
Concurso de Ofertas                                                                                 32752
Licitación Pública Nacional                                                                         30365
Locación de Inmuebles                                                                                5121
Contratación por Excepción                                                                           4399
Licitación Pública Internacional                                                                      858
BID - Contratación Directa (CD/SD)                                                                    571
BID - Concurso de Ofertas (CO/CP)                                                                     295
BID - Licitación Internacional                                                                        174
BM - Contratación Directa - CD                                                                        139
BID - Licitación Pública Nacional                                                                     134
Selección sobre la base la comparación de las calificaciones                                          132
BM - Concurso de Ofertas - CO                                                                         119
Selección basada en la calidad y el costo                                                              86
BM - Licitación Pública Internacional - LPI                                                            80
BM - Licitación Pública Nacional - LPN                                                                 77
Acuerdo Nacional                                                                                       70
BID - Contratación por Excepción                                                                       69
Selección basada en las calificaciones de los consultores                                              46
LCO_SBE_DNCP_BID - LICITACIÓN POR CONCURSO DE OFERTA POR SBE SISTEMA NACIONAL BID BIENES COMUNES       43
Selección basada en la calidad                                                                         34
LPN_SBE_DNCP_BID - LICITACIÓN PUBLICA NACIONAL POR SBE SISTEMA NACIONAL BID BIENES COMUNES             33
Selección basada en el menor costo                                                                     33
CD_SBE_DNCP_BID - CONTRATACIÓN DIRECTA POR SBE SISTEMA NACIONAL BID PARA BIENES COMUNES                25
BID - Locación de Inmuebles                                                                            23
BM - Contratación por Excepción - CE                                                                   18
BM - Selección basada en la calidad y el costo                                                         17
Selección cuando el presupuesto es fijo                                                                11
BM - Selección basada en el menor costo                                                                10
BM - Selección basada en las calificaciones de consultores                                              6
Acuerdo Internacional                                                                                   4
LCO_DNCP_BID_OBRAS - LICITACIÓN POR CONCURSO DE OFERTA SISTEMA NACIONAL BID OBRAS SIMPLES               1
Name: count, dtype: int64

Number of Recorded Bids in Paraguay: tender_recordedbidscount
1      90945
3      17513
2      13993
4      10681
5       7657
       ...
67         2
108        2
91         1
71         1
109        1
Name: count, Length: 80, dtype: int64

Number of Buyers in Paraguay:  454

Number of Bidders in Paraguay:  14497

Tender Publication Call Dates in Paraguay:  tender_publications_firstcallfor
20881.0    924
21614.0    864
21248.0    838
19059.0    789
21613.0    744
          ...
18280.0      1
21863.0      1
20042.0      1
18282.0      1
20814.0      1
Name: count, Length: 2507, dtype: int64

Tender Bid Deadlines in Paraguay:  tender_biddeadline
19694.0    605
19330.0    410
21164.0    324
20066.0    321
20797.0    301
          ...
21225.0      1
19069.0      1
19118.0      1
18530.0      1
20952.0      1
Name: count, Length: 2808, dtype: int64

Tender Award Dates in Paraguay:  tender_contractsignaturedate
18966.0    966
18599.0    758
21900.0    607
18963.0    583
19710.0    548
          ...
19776.0      1
21192.0      1
20659.0      1
22197.0      1
19784.0      1
Name: count, Length: 3251, dtype: int64

### Checking All Product Codes to Match Against UNSPSC
<a href="https://www.ungm.org/public/unspsc">Here is the Product Code matching they use</a>

Need to create a dictionary object of all line items that have pharmaceutical related observations, then compare them against what is found in the main country datasets

In [16]:
unspsc_classifications.columns = ['Key', 'Parent key', 'Product Code', 'Title']
unspsc_classifications

,Key,Parent key,Product Code,Title
10,100001,100,10000000,Live Plant and Animal Material and Accessories...
11,100002,100001,10100000,Live animals
12,100003,100002,10101500,Livestock
13,100004,100003,10101501,Cats
14,100005,100003,10101502,Dogs
...,...,...,...,...
13288,2137002045,447940749,57030303,Water distribution kit
13289,2138314803,1769071149,57030109,Trauma and emergency surgery kit
13290,2138640862,101526,25131511,"Aircraft, Twin Engine"
13291,2140382544,107537,25173121,Distance Measuring Equipment (DME) System
13292,2147080441,181196,51192458,Calcium carbonate/calcium gluconate lactate

In [17]:
pharmaceutical_classifications = unspsc_classifications[unspsc_classifications['Title'].str.contains('pharma|drug|medicine|medical|health')]
pharmaceutical_classifications

,Key,Parent key,Product Code,Title
821,102545,102525,95141900,Prefabricated medical buildings and structures
2306,106382,106358,51300000,Antifungal drugs
2324,106409,181731,51281500,Antitubercular drugs
2334,106428,106358,51340000,Antiviral drugs
2382,106512,106358,51120000,Antiarrythmics and antianginals and cardiopleg...
...,...,...,...,...
12812,789763802,1769071149,57030107,Primary healthcare kit
12924,1097150747,115471,42192800,Medical and pharmaceutical biohazard disposal ...
13118,1654384682,1769071149,57030105,Emergency health kit
13127,1667187086,1699154932,57030000,Humanitarian health supplies
13179,1820303875,1769071149,57030106,Epidemy health kit

In [18]:
unspsc_classifications_mapped = unspsc_classifications.set_index('Product Code')['Title'].to_dict()
unspsc_classifications_mapped

{'10000000': 'Live Plant and Animal Material and Accessories and Supplies',
 '10100000': 'Live animals',
 '10101500': 'Livestock',
 '10101501': 'Cats',
 '10101502': 'Dogs',
 '10101506': 'Horses',
 '10101507': 'Sheep',
 '10101508': 'Goats',
 '10101509': 'Asses',
 '10101511': 'Swine',
 '10101512': 'Rabbits',
 '10101513': 'Guinea pigs',
 '10101516': 'Cattle',
 '10101600': 'Birds and fowl',
 '10101601': 'Live chickens',
 '10101602': 'Live ducks',
 '10101603': 'Live turkeys',
 '10101604': 'Live geese',
 '10101605': 'Live pheasants',
 '10101700': 'Live fish',
 '10101701': 'Live salmon',
 '10101800': 'Shellfish and aquatic invertebrates',
 '10101801': 'Live shrimp',
 '10101900': 'Insects',
 '10101903': 'Bees',
 '10101904': 'Silkworms',
 '10120000': 'Animal feed',
 '10121500': 'Livestock feed',
 '10121501': 'Pure wheat bran',
 '10121600': 'Bird and fowl food',
 '10121601': 'Live food for birds',
 '10121700': 'Fish food',
 '10121701': 'Fresh or frozen brine',
 '10121800': 'Dog and cat food',
 '10121801': 'Dry food for dogs',
 '10131600': 'Animal containment',
 '10131500': 'Animal shelters',
 '10131601': 'Cages or its accessories',
 '10131701': 'Terrariums',
 '10131602': 'Kennels',
 '10140000': 'Saddlery and harness goods',
 '10141500': 'Saddlery',
 '10141501': 'Saddles',
 '10150000': 'Seeds and bulbs and seedlings and cuttings',
 '10151500': 'Vegetable seeds and seedlings',
 '10152301': 'Bean seeds or seedlings',
 '10152404': 'Carrot seeds or seedlings',
 '10151503': 'Celery seeds or seedlings',
 '10151504': 'Chili seeds or seedlings',
 '10151505': 'Courgette seeds or seedlings',
 '10151506': 'Pea seeds or seedlings',
 '10151507': 'Cucumber seeds or seedlings',
 '10151508': 'Eggplant seeds or seedlings',
 '10151509': 'Endive seeds or seedlings',
 '10151510': 'Garlic seeds or seedlings',
 '10151511': 'Leek seeds or seedlings',
 '10151512': 'Lettuce seeds or seedlings',
 '10151513': 'Corn seeds or seedlings',
 '10151514': 'Melon seeds or seedlings',
 '10151515': 'Onion seeds or seedlings',
 '10152302': 'Soya seeds or seedlings',
 '10151517': 'Spinach seeds or seedlings',
 '10151518': 'Tomato seeds or seedlings',
 '10152402': 'Turnip seeds or seedlings',
 '10151520': 'Chard seeds or seedlings',
 '10151600': 'Cereal seeds',
 '10151601': 'Wheat seeds',
 '10151602': 'Colza seeds',
 '10151603': 'Barley seeds',
 '10151604': 'Millet seeds',
 '10151605': 'Oat seeds',
 '10151606': 'Sesame seeds',
 '10151607': 'Linseed seeds',
 '10151608': 'Castor oil seeds',
 '10151609': 'Maize seeds',
 '10151610': 'Rye seeds',
 '10151611': 'Sorghum seeds',
 '10151700': 'Grass and forage seeds and seedlings',
 '10151614': 'Rice seeds or seedlings',
 '10151800': 'Spice crop seeds and seedlings',
 '10151900': 'Flower seeds and bulbs and seedlings and cuttings',
 '10152000': 'Tree and shrub seeds and cuttings',
 '10152001': 'Fruit tree seeds or cuttings',
 '10152003': 'Nut tree seeds or cuttings',
 '10160000': 'Floriculture and silviculture products',
 '10161500': 'Trees and shrubs',
 '10170000': 'Fertilizers and plant nutrients and herbicides',
 '10171500': 'Organic fertilizers and plant nutrients',
 '10171501': 'Manure or guano',
 '10171502': 'Plant hormones',
 '10171600': 'Chemical fertilizers and plant nutrients',
 '10171601': 'Ammonium nitrate fertilizer',
 '10171602': 'Potassic fertilizer',
 '10171603': 'Phosphatic fertilizer',
 '10171604': 'Sulphuric fertilizer',
 '10171605': 'Nitrogen Phosphorous Potassium Mixtures NPK',
 '10190000': 'Pest control products',
 '10191500': 'Pesticides or pest repellents',
 '10191509': 'Insecticides',
 '10191506': 'Rodenticides',
 '10191700': 'Pest control devices',
 '11000000': 'Mineral and Textile and Inedible Plant and Animal Materials',
 '11100000': 'Minerals and ores and metals',
 '11101500': 'Minerals',
 '11101501': 'Mica',
 '11101506': 'Chalk',
 '11101600': 'Ores',
 '11101700': 'Base Metals',
 '11101800': 'Precious metals',
 '11110000': 'Earth and stone',
 '11111500': 'Dirt and soil',
 '11111501': 'Soil',
 '11111600': 'Stone',
 '11111601': 'Gypsum',
 '11111602': 'Travertine',
 '11111603': 'Ecaussine or alabaster',
 '11111604': 'Granite',
 '11111605': 'Marble',
 '11111606': 'Slate',
 '11111607': 'Sandstone',
 '11111608': 'Limestone',
 '11111700': 'Sand',
 '11111701': 'Silica sand',
 '11111800': 'Clays',
 '11111801': 'Terra cotta',
 '11111802': 'Fireclay',
 '11111803': 'Kaolin or other kaolinic clays',
 '11111804': 'Bentonite',
 '11111805': 'Andalusite',
 '11111806': 'Mullite',
 '11111807': 'Chamotte',
 '11111808': 'Common clay',
 '11111809': 'Ball clay',
 '11111810': 'Fullers earth',
 '11120000': 'Non edible plant and forestry products',
 '11121500': 'Sap',
 '11121502': 'Rosin',
 '11121600': 'Wood',
 '11121603': 'Logs',
 '11121604': 'Soft timber',
 '11121605': 'Rattan',
 '11121606': 'Cork',
 '11121607': 'Wood pulp',
 '11121608': 'Bamboo',
 '11121700': 'Forestry byproducts',
 '11121800': 'Plant fibers',
 '11130000': 'Non edible animal products',
 '11131500': 'Animal hides and skins and animal textile materials',
 '11131501': 'Feathers',
 '11131600': 'Other animal products',
 '11131602': 'Semen',
 '11131607': 'Embryos',
 '11140000': 'Scrap and waste materials',
 '11141600': 'Non metallic waste and scrap',
 '11141700': 'Food and tobacco waste and scrap',
 '11150000': 'Fibers and threads and yarns',
 '11151500': 'Fibers',
 '11151600': 'Threads',
 '11151700': 'Yarns',
 '11160000': 'Fabrics and leather materials',
 '11161500': 'Silk fabrics',
 '11161600': 'Wool fabrics',
 '11161700': 'Cotton fabrics',
 '11161800': 'Synthetic fabrics',
 '11162000': 'Fabrics of vegetable material other than cotton',
 '11162100': 'Specialty fabrics or cloth',
 '11162101': 'Cheese cloth or fabric',
 '11162102': 'Bismalemide fabric or cloth',
 '11162104': 'Graphite fabric or cloth',
 '11162105': 'Glass fabric or cloth',
 '11162107': 'Resin impregnated fabric or cloth',
 '11162108': 'Wire mesh fabric or cloth',
 '11162109': 'Lace',
 '11162110': 'Netting',
 '11162111': 'Mesh',
 '11162112': 'Coated fabrics',
 '11162113': 'Upholstery fabrics',
 '12000000': 'Chemicals including Bio Chemicals and Gas Materials',
 '12141800': 'Alkali metals',
 '12142201': 'Deuterated solvents',
 '12142202': 'Heavy water',
 '12142203': 'Alpha sources',
 '12142204': 'Beta sources',
 '12142205': 'Cobalt sources',
 '12142206': 'Gamma sources',
 '12142207': 'Radioisotope sources',
 '12142208': 'Calibration sources',
 '12130000': 'Explosive materials',
 '12131500': 'Explosives',
 '12131501': 'Dynamite',
 '12131502': 'Explosive cartridges',
 '12131503': 'Propellant explosives',
 '12131504': 'Explosive charges',
 '12131505': 'Plastic explosives',
 '12131506': 'Aluminized explosives',
 '12131507': 'Ammonium nitrate explosives',
 '12131508': 'Nitroglycerin powder explosives',
 '12131600': 'Pyrotechnics',
 '12131700': 'Igniters',
 '12131702': 'Detonators',
 '12131703': 'Explosives fuses',
 '12131704': 'Explosive initiators',
 '12131705': 'Explosive primers',
 '12131800': 'Propellants',
 '13000000': 'Resin and Rosin and Rubber and Foam and Film and Elastomeric Materials',
 '13100000': 'Rubber and elastomers',
 '13101500': 'Natural rubber',
 '13101600': 'Processed and synthetic rubber',
 '13101700': 'Elastomers',
 '13101900': 'Thermoset plastics',
 '13102000': 'Thermoplastic plastics',
 '13111000': 'Resins',
 '13111202': 'Polyurethane films',
 '14000000': 'Paper Materials and Products',
 '14100000': 'Paper materials',
 '14101500': 'Raw materials',
 '14101501': 'Paper pulp',
 '14120000': 'Industrial use papers',
 '14121500': 'Paperboard and packaging papers',
 '14121901': 'Standard newsprint',
 '14121807': 'Butcher papers',
 '14110000': 'Paper products',
 '14111500': 'Printing and writing paper',
 '14111501': 'Onion skin paper',
 '14111502': 'Vellum paper',
 '14111503': 'Parchment paper',
 '14111504': 'Tractor feed paper',
 '14111505': 'Mimeograph paper',
 '14111506': 'Computer printout paper',
 '14111507': 'Printer or copier paper',
 '14111508': 'Facsimile paper',
 '14111509': 'Stationery',
 '14111510': 'Plotter paper',
 '14111511': 'Writing paper',
 '14111512': 'Graph paper',
 '14111513': 'Ledger paper',
 '14111514': 'Paper pads or notebooks',
 '14111515': 'Calculator or cash register paper',
 '14111516': 'Notebook filler paper',
 '14111806': 'Business forms or questionnaires',
 '14111600': 'Novelty paper',
 '14111601': 'Gift wrapping paper or bags or boxes',
 '14111604': 'Business cards',
 '14111605': 'Greeting or note or post cards',
 '14111700': 'Personal paper products',
 '14111701': 'Facial tissues',
 '14111702': 'Toilet seat covers',
 '14111703': 'Paper towels',
 '14111704': 'Toilet tissue',
 '15000000': 'Fuels and Fuel Additives and Lubricants and Anti corrosive Materials',
 '15100000': 'Fuels',
 '15101500': 'Petroleum and distillates',
 '15101700': 'Fuel Oils',
 '15101502': 'Kerosene',
 '15101503': 'Naphtha',
 '15101504': 'Aviation fuel',
 '15101505': 'Diesel fuel',
 '15101506': 'Gasoline or Petrol',
 '15101507': 'Benzene',
 '15101508': 'Crude oil',
 '15101509': 'Marine fuel',
 '15101600': 'Solid and gel fuels',
 '15110000': 'Gaseous fuels and additives',
 '15111500': 'Gaseous fuels',
 '15111501': 'Propane',
 '15111502': 'Methane',
 '15111503': 'Propylene',
 '15111504': 'Ethylene',
 '15111505': 'Butane',
 '15120000': 'Lubricants and oils and greases and anti corrosives',
 '15121500': 'Lubricating preparations',
 '15121501': 'Engine oil',
 '15121504': 'Hydraulic oil',
 '15121508': 'Transmission oil',
 '12181500': 'Waxes',
 '15121800': 'Anti corrosives',
 '15130000': 'Fuel for nuclear reactors',
 '15131500': 'Nuclear fuel',
 '15131601': 'Nuclear fuel rod',
 '15131502': 'Depleted uranium',
 '15131503': 'Enriched uranium',
 '15131504': 'Iridium',
 '15131505': 'Enriched plutonium',
 '15131506': 'Depleted plutonium',
 '20000000': 'Mining and Well Drilling Machinery and Accessories',
 '20100000': 'Mining and quarrying machinery and equipment',
 '20101500': 'Cutting equipment',
 '20101501': 'Continuous mining equipment',
 '20101502': 'Longwall shears',
 '20101600': 'Screens and feeding equipment',
 '20101700': 'Crushers and breakers and grinders',
 '20101709': 'Ball mills',
 '20110000': 'Well drilling and operation equipment',
 '20111500': 'Drilling and exploration equipment',
 '20111504': 'Water well drilling equipment',
 '20111505': 'Uranium exploration equipment',
 '20111600': 'Drilling and operation machinery',
 '20102100': 'Rock drills',
 '20111700': 'Drilling and operation accessories',
 '21000000': 'Farming and Fishing and Forestry and Wildlife Machinery and Accessories',
 '21100000': 'Agricultural and forestry and landscape machinery and equipment',
 '21101500': 'Agricultural machinery for soil preparation',
 '21101501': 'Ploughs',
 '21101502': 'Harrows',
 '21101503': 'Cultivators',
 '21101504': 'Weeders',
 '21101505': 'Hoeing machines',
 '21101506': 'Graders or land levelers',
 '21101507': 'Agricultural rollers',
 '21101508': 'Rollers for lawn or sports grounds',
 '21101509': 'Trencher drainage machine',
 '21102501': 'Irrigation trickles',
 '21102502': 'Irrigation overheads',
 '21101600': 'Agricultural machinery for planting and seeding',
 '21101601': 'Planters',
 '21101700': 'Agricultural machinery for harvesting',
 '21101701': 'Mowers',
 '21101703': 'Harvesters',
 '21101705': 'Threshing machines',
 '21101800': 'Dispersing and spraying appliances for agriculture',
 '21101801': 'Sprayers',
 '21101802': 'Dusters',
 '21101803': 'Water sprinklers',
 '21101804': 'Fertilizer spreaders or distributors',
 '21101805': 'Fog or mist generators',
 '21101806': 'Composter',
 '21101807': 'Pollination equipment or supplies',
 '21101808': 'Frost protection equipment',
 '21101900': 'Poultry and livestock equipment',
 '21101901': 'Milking machines',
 '21101903': 'Incubators or brooders for poultry',
 '21101905': 'Livestock identification equipment',
 '21101906': 'Egg inspection or collecting equipment',
 '21102000': 'Agricultural machinery for cleaning and sorting and grading',
 '21102001': 'Cleaning machines for seed or grain or dried leguminous vegetables',
 '21102002': 'Sorting machines for seed or grain or dried leguminous vegetables',
 '21102100': 'Agricultural processing machinery and equipment',
 '21102200': 'Forestry machinery and equipment',
 '21102300': 'Greenhouse equipment',
 '21102400': 'Insect equipment',
 '21102401': 'Beekeeping equipment',
 '21110000': 'Fishing and aquaculture equipment',
 '21111500': 'Commercial fishing equipment',
 '21111501': 'Commercial fish hooks',
 '21111504': 'Commercial fishing nets',
 '21111600': 'Aquaculture equipment',
 '22000000': 'Building and Construction Machinery and Accessories',
 '22100000': 'Heavy construction machinery and equipment',
 '22101500': 'Earth moving machinery',
 '22101501': 'Front end loaders',
 '22101502': 'Graders',
 '22101504': 'Pile drivers',
 '22101505': 'Rollers',
 '22101507': 'Tampers',
 '22101508': 'Trenching machines',
 '22101509': 'Backhoes',
 '22101511': 'Compactors',
 '22101513': 'Draglines',
 '22101514': 'Dredgers',
 '22101516': 'Ditchers',
 '22101600': 'Paving equipment',
 '22101700': 'Heavy equipment components',
 '23000000': 'Industrial Manufacturing and Processing Machinery and Accessories',
 '23100000': 'Raw materials processing machinery',
 '23101500': 'Machinery for working wood and stone and ceramic and the like',
 '23101501': 'Coping machines',
 '23101513': 'Milling machines',
 '23110000': 'Petroleum processing machinery',
 '23120000': 'Textile and fabric machinery and accessories',
 '23121500': 'Textile processing machinery and accessories',
 '23121501': 'Embroidery making machines',
 '23121600': 'Textile working machinery and equipment and accessories',
 '23121614': 'Sewing machines',
 '23130000': 'Lapidary machinery and equipment',
 '23131500': 'Grinding and sanding and polishing equipment and supplies',
 '23131501': 'Abrasive compounds',
 '23131503': 'Grinding wheels',
 '23131600': 'Faceting equipment and accessories',
 '23131700': 'Cabbing equipment',
 '23140000': 'Leatherworking repairing machinery and equipment',
 '23141600': 'Leather preparing machinery and accessories',
 '23141601': 'Leather fleshing machines',
 '23141700': 'Leather working and repairing machinery and accessories',
 '23150000': 'Industrial process machinery and equipment and supplies',
 '23151500': 'Rubber and plastic processing machinery and equipment and supplies',
 '23151600': 'Cement and ceramics and glass industry machinery and equipment and supplies',
 '23151700': 'Optical industry machinery and equipment and supplies',
 '23151800': 'Pharmaceutical industry machinery and equipment and supplies',
 '23151900': 'Paper making and paper processing machinery and equipment and supplies',
 '23160000': 'Foundry machines and equipment and supplies',
 '23161500': 'Foundry machines and equipment',
 '23161501': 'Foundry blowers',
 '23161600': 'Foundry supplies',
 '23271812': 'Welding rod',
 '23180000': 'Industrial food and beverage equipment',
 '23181500': 'Food preparation machinery',
 '23181501': 'Filling machinery',
 '23181502': 'Milling machinery',
 '23181507': 'Crushing machinery',
 '23181600': 'Food cutting machinery',
 '23181601': 'Dicing machinery',
 '23181700': 'Food cooking and smoking machinery',
 '23181800': 'Industrial beverage processing machinery',
 '24000000': 'Material Handling and Conditioning and Storage Machinery and their Accessories and Supplies',
 '24100000': 'Material handling machinery and equipment',
 '24101500': 'Industrial trucks',
 '24101501': 'Carts',
 '24101502': 'Bulk transporters',
 '24101503': 'Dollies',
 '24101504': 'Hand trucks or accessories',
 '24101505': 'Pallet trucks',
 '24101506': 'Pushcarts',
 '24101507': 'Wheelbarrows',
 '24101600': 'Lifting equipment and accessories',
 '24101601': 'Elevators',
 '24101602': 'Hoists',
 '24101603': 'Forklifts',
 '24101604': 'Lifts',
 '24101605': 'Loading equipment',
 '24101606': 'Stackers',
 '24101608': 'Winches',
 '24101700': 'Conveyors and accessories',
 '24101706': 'Trolleys or accessories',
 '24101800': 'Dock equipment',
 '24101900': 'Drum handling equipment',
 '24102000': 'Shelving and storage',
 '24112700': 'Pallets',
 '24102100': 'Warehousing equipment and supplies',
 '24102101': 'Cargo handling equipment',
 '24102102': 'Warehouse carousels',
 '24102103': 'Warehouse casers',
 '24102104': 'Depalletizers',
 '24102105': 'Palletizers',
 '24102106': 'Industrial shrink wrap equipment',
 '24110000': 'Containers and storage',
 '24111500': 'Bags',
 '24111501': 'Canvas bags',
 '24111502': 'Paper bags',
 '24111503': 'Plastic bags',
 '24112500': 'Corrugated and other supplies for distribution',
 '24111800': 'Tanks and cylinders and their accessories',
 '24111801': 'Reservoirs',
 '24111802': 'Air or gas tanks or cylinders',
 '24111803': 'Storage tanks',
 '24111804': 'Calibrating tanks',
 '24111805': 'Chemical tanks',
 '24111806': 'Dip tanks',
 '24111807': 'Expansion tanks',
 '24111808': 'Fuel storage tanks',
 '24111809': 'Processing tanks',
 '24111810': 'Water storage tanks',
 '24112000': 'Bins and baskets',
 '24112100': 'Casks and barrels and drums',
 '24112101': 'Casks',
 '24112200': 'Cans and pails',
 '24122000': 'Bottles',
 '24122002': 'Plastic bottles',
 '24122003': 'Glass bottles',
 '24112400': 'Storage chests and cabinets and trunks',
 '24112401': 'Tool chest or cabinet',
 '24112402': 'Hazardous materials cabinets',
 '24120000': 'Packaging materials',
 '24121500': 'Packaging boxes and bags and pouches',
 '24121502': 'Packaging pouches or bags',
 '24141501': 'Stretch wrap films',
 '24141600': 'Cushioning supplies',
 '24121800': 'Packaging cans',
 '24130000': 'Industrial refrigeration',
 '24131500': 'Industrial refrigerators',
 '24131501': 'Combined refrigerator freezers',
 '24131502': 'Liquid nitrogen refrigerators',
 '24131503': 'Walk in refrigerators',
 '24131504': 'Refrigerated containers',
 '24131505': 'Refrigerated vessels',
 '24131506': 'Refrigerated tanks',
 '24131600': 'Industrial freezers',
 '24131601': 'Chest freezers',
 '24131602': 'Upright cabinet freezer',
 '24131603': 'Low temperature freezers',
 '24131604': 'Freeze drying equipment',
 '24131605': 'Walk in freezers',
 '24131900': 'Ice makers',
 '25000000': 'Commercial and Military and Private Vehicles and their Accessories and Components',
 '25100000': 'Motor vehicles',
 '25101500': 'Passenger motor vehicles',
 '25101501': 'Minibuses',
 '25101502': 'Busses',
 '25101503': 'Automobiles or cars',
 '25101504': 'Station wagons',
 '25101505': 'Minivans or vans',
 '25101506': 'Limousines',
 '25101507': 'Light trucks or sport utility vehicles',
 '25101600': 'Product and material transport vehicles',
 '25101601': 'Dump trucks',
 '25101602': 'Tow trucks',
 '25101604': 'Delivery trucks',
 '25101609': 'Sludge or sewage handling trucks',
 '25101700': 'Safety and rescue vehicles',
 '25101702': 'Police vehicles',
 '25101703': 'Ambulances',
 '25101800': 'Motorized cycles',
 '25101801': 'Motorcycles',
 '25101802': 'Scooters',
 '25101803': 'Mopeds',
 '25101900': 'Specialized and recreational vehicles',
 '25101901': 'Agricultural tractors',
 '25101902': 'Motor homes',
 '25101903': 'Snowmobiles or snow scooter',
 '25101904': 'Golf carts',
 '25102000': 'War vehicles',
 '25102001': 'Tanks',
 '25102002': 'Armored fighting vehicles',
 '25102003': 'Self propelled artillery',
 '25110000': 'Marine transport',
 '25111500': 'Commercial marine craft',
 '25111501': 'Trawlers',
 '25111502': 'Fishing boats',
 '25111503': 'Cargo or container ships',
 '25111504': 'Dredging craft',
 '25111505': 'Tankers',
 '25111506': 'Tug boats',
 '25111507': 'Barges',
 '25111508': 'Passenger or automobile ferries',
 '25111509': 'Cruise ships',
 '25111510': 'Salvage ships',
 '25111600': 'Safety and rescue water craft',
 '25111601': 'Lifeboats or liferafts',
 '25111602': 'Fire fighting watercraft',
 '25111603': 'Rescue ships or boats',
 '25111700': 'Military watercraft',
 '25111800': 'Recreational watercraft',
 '25111801': 'Recreational sailboats',
 '25111802': 'Recreational motorboats',
 '25111803': 'Recreational rowboats',

Preparing the codes for Paraguay Products

In [19]:
paraguay_product_codes = paraguay_procurement_data['lot_productCode'].value_counts().reset_index()
paraguay_product_codes['lot_productCode'] = paraguay_product_codes['lot_productCode'].str.strip(',')

paraguay_product_codes = paraguay_product_codes.assign(lot_productCode = paraguay_product_codes['lot_productCode'].str.split(','))
paraguay_product_codes = paraguay_product_codes.explode('lot_productCode')

paraguay_product_base_codes = paraguay_product_codes.copy()

paraguay_product_base_codes['lot_productCode'] = paraguay_product_base_codes['lot_productCode'].str.split('-').str[0]

paraguay_product_codes = paraguay_product_codes.groupby('lot_productCode', as_index = False)['count'].sum()
paraguay_product_base_codes = paraguay_product_base_codes.groupby('lot_productCode', as_index = False)['count'].sum()
paraguay_product_base_codes

     lot_productCode  count
0           10101502      3
1           10101506     13
2           10101507      6
3           10101508      6
4           10101511     11
...              ...    ...
5840        95121911      2
5841        95131603      1
5842        95131605      2
5843        95131702      1
5844        95141801      5

[5845 rows x 2 columns]

In [20]:
paraguay_product_base_codes

     lot_productCode  count
0           10101502      3
1           10101506     13
2           10101507      6
3           10101508      6
4           10101511     11
...              ...    ...
5840        95121911      2
5841        95131603      1
5842        95131605      2
5843        95131702      1
5844        95141801      5

[5845 rows x 2 columns]

In [21]:
paraguay_product_base_codes.columns = ['Product Code', 'count']
paraguay_product_base_codes

     Product Code  count
0        10101502      3
1        10101506     13
2        10101507      6
3        10101508      6
4        10101511     11
...           ...    ...
5840     95121911      2
5841     95131603      1
5842     95131605      2
5843     95131702      1
5844     95141801      5

[5845 rows x 2 columns]

In [22]:
paraguay_products_titled = pd.merge(paraguay_product_base_codes, pharmaceutical_classifications, how = 'inner', on = 'Product Code')
len(sorted(paraguay_products_titled['Title'].value_counts().to_dict()))

15

# Loading in Each Countries Procurement Catalogs

### Uruguay

In [23]:
uruguay_procurement_data[(uruguay_procurement_data['tender_year'] == 2010)].dropna(subset = ['buyer_name', 'tender_proceduretype'])
uruguay_procurement_data_expanded = expand_procurement_data(uruguay_procurement_data)
uruguay_procurement_data_expanded

,tender_id,tender_title,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,tender_contractsignaturedate,lot_productCode,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_nuts,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_nuts,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_publications_lastcallfort,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,currency,tender_proceduretype,tender_biddeadline,tender_awarddecisiondate,tender_publications_firstcallfor,lot_localProductCode,lot_localProductCode_type,tender_integrity_winner_ca_share,is_exploded_row
0,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,35905,NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN,True
1,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,35902,NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN,True
2,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,1879,NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN,True
3,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,1880,NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN,True
4,UY_abd1516f6b2b558de01ed1989aa7ed05edc9282f_1,Licitación Pública 7/2006,Licitación Pública,NaN,1,NaN,1133,NaN,NaN,R/210000700010,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R/210000700010,00e039fb-71dc-4300-930e-0c69586a08a9,MAPA S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2007-02-07,NaN,NaN,2006,0.0,0.0,50.0,100,100.0,NaN,NaN,OPEN,17097.0,17204.0,NaN,"35905,35",CPV2008,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518156,UY_2e76ea98af0be5415e061cfad40d11d5647e255f_1,Compra Directa 9017/2010,Compra Directa,NaN,1,NaN,34036,NaN,NaN,R/210184230012,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210184230012,7af0c3f2-3608-4629-9bc7-601659f38420,BELLO LTDA.-,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2010-05-20,NaN,2010-04-30,2010,0.0,0.0,0.0,100,100.0,NaN,NaN,OUTRIGHT_AWARD,18393.0,18402.0,18382.0,"34036,83",CPV2008,99.899620,True
3518157,UY_2e76ea98af0be5415e061cfad40d11d5647e255f_1,Compra Directa 9017/2010,Compra Directa,NaN,1,NaN,8317,NaN,NaN,R/210184230012,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210184230012,7af0c3f2-3608-4629-9bc7-601659f38420,BELLO LTDA.-,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2010-05-20,NaN,2010-04-30,2010,0.0,0.0,0.0,100,100.0,NaN,NaN,OUTRIGHT_AWARD,18393.0,18402.0,18382.0,"34036,83",CPV2008,99.899620,True
3518158,UY_070e34fcc63f55a7019a3a90c7c0459bf82a9540_1,NaN,NaN,NaN,1,NaN,1125,NaN,NaN,R/150112370015,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/150112370015,f1dce34e-394a-4469-922c-e07069bb2e45,COLECTIVO MEDICO ROCHENSE I.A.M.P.P.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2016-02-05,NaN,NaN,2016,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,20404.0,NaN,"1125,",CPV2008,100.000000,True
3518159,UY_58750a44a4fb172bfc70937ded2d4dab60326a72_1,NaN,NaN,NaN,1,NaN,0,NaN,NaN,R/210651680018,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210651680018,71eb3a4d-1877-48ba-91bf-b4298098fa4b,SELECTRON LTDA.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2003-08-13,NaN,NaN,2003,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,15921.0,NaN,"0,",CPV2008,99.985397,True
3518160,UY_8f48e3f3b0257b52935d76450935f3c5b6bb3da4_1,NaN,NaN,NaN,1,NaN,2153,NaN,NaN,R/210218980019,1,11-18,259c3f93-7578-4084-8c1d-0b7151ab63a5,DIRECCIÓN GENERAL DE REGISTROS,NaN,NaN,NaN,NaN,R/210218980019,f69883d3-3fd8-4ffd-85eb-a53dc31fe34f,LOPEZ Y PARDIÑAS LTDA,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2006-11-16,NaN,NaN,2006,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,17121.0,NaN,"2153,",CPV2008,99.424095,True

### Loading in the Uruguay Tender Data to match with the Procurement Data

In [24]:
uruguay_date_cols = [
    'tender_biddeadline', 
    'tender_awarddecisiondate',
    'tender_publications_firstcallfor', 
]

uruguay_procurement_data[uruguay_date_cols] = uruguay_procurement_data[uruguay_date_cols].apply(pd.to_datetime, unit = 'd', errors='coerce')
uruguay_procurement_data_years = sorted(uruguay_procurement_data['tender_year'].unique().tolist())

uruguay_tender_files = os.path.join(data_folder, 'uruguay_tender_data')

for year in tqdm(uruguay_procurement_data_years, desc = 'Retrieving Uruguay Tender Data', total = len(uruguay_procurement_data_years)):
    combined_yearly_data_calls = {'releases' : []}
    combined_yearly_data_awards = {'releases' : []}
    annual_tender_files = os.path.join(uruguay_tender_files, str(year))
    
    if not os.path.exists(os.path.join(annual_tender_files, f'l_{year}_data.json')):
        for file in sorted(os.listdir(annual_tender_files)):
            if file.endswith('.json'):
                # print(file)
                if file.startswith('l'):
                    with open(os.path.join(annual_tender_files, file), 'r') as f:
                        tender_data = json.load(f)
                        if 'releases' in tender_data:
                            combined_yearly_data_calls['releases'].extend(tender_data['releases'])

                if file.startswith('a'):
                    with open(os.path.join(annual_tender_files, file), 'r') as j:
                        award_data = json.load(j)
                        if 'releases' in award_data:
                            combined_yearly_data_awards['releases'].extend(award_data['releases'])


        if 'releases' in tender_data:
            for key in tender_data:
                if key != 'releases':
                    combined_yearly_data_calls[key] = tender_data[key]

        if 'releases' in award_data:
            for key in award_data:
                if key != 'releases':
                    combined_yearly_data_awards[key] = award_data[key]

            
                
        with open(os.path.join(annual_tender_files, f'l_{year}_data.json'), 'w') as f:
            json.dump(combined_yearly_data_calls, f, indent = 4)

        with open(os.path.join(annual_tender_files, f'a_{year}_data.json'), 'w') as f:
            json.dump(combined_yearly_data_awards, f, indent = 4)

    else:
        with open(os.path.join(annual_tender_files, f'l_{year}_data.json'), 'r') as f:
            combined_yearly_data_calls = json.load(f)

        with open(os.path.join(annual_tender_files, f'a_{year}_data.json'), 'r') as f:
            combined_yearly_data_awards = json.load(f)

Retrieving Uruguay Tender Data:   0%|          | 0/18 [00:00<?, ?it/s]

## Searching the Uruguayan Catalogs

In [25]:
uruguay_public_procurement_catalog_1 = pd.read_excel(os.path.join(data_folder, 'uruguay_procurement_catalog', uruguay_catalog_file_name_1), header = 1)
uruguay_public_procurement_catalog_2 = pd.read_excel(os.path.join(data_folder, 'uruguay_procurement_catalog', uruguay_catalog_file_name_2), header = 1)
uruguay_public_procurement_catalog_3 = pd.read_excel(os.path.join(data_folder, 'uruguay_procurement_catalog', uruguay_catalog_file_name_3), header = 1)

uruguay_public_procurement_catalog = pd.concat([uruguay_public_procurement_catalog_1,
                                               uruguay_public_procurement_catalog_2,
                                               uruguay_public_procurement_catalog_3],
                                              ignore_index = True)
uruguay_public_procurement_catalog_num_rows = uruguay_public_procurement_catalog_1.shape[0]
uruguay_public_procurement_catalog_num_cols = uruguay_public_procurement_catalog_1.shape[1]

uruguay_public_procurement_catalog.head()

,Cód. Artículo,Artículo,Familia,SubFamilia,Clase,SubClase,Unidad,Variante,Unidad Variante,Color,Tipo Artículo,Tipo Detalle Variante,ODG,Impuesto
0,16589,ABACAVIR (COMPRIMIDOS),MATERIALES Y SUMINISTROS,PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTI...,FARMACOS ANTI-INFECCIOSOS,ANTI-RETROVIRALES,COMPRIMIDO,CONCENTRACION,MG,NaN,Artículo,Medicamento,152000,2%CJPP +IVA MINIMO
1,37147,ABACAVIR/ LAMIVUDINA (COMPRIMIDOS),MATERIALES Y SUMINISTROS,PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTI...,FARMACOS ANTI-INFECCIOSOS,ANTI-RETROVIRALES,COMPRIMIDO (CM),CONCENTRACION,MG/MG,NaN,Artículo,Medicamento,152000,2%CJPP +IVA MINIMO
2,25917,ABACAVIR (SOLUCION ORAL),MATERIALES Y SUMINISTROS,PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTI...,FARMACOS ANTI-INFECCIOSOS,ANTI-RETROVIRALES,FRASCO,CONCENTRACION,MG/ML,NaN,Artículo,Medicamento,152000,2%CJPP +IVA MINIMO
3,100942,ABEMACICLIB (COMPRIMIDOS),MATERIALES Y SUMINISTROS,PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTI...,FARMACOS ONCOLOGICOS,OTROS FARMACOS ONCOLOGICOS,COMPRIMIDO,CONCENTRACION,MG,NaN,Artículo,Medicamento,152000,2%CJPP +IVA MINIMO
4,100963,ACALABRUTINIB (COMPRIMIDOS),MATERIALES Y SUMINISTROS,PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTI...,FARMACOS ONCOLOGICOS,OTROS FARMACOS ONCOLOGICOS,COMPRIMIDO,CONCENTRACION,MG,NaN,Artículo,Medicamento,152000,2%CJPP +IVA MINIMO

Checking for any matching tenders and buyer ids

In [26]:
uruguay_public_procurement_catalog['Cód. Artículo'] = uruguay_public_procurement_catalog['Cód. Artículo'].astype(str)
uruguay_catalog_codes = uruguay_public_procurement_catalog['Cód. Artículo'].unique().tolist()

In [27]:
uruguay_buyer_ids = uruguay_procurement_data_expanded['buyer_id'].unique().tolist()
uruguay_supplier_ids = uruguay_procurement_data_expanded['bidder_id'].unique().tolist()
uruguay_tender_titles = uruguay_procurement_data_expanded['tender_title'].unique().tolist()
uruguay_product_codes = uruguay_procurement_data_expanded['lot_productCode'].unique().tolist()

In [28]:
for year in uruguay_procurement_data_years[0:1]:

# for year in tqdm(uruguay_procurement_data_years, desc = 'Processing Uruguay Tender Data', total = len(uruguay_procurement_data_years)):
    # print(f'Processing year: {year}')
    uruguay_contract_quantities = {}

    print('Analysing Full Tender Data:')
    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'l_{year}_data.json'), 'r') as f:
        tender_data = json.load(f)

        print(tender_data['releases'][0]['id'])
        # for tender in tqdm(tender_data['releases'], desc = f'Processing Tenders for {year}', total = len(tender_data['releases'])):
        for tender in tender_data['releases']:
            try:
        #         print(tender.keys())
                if tender['buyer']['id'] in uruguay_buyer_ids and tender['tender']['title'] in uruguay_tender_titles:
                    # For each matching buyer id and title, get the start and end of the tender period and map the quantity to the product code
                    if tender['tender']['title'] == 'Licitación Abreviada 4/2002' and tender['buyer']['id'] == '4-4':
                        print(tender['tender']['items'])
                #         print(json.dumps(tender_data, indent=4))
                #         tender_periods = tender['tender']['tenderPeriod']
                #         start_date = tender_periods['startDate']
                #         end_date = tender_periods['endDate']

                #         start_date = pd.to_datetime(start_date)
                #         end_date = pd.to_datetime(end_date)

                #         # print(f'Start Date: {start_date}')
                #         # print(f'End Date: {end_date}')

                #         matched_buyer_41_2002 = uruguay_procurement_data_expanded[
                #             (uruguay_procurement_data_expanded['tender_title'] == 'Licitación Abreviada 41/2002') & 
                #             (uruguay_procurement_data_expanded['buyer_id'] == '4-4')
                #         ]

                #         tender_df_match = uruguay_procurement_data_expanded[(uruguay_procurement_data_expanded['buyer_id'] == buyer_id) & 
                #                                                             (uruguay_procurement_data_expanded['tender_title'] == tender['tender']['title'])]
                #         if len(tender_df_match) > 0:
                            
                #             tender_deadline_timestamp = pd.Timestamp(tender_df_match['tender_biddeadline'].values[0])

                #             if tender_deadline_timestamp.tzinfo:
                #                 tender_deadline_timestamp = tender_deadline_timestamp.replace(tzinfo = None)
                #             if end_date.tzinfo:
                #                 end_date = end_date.replace(tzinfo = None)

                #             difference_in_days = (tender_deadline_timestamp - end_date).days
                            
                    

                            # for item in tender['tender']['items']:
                            #     print(item)
                            #     if item['id'] in uruguay_product_codes:
                            #         print(f'Item ID: {item['id']} exists in the catalog')
            except KeyError:
                continue

    print(f'\nAnalysing Awards in {year}:')
    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'a_{year}_data.json'), 'r') as f:
        a_tender_data = json.load(f)
        for tender in a_tender_data['releases']:
            if tender['parties'][0]['id'] == '4-4':
                try:
                    # print(tender['awards'][0]['suppliers'][0])
                    if tender['awards'][0]['suppliers'][0]['id'] == 'R/211267550012':
                        print(f'Found {tender['awards'][0]['suppliers'][0]['name']}')
                        
                        for item in tender['awards'][0]['items']:
                            print(item)
                        print()
                except:
                    continue
            #     except:
            #         continue

Analysing Full Tender Data:
llamado-a25
[{'id': '1', 'description': 'ROLLOS DE PAPEL DE FAX', 'quantity': 2800.0, 'classification': {'id': '0', 'description': 'ROLLOS DE PAPEL DE FAX', 'scheme': 'x_catalogo_arce'}, 'unit': {'name': 'UNIDADES', 'id': ''}}]

Analysing Awards in 2002:
Found PROVEEDORES INDUSTRIALES  S.A.
{'id': 1, 'quantity': 2800.0, 'classification': {'id': '0', 'description': 'ROLLOS DE PAPEL DE FAX', 'scheme': 'x_catalogo_arce'}, 'unit': {'id': '', 'name': 'UNIDADES', 'value': {'amount': 0.91, 'currency': 'USD'}}}

Found PROVEEDORES INDUSTRIALES  S.A.
{'id': 1, 'quantity': 1.0, 'classification': {'id': '0', 'description': 'REPARACION DE MAQUINA', 'scheme': 'x_catalogo_arce'}, 'unit': {'id': '', 'name': 'UNIDAD', 'value': {'amount': 165.0, 'currency': 'UYU'}}}

Found PROVEEDORES INDUSTRIALES  S.A.
{'id': 1, 'quantity': 1.0, 'classification': {'id': '0', 'description': 'BROCHES 7/16 X 7600', 'scheme': 'x_catalogo_arce'}, 'unit': {'id': '', 'name': 'UNIDAD', 'value': {'amount': 166.32, 'currency': 'UYU'}}}
{'id': 2, 'quantity': 1.0, 'classification': {'id': '0', 'description': 'BROCHES 7/11 X 9600', 'scheme': 'x_catalogo_arce'}, 'unit': {'id': '', 'name': 'UNIDAD', 'value': {'amount': 152.78, 'currency': 'UYU'}}}

In [29]:
with open(os.path.join(data_folder, 'uruguay_tender_data', '2002', 'a_2002_data.json'), 'r') as f:
    a_tender_data_2002 = json.load(f)

with open(os.path.join(data_folder, 'uruguay_tender_data', '2002', 'l_2002_data.json'), 'r') as f:
    l_tender_data_2002 = json.load(f)

In [30]:
date_cols = [
    'tender_biddeadline',
    'tender_awarddecisiondate',
    'tender_publications_firstcallfor'
]

unique_num_days = 3652 + 1

for col in date_cols:
    uruguay_procurement_data_expanded[col] = pd.to_datetime(uruguay_procurement_data_expanded[col], unit = 'd', errors = 'coerce')

    uruguay_procurement_data_expanded[f'{col}_corrected'] = (uruguay_procurement_data_expanded[col] - pd.Timedelta(days = unique_num_days))

Matching the buyers with the suppliers to connect into the Uruguayan data

In [57]:
l_tender_data_2002_releases = l_tender_data_2002['releases']
# print(l_tender_data_2002_releases[0].keys())

matched_records = 0

# for year in tqdm(uruguay_procurement_data_years, desc = 'Cross-checking Annual Uruguay Tender Data', total = len(uruguay_procurement_data_years)):

uruguay_procurement_data_expanded['quantity'] = None

for year in tqdm(uruguay_procurement_data_years[0:1], desc = 'Processing Uruguay Tender Data', total = len(uruguay_procurement_data_years)):
    print(f'Processing year: {year}')
    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'l_{year}_data.json'), 'r') as f:
        l_tender_data = json.load(f)

    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'a_{year}_data.json'), 'r') as f:
        a_tender_data = json.load(f)

        awarded_procurement_tender_ids = []

        # for i in tqdm(range(len(a_tender_data['releases'])), desc = f'Creating List of Award IDs for {year}', total = len(a_tender_data['releases'])):
        for i in range(len(a_tender_data['releases'])):
            awarded_procurement_tender_ids.append(a_tender_data['releases'][i]['id'])
    # # for tender in tqdm(l_tender_data['releases'], desc = f'Cross-checking Tenders for {year}', total = len(l_tender_data['releases'])):
    for tender in tqdm(l_tender_data['releases'][0:10], desc = f'Checking Tender Data for {year}', total = len(l_tender_data['releases'][0:10])):
        # Check whether the title in the tender release exists in the uruguay procurement data 
        # Find the tender ID from the main tender releases
        # Check it against the award data and find the ID inside tender['awards'][0]['documents][0]['id]
        # Get the bidder ID from the award data where the tender 
        # Find the matching buyer IDs and tender titles from the uruguay procurement data
        try:
            tender_title = tender['tender']['title']

            if tender_title in uruguay_tender_titles:

                procurement_tender_id = tender['tender'].get('id')
                buyer_id = tender['tender']['procuringEntity']['id']
                if procurement_tender_id:
                    procurement_tender_id_str = str(procurement_tender_id)
                    if any(procurement_tender_id_str in str(aid) or str(aid) in procurement_tender_id_str for aid in awarded_procurement_tender_ids):
                        for idx, a_tender in enumerate(a_tender_data['releases']):
                            
                            matched_bidder = uruguay_procurement_data_expanded[
                                (uruguay_procurement_data_expanded['tender_title'] == tender_title) &
                                (uruguay_procurement_data_expanded['buyer_id'] == buyer_id) 
                                # (uruguay_procurement_data_expanded['bidder_id'] == a_tender['awards'][0]['suppliers'][0]['id'])
                            ]['bidder_id'].values[0]

                            if a_tender['parties'][0]['id'] == buyer_id:
                                try:
                                    if a_tender['awards'][0]['suppliers'][0]['id'] == matched_bidder:
                                        match_date = a_tender['awards'][0]['date']
                                        match_date = pd.to_datetime(match_date).date()

                                        matched_record_df = uruguay_procurement_data_expanded[
                                            (uruguay_procurement_data_expanded['tender_title'] == tender_title) &
                                            (uruguay_procurement_data_expanded['buyer_id'] == buyer_id) &
                                            (uruguay_procurement_data_expanded['tender_awarddecisiondate_corrected'].dt.date == match_date) &
                                            (uruguay_procurement_data_expanded['bidder_id'] == matched_bidder)
                                        ]
                                        
                                        if len(matched_record_df) > 0:
                                            # Calculate total quantity from all items in the award
                                            total_quantity = 0
                                            item_details = []
                                            
                                            for item in a_tender['awards'][0]['items']:
                                                item_quantity = item.get('quantity', 0)
                                                total_quantity += item_quantity
                                                item_desc = item.get('classification', {}).get('description', 'Unknown item')
                                                item_details.append(f"{item_desc}: {item_quantity}")
                                            
                                            # Update all matched records with the total quantity
                                            if total_quantity > 0:
                                                uruguay_procurement_data_expanded.loc[matched_record_df.index.to_list()[0], 'quantity'] = total_quantity
                                                
                                except Exception as e:
                                    print('Failed to retrieve award supplier information', e)
                                    continue

        except KeyError:
            continue

print(f'Total matched records: {matched_records}')

Processing Uruguay Tender Data:   0%|          | 0/18 [00:00<?, ?it/s]

Processing year: 2002

Checking Tender Data for 2002:   0%|          | 0/10 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
uruguay_procurement_data_expanded['quantity'] = None
matched_records = 0
total_processed = 0
successful_matches = 0

for year in tqdm(uruguay_procurement_data_years, desc='Processing Uruguay Tender Data', total=len(uruguay_procurement_data_years)):
    print(f'Processing year: {year}')
    
    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'l_{year}_data.json'), 'r') as f:
        l_tender_data = json.load(f)

    with open(os.path.join(data_folder, 'uruguay_tender_data', str(year), f'a_{year}_data.json'), 'r') as f:
        a_tender_data = json.load(f)

    # Create list of awarded tender IDs
    awarded_procurement_tender_ids = [release['id'] for release in a_tender_data['releases']]
    print(f"Total awarded tenders: {len(awarded_procurement_tender_ids)}")
    
    # Create a lookup for awards by buyer_id for efficiency
    awards_by_buyer = {}
    for a_tender in a_tender_data['releases']:
        if 'parties' in a_tender and len(a_tender['parties']) > 0:
            buyer_id = a_tender['parties'][0]['id']
            if buyer_id not in awards_by_buyer:
                awards_by_buyer[buyer_id] = []
            awards_by_buyer[buyer_id].append(a_tender)
    
    print(f"Awards organized by {len(awards_by_buyer)} buyers")
    
    # Process tenders - increase to [0:50] or remove slice for full processing
    for tender in tqdm(l_tender_data['releases'], desc=f'Processing {year} tenders', leave=False):
        total_processed += 1
        
        try:
            tender_title = tender['tender']['title']
            
            if tender_title not in uruguay_tender_titles:
                continue
                
            procurement_tender_id = tender['tender'].get('id')
            buyer_id = tender['tender']['procuringEntity']['id']
            
            if not procurement_tender_id:
                continue
                
            # Check if this tender has awards
            if buyer_id not in awards_by_buyer:
                continue
            
            procurement_tender_id_str = str(procurement_tender_id)
            
            # Check if tender ID matches any awarded tender ID
            if not any(procurement_tender_id_str in str(aid) or str(aid) in procurement_tender_id_str 
                      for aid in awarded_procurement_tender_ids):
                continue
            
            # Get all potential bidders for this tender/buyer combination
            potential_bidders_query = uruguay_procurement_data_expanded[
                (uruguay_procurement_data_expanded['tender_title'] == tender_title) &
                (uruguay_procurement_data_expanded['buyer_id'] == buyer_id)
            ]
            
            if len(potential_bidders_query) == 0:
                print(f"⚠️  No procurement records found for tender: {tender_title}, buyer: {buyer_id}")
                continue
                
            potential_bidders = potential_bidders_query['bidder_id'].unique()
            print(f"🔍 Found {len(potential_bidders)} potential bidders for tender: {tender_title}")
            
            # Look through awards for this buyer
            for a_tender in awards_by_buyer[buyer_id]:
                try:
                    if ('awards' not in a_tender or len(a_tender['awards']) == 0 or
                        'suppliers' not in a_tender['awards'][0] or len(a_tender['awards'][0]['suppliers']) == 0):
                        continue
                        
                    supplier_id = a_tender['awards'][0]['suppliers'][0]['id']
                    
                    # Check if this supplier is in our potential bidders
                    if supplier_id not in potential_bidders:
                        continue
                    
                    # We found a match!
                    match_date = pd.to_datetime(a_tender['awards'][0]['date']).date()
                    
                    matched_record_df = uruguay_procurement_data_expanded[
                        (uruguay_procurement_data_expanded['tender_title'] == tender_title) &
                        (uruguay_procurement_data_expanded['buyer_id'] == buyer_id) &
                        (uruguay_procurement_data_expanded['tender_awarddecisiondate_corrected'].dt.date == match_date) &
                        (uruguay_procurement_data_expanded['bidder_id'] == supplier_id)
                    ]
                    
                    if len(matched_record_df) > 0:
                        # Calculate total quantity from all items
                        total_quantity = 0
                        item_details = []
                        
                        if 'items' in a_tender['awards'][0]:
                            for item in a_tender['awards'][0]['items']:
                                item_quantity = item.get('quantity', 0)
                                total_quantity += item_quantity
                                item_desc = item.get('classification', {}).get('description', 'Unknown item')
                                item_details.append(f"{item_desc}: {item_quantity}")
                        
                        if total_quantity > 0:
                            # Update all matched records
                            uruguay_procurement_data_expanded.loc[matched_record_df.index, 'quantity'] = total_quantity
                            matched_records += len(matched_record_df)
                            successful_matches += 1
                            
                            print(f'✅ Match #{successful_matches}: Updated {len(matched_record_df)} records')
                            print(f'   Tender: {tender_title}')
                            print(f'   Buyer: {buyer_id}')
                            print(f'   Supplier: {supplier_id}')
                            print(f'   Quantity: {total_quantity}')
                            print(f'   Date: {match_date}')
                            
                            # Break after first successful match for this tender
                            break
                        else:
                            print(f'⚠️  Found match but no quantity data')
                            
                except Exception as e:
                    print(f'❌ Error processing award: {e}')
                    continue
                
        except KeyError as e:
            print(f'❌ KeyError processing tender: {e}')
            continue
        except Exception as e:
            print(f'❌ Unexpected error: {e}')
            continue

print(f'\n🎉 PROCESSING COMPLETE')
print(f'📊 Total tenders processed: {total_processed}')
print(f'✅ Successful matches found: {successful_matches}')
print(f'📝 Total records updated: {matched_records}')
if total_processed > 0:
    print(f'📈 Success rate: {successful_matches/total_processed*100:.2f}%')

Processing Uruguay Tender Data:   0%|          | 0/18 [00:00<?, ?it/s]

Processing year: 2002
Total awarded tenders: 14801
Awards organized by 111 buyers

Processing 2002 tenders:   0%|          | 0/912 [00:00<?, ?it/s]

🔍 Found 1 potential bidders for tender: Licitación Abreviada 4/2002
✅ Match #1: Updated 1 records
   Tender: Licitación Abreviada 4/2002
   Buyer: 4-4
   Supplier: R/211267550012
   Quantity: 2800.0
   Date: 2002-02-20
🔍 Found 2 potential bidders for tender: Licitación Abreviada 9/2002
✅ Match #2: Updated 1 records
   Tender: Licitación Abreviada 9/2002
   Buyer: 4-4
   Supplier: R/020049970016
   Quantity: 10864.0
   Date: 2002-02-20
🔍 Found 3 potential bidders for tender: Licitación Abreviada 2/2002
✅ Match #3: Updated 1 records
   Tender: Licitación Abreviada 2/2002
   Buyer: 4-4
   Supplier: R/210221460012
   Quantity: 4560.0
   Date: 2002-02-22
🔍 Found 3 potential bidders for tender: Licitación Abreviada 5/2002
✅ Match #4: Updated 1 records
   Tender: Licitación Abreviada 5/2002
   Buyer: 4-4
   Supplier: R/210000100013
   Quantity: 10.0
   Date: 2002-02-22
🔍 Found 1 potential bidders for tender: Licitación Abreviada 6/2002
✅ Match #5: Updated 1 records
   Tender: Licitación Abreviada 6/2002
   Buyer: 4-4
   Supplier: R/214148850017
   Quantity: 250000.0
   Date: 2002-03-01
🔍 Found 8 potential bidders for tender: Licitación Abreviada 8/2002
✅ Match #6: Updated 1 records
   Tender: Licitación Abreviada 8/2002
   Buyer: 4-4
   Supplier: R/210000700010
   Quantity: 1552.0
   Date: 2002-03-06
🔍 Found 2 potential bidders for tender: Licitación Abreviada 14/2002
✅ Match #7: Updated 1 records
   Tender: Licitación Abreviada 14/2002
   Buyer: 4-4
   Supplier: R/020049970016
   Quantity: 18042.0
   Date: 2002-03-08
🔍 Found 6 potential bidders for tender: Licitación Abreviada 10/2002
✅ Match #8: Updated 1 records
   Tender: Licitación Abreviada 10/2002
   Buyer: 4-4
   Supplier: R/210166540013
   Quantity: 200.0
   Date: 2002-03-08
🔍 Found 2 potential bidders for tender: Licitación Abreviada 7/2002
✅ Match #9: Updated 1 records
   Tender: Licitación Abreviada 7/2002
   Buyer: 4-4
   Supplier: R/210000400017
   Quantity: 6600.0
   Date: 2002-03-04
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2002
✅ Match #10: Updated 1 records
   Tender: Licitación Abreviada 1/2002
   Buyer: 4-4
   Supplier: R/210160990017
   Quantity: 8000.0
   Date: 2002-03-01
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2002
✅ Match #11: Updated 1 records
   Tender: Licitación Abreviada 2/2002
   Buyer: 2-1
   Supplier: R/210035000015
   Quantity: 2.4
   Date: 2002-03-18
🔍 Found 1 potential bidders for tender: Licitación Abreviada 05/2002
✅ Match #12: Updated 1 records
   Tender: Licitación Abreviada 05/2002
   Buyer: 4-8
   Supplier: R/040096590016
   Quantity: 13000.0
   Date: 2002-03-19
🔍 Found 9 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #13: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-8
   Supplier: R/040199550017
   Quantity: 120076.0
   Date: 2002-03-19
🔍 Found 1 potential bidders for tender: Licitación Abreviada 03/2002
✅ Match #14: Updated 1 records
   Tender: Licitación Abreviada 03/2002
   Buyer: 4-8
   Supplier: R/212163730012
   Quantity: 4.0
   Date: 2002-03-19
🔍 Found 3 potential bidders for tender: Licitación Abreviada 11/2002
✅ Match #15: Updated 1 records
   Tender: Licitación Abreviada 11/2002
   Buyer: 4-4
   Supplier: R/210221460012
   Quantity: 2410.0
   Date: 2002-03-22
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3/2002
✅ Match #16: Updated 1 records
   Tender: Licitación Abreviada 3/2002
   Buyer: 4-4
   Supplier: R/213710970018
   Quantity: 1200.0
   Date: 2002-03-26
🔍 Found 1 potential bidders for tender: Licitación Abreviada 13/2002
✅ Match #17: Updated 1 records
   Tender: Licitación Abreviada 13/2002
   Buyer: 4-4
   Supplier: R/212477120012
   Quantity: 620.0
   Date: 2002-03-22
⚠️  No procurement records found for tender: Licitación Abreviada 25/2001, buyer: 14-1
🔍 Found 3 potential bidders for tender: Licitación Abreviada 1/2002
✅ Match #18: Updated 1 records
   Tender: Licitación Abreviada 1/2002
   Buyer: 4-7
   Supplier: R/030086110014
   Quantity: 2500.0
   Date: 2002-03-19
🔍 Found 5 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #19: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-7
   Supplier: R/030089720018
   Quantity: 2940.0
   Date: 2002-03-19
⚠️  No procurement records found for tender: Licitación Abreviada 08/2002, buyer: 10-3
⚠️  No procurement records found for tender: Licitación Pública 03/2002, buyer: 4-26
⚠️  No procurement records found for tender: Licitación Abreviada 06/2002, buyer: 7-1
⚠️  No procurement records found for tender: Licitación Abreviada 09/2002, buyer: 12-70
⚠️  No procurement records found for tender: Licitación Pública 11/2002, buyer: 12-70
🔍 Found 3 potential bidders for tender: Licitación Abreviada 19/2002
✅ Match #20: Updated 1 records
   Tender: Licitación Abreviada 19/2002
   Buyer: 4-4
   Supplier: R/210221460012
   Quantity: 5635.0
   Date: 2002-04-04
⚠️  No procurement records found for tender: Licitación Abreviada 12/2002, buyer: 3-18
⚠️  No procurement records found for tender: Licitación Abreviada 07/2002, buyer: 4-8
⚠️  No procurement records found for tender: Licitación Abreviada 2/2002, buyer: 4-22
⚠️  No procurement records found for tender: Licitación Abreviada 07/2002, buyer: 7-1
⚠️  No procurement records found for tender: Licitación Pública 08/2002, buyer: 12-70
⚠️  No procurement records found for tender: Licitación Pública 10/2001, buyer: 13-6
⚠️  No procurement records found for tender: Licitación Abreviada 4/2002, buyer: 4-28
⚠️  No procurement records found for tender: Licitación Abreviada 02/2002, buyer: 5-14
⚠️  No procurement records found for tender: Licitación Abreviada 3/2002, buyer: 4-28
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2002
✅ Match #21: Updated 1 records
   Tender: Licitación Abreviada 1/2002
   Buyer: 11-21
   Supplier: R/211742930015
   Quantity: 2475.0
   Date: 2002-04-16
🔍 Found 1 potential bidders for tender: Licitación Pública 1/2002
✅ Match #22: Updated 1 records
   Tender: Licitación Pública 1/2002
   Buyer: 11-19
   Supplier: R/213233280019
   Quantity: 8.9
   Date: 2002-04-08
🔍 Found 2 potential bidders for tender: Licitación Pública 3830/2002
✅ Match #23: Updated 1 records
   Tender: Licitación Pública 3830/2002
   Buyer: 64-1
   Supplier: R/210000700010
   Quantity: 1614.0
   Date: 2002-02-27
🔍 Found 1 potential bidders for tender: Licitación Abreviada 20/2002
✅ Match #24: Updated 1 records
   Tender: Licitación Abreviada 20/2002
   Buyer: 4-4
   Supplier: R/020049970016
   Quantity: 26190.0
   Date: 2002-04-17
🔍 Found 1 potential bidders for tender: Licitación Abreviada 08/2002
✅ Match #25: Updated 1 records
   Tender: Licitación Abreviada 08/2002
   Buyer: 2-1
   Supplier: R/210743540018
   Quantity: 60.0
   Date: 2002-04-18
⚠️  No procurement records found for tender: Licitación Abreviada 6/2002, buyer: 5-13
⚠️  No procurement records found for tender: Licitación Abreviada 4/2002, buyer: 5-13
🔍 Found 1 potential bidders for tender: Licitación Abreviada 001/2002
✅ Match #26: Updated 1 records
   Tender: Licitación Abreviada 001/2002
   Buyer: 4-21
   Supplier: R/212672500015
   Quantity: 9345.79
   Date: 2002-04-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2002
✅ Match #27: Updated 1 records
   Tender: Licitación Abreviada 2/2002
   Buyer: 10-4
   Supplier: R/214556530015
   Quantity: 1.0
   Date: 2002-03-07
🔍 Found 1 potential bidders for tender: Licitación Abreviada 8/2001
✅ Match #28: Updated 1 records
   Tender: Licitación Abreviada 8/2001
   Buyer: 5-2
   Supplier: R/213453280018
   Quantity: 4.0
   Date: 2002-04-05
⚠️  No procurement records found for tender: Licitación Abreviada 01/2002, buyer: 11-12
🔍 Found 3 potential bidders for tender: Licitación Abreviada 17/2002
✅ Match #29: Updated 1 records
   Tender: Licitación Abreviada 17/2002
   Buyer: 4-4
   Supplier: R/210169240010
   Quantity: 20.0
   Date: 2002-04-11
🔍 Found 8 potential bidders for tender: Licitación Pública 1/2002
✅ Match #30: Updated 1 records
   Tender: Licitación Pública 1/2002
   Buyer: 4-4
   Supplier: R/210003280012
   Quantity: 216500.0
   Date: 2002-02-05
🔍 Found 2 potential bidders for tender: Licitación Abreviada 7/2001
✅ Match #31: Updated 1 records
   Tender: Licitación Abreviada 7/2001
   Buyer: 5-2
   Supplier: R/210743540018
   Quantity: 6.0
   Date: 2002-04-05
🔍 Found 1 potential bidders for tender: Licitación Abreviada 004/2002
✅ Match #32: Updated 1 records
   Tender: Licitación Abreviada 004/2002
   Buyer: 11-1
   Supplier: R/212495970014
   Quantity: 1.0
   Date: 2002-04-23
🔍 Found 1 potential bidders for tender: Licitación Abreviada 8/2002
✅ Match #33: Updated 1 records
   Tender: Licitación Abreviada 8/2002
   Buyer: 3-18
   Supplier: R/210253180015
   Quantity: 2500.0
   Date: 2002-04-29
🔍 Found 2 potential bidders for tender: Licitación Abreviada 005/2002
✅ Match #34: Updated 1 records
   Tender: Licitación Abreviada 005/2002
   Buyer: 11-1
   Supplier: R/212674850013
   Quantity: 3000.0
   Date: 2002-04-18
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2002
✅ Match #35: Updated 1 records
   Tender: Licitación Abreviada 2/2002
   Buyer: 11-19
   Supplier: R/214269650019
   Quantity: 8.0
   Date: 2002-04-24
🔍 Found 4 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #36: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-11
   Supplier: R/070062330013
   Quantity: 4500.0
   Date: 2002-02-26
⚠️  No procurement records found for tender: Licitación Abreviada 1/2002, buyer: 3-18
🔍 Found 2 potential bidders for tender: Licitación Abreviada 2/2002
✅ Match #37: Updated 1 records
   Tender: Licitación Abreviada 2/2002
   Buyer: 11-21
   Supplier: R/210001840010
   Quantity: 80000.0
   Date: 2002-04-30
🔍 Found 1 potential bidders for tender: Licitación Abreviada 01/2002
✅ Match #38: Updated 1 records
   Tender: Licitación Abreviada 01/2002
   Buyer: 2-7
   Supplier: R/213644720012
   Quantity: 1.0
   Date: 2002-05-10
⚠️  No procurement records found for tender: Licitación Abreviada 01/2002, buyer: 4-14
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3/2002
✅ Match #39: Updated 1 records
   Tender: Licitación Abreviada 3/2002
   Buyer: 2-7
   Supplier: R/214255840015
   Quantity: 1.0
   Date: 2002-05-09
🔍 Found 4 potential bidders for tender: Licitación Pública URU/01/024/107/2002
✅ Match #40: Updated 1 records
   Tender: Licitación Pública URU/01/024/107/2002
   Buyer: 2-4
   Supplier: R/210440220017
   Quantity: 30.0
   Date: 2002-04-11
🔍 Found 6 potential bidders for tender: Licitación Abreviada 03/2002
✅ Match #41: Updated 1 records
   Tender: Licitación Abreviada 03/2002
   Buyer: 4-14
   Supplier: R/040199550017
   Quantity: 226.0
   Date: 2002-04-19
🔍 Found 1 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #42: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-12
   Supplier: R/090002760016
   Quantity: 1450.0
   Date: 2002-04-17
🔍 Found 1 potential bidders for tender: Licitación Abreviada 03/2002
✅ Match #43: Updated 1 records
   Tender: Licitación Abreviada 03/2002
   Buyer: 12-66
   Supplier: R/212316460016
   Quantity: 25200.0
   Date: 2002-05-09
🔍 Found 2 potential bidders for tender: Licitación Abreviada 27/2002
✅ Match #44: Updated 1 records
   Tender: Licitación Abreviada 27/2002
   Buyer: 4-4
   Supplier: R/020049970016
   Quantity: 15035.0
   Date: 2002-05-17
🔍 Found 6 potential bidders for tender: Licitación Abreviada 001/2002
✅ Match #45: Updated 1 records
   Tender: Licitación Abreviada 001/2002
   Buyer: 3-3
   Supplier: R/210329070010
   Quantity: 1690.0
   Date: 2002-05-16
🔍 Found 2 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #46: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 12-66
   Supplier: R/210125280017
   Quantity: 200.0
   Date: 2002-05-09
⚠️  No procurement records found for tender: Licitación Abreviada 15/2002, buyer: 4-26
🔍 Found 4 potential bidders for tender: Licitación Abreviada 10/2002
✅ Match #47: Updated 1 records
   Tender: Licitación Abreviada 10/2002
   Buyer: 2-1
   Supplier: R/212363900019
   Quantity: 3.0
   Date: 2002-05-17
⚠️  No procurement records found for tender: Licitación Abreviada 01/2002, buyer: 4-11
🔍 Found 3 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #48: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-14
   Supplier: R/120126300012
   Quantity: 3722.0
   Date: 2002-04-30
🔍 Found 3 potential bidders for tender: Licitación Abreviada 11/2002
✅ Match #49: Updated 1 records
   Tender: Licitación Abreviada 11/2002
   Buyer: 4-23
   Supplier: R/030083940016
   Quantity: 460.0
   Date: 2002-04-12
🔍 Found 1 potential bidders for tender: Licitación Abreviada 15/2002
✅ Match #50: Updated 1 records
   Tender: Licitación Abreviada 15/2002
   Buyer: 4-4
   Supplier: R/212455510012
   Quantity: 120.0
   Date: 2002-04-11
🔍 Found 11 potential bidders for tender: Licitación Abreviada 01/2002
✅ Match #51: Updated 1 records
   Tender: Licitación Abreviada 01/2002
   Buyer: 4-12
   Supplier: R/040199550017
   Quantity: 300000.0
   Date: 2002-04-16
🔍 Found 1 potential bidders for tender: Licitación Abreviada 06/2002
✅ Match #52: Updated 1 records
   Tender: Licitación Abreviada 06/2002
   Buyer: 2-1
   Supplier: R/211353630010
   Quantity: 1.0
   Date: 2002-05-13
⚠️  No procurement records found for tender: Licitación Abreviada 12/2002, buyer: 4-26
🔍 Found 2 potential bidders for tender: Licitación Abreviada 002/2002
✅ Match #53: Updated 1 records
   Tender: Licitación Abreviada 002/2002
   Buyer: 11-1
   Supplier: R/211322010010
   Quantity: 1.0
   Date: 2002-04-23
🔍 Found 1 potential bidders for tender: Licitación Abreviada 16/2002
✅ Match #54: Updated 1 records
   Tender: Licitación Abreviada 16/2002
   Buyer: 4-4
   Supplier: R/210001840010
   Quantity: 1624.0
   Date: 2002-04-04
🔍 Found 3 potential bidders for tender: Licitación Abreviada 25/2002
✅ Match #55: Updated 1 records
   Tender: Licitación Abreviada 25/2002
   Buyer: 4-4
   Supplier: R/210221460012
   Quantity: 1430.0
   Date: 2002-04-30
🔍 Found 1 potential bidders for tender: Licitación Abreviada 06/2002
✅ Match #56: Updated 1 records
   Tender: Licitación Abreviada 06/2002
   Buyer: 12-66
   Supplier: R/213288390010
   Quantity: 28000.0
   Date: 2002-05-27
🔍 Found 6 potential bidders for tender: Licitación Abreviada 09/2002
✅ Match #57: Updated 1 records
   Tender: Licitación Abreviada 09/2002
   Buyer: 4-26
   Supplier: R/210307720012
   Quantity: 500.0
   Date: 2002-04-18
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3376/2002
🔍 Found 14 potential bidders for tender: Licitación Abreviada 10/2002
✅ Match #58: Updated 1 records
   Tender: Licitación Abreviada 10/2002
   Buyer: 4-26
   Supplier: R/210116670010
   Quantity: 60.0
   Date: 2002-05-23
⚠️  No procurement records found for tender: Licitación Abreviada 05/2002, buyer: 12-66
⚠️  No procurement records found for tender: Licitación Abreviada 3/2002, buyer: 14-1
⚠️  No procurement records found for tender: Licitación Abreviada 08/2002, buyer: 7-1
🔍 Found 1 potential bidders for tender: Licitación Abreviada 22/2002
✅ Match #59: Updated 1 records
   Tender: Licitación Abreviada 22/2002
   Buyer: 4-4
   Supplier: R/210308100018
   Quantity: 1.0
   Date: 2002-05-17
⚠️  No procurement records found for tender: Licitación Abreviada 08/2002, buyer: 4-8
🔍 Found 27 potential bidders for tender: Licitación Abreviada 11/2002
✅ Match #60: Updated 1 records
   Tender: Licitación Abreviada 11/2002
   Buyer: 4-26
   Supplier: R/210000780014
   Quantity: 200.0
   Date: 2002-05-24
🔍 Found 1 potential bidders for tender: Licitación Abreviada 30/2002
✅ Match #61: Updated 1 records
   Tender: Licitación Abreviada 30/2002
   Buyer: 4-4
   Supplier: R/211801770015
   Quantity: 21.0
   Date: 2002-05-29
🔍 Found 1 potential bidders for tender: Licitación Abreviada 21/2002
✅ Match #62: Updated 1 records
   Tender: Licitación Abreviada 21/2002
   Buyer: 4-4
   Supplier: R/214341860010
   Quantity: 86.0
   Date: 2002-05-23
🔍 Found 2 potential bidders for tender: Licitación Abreviada 9/2002
✅ Match #63: Updated 1 records
   Tender: Licitación Abreviada 9/2002
   Buyer: 4-13
   Supplier: R/210000400017
   Quantity: 3918.0
   Date: 2002-05-15
⚠️  No procurement records found for tender: Licitación Abreviada 04/2002, buyer: 6-1
🔍 Found 6 potential bidders for tender: Licitación Abreviada 01/2002
✅ Match #64: Updated 1 records
   Tender: Licitación Abreviada 01/2002
   Buyer: 4-28
   Supplier: R/210003280012
   Quantity: 300.0
   Date: 2002-04-26
🔍 Found 2 potential bidders for tender: Licitación Abreviada 26/2002
✅ Match #65: Updated 1 records
   Tender: Licitación Abreviada 26/2002
   Buyer: 4-4
   Supplier: R/210206210019
   Quantity: 254.0
   Date: 2002-05-23
🔍 Found 3 potential bidders for tender: Licitación Abreviada 23/2002
✅ Match #66: Updated 1 records
   Tender: Licitación Abreviada 23/2002
   Buyer: 4-4
   Supplier: R/210268110018
   Quantity: 1500.0
   Date: 2002-05-23
🔍 Found 9 potential bidders for tender: Licitación Abreviada 01/2002
✅ Match #67: Updated 1 records
   Tender: Licitación Abreviada 01/2002
   Buyer: 6-1
   Supplier: R/210000700010
   Quantity: 624.0
   Date: 2002-05-23
🔍 Found 1 potential bidders for tender: Licitación Abreviada 13/2002
✅ Match #68: Updated 1 records
   Tender: Licitación Abreviada 13/2002
   Buyer: 10-3
   Supplier: R/160002920018
   Quantity: 1250.0
   Date: 2002-11-28
🔍 Found 1 potential bidders for tender: Licitación Abreviada 17/2002
✅ Match #69: Updated 1 records
   Tender: Licitación Abreviada 17/2002
   Buyer: 2-1
   Supplier: R/211322010010
   Quantity: 7.0
   Date: 2002-06-11
🔍 Found 1 potential bidders for tender: Licitación Abreviada 32/2001
✅ Match #70: Updated 1 records
   Tender: Licitación Abreviada 32/2001
   Buyer: 2-1
   Supplier: R/210156030012
   Quantity: 1.0
   Date: 2002-04-16
🔍 Found 1 potential bidders for tender: Licitación Abreviada 10/2002
✅ Match #71: Updated 1 records
   Tender: Licitación Abreviada 10/2002
   Buyer: 4-13
   Supplier: R/100010300011
   Quantity: 39.0
   Date: 2002-04-16
🔍 Found 1 potential bidders for tender: Licitación Abreviada 02/2002
✅ Match #72: Updated 1 records
   Tender: Licitación Abreviada 02/2002
   Buyer: 4-1
   Supplier: R/211427110015
   Quantity: 1.0
   Date: 2002-04-26
🔍 Found 1 potential bidders for tender: Licitación Abreviada 28/2002
✅ Match #73: Updated 1 records
   Tender: Licitación Abreviada 28/2002
   Buyer: 4-4
   Supplier: R/213394980012
   Quantity: 276.0
   Date: 2002-06-14
⚠️  No procurement records found for tender: Licitación Abreviada 04/2002, buyer: 4-2
🔍 Found 1 potential bidders for tender: Licitación Abreviada 17/2002
✅ Match #74: Updated 1 records
   Tender: Licitación Abreviada 17/2002
   Buyer: 3-18
   Supplier: R/210267400012
   Quantity: 1.0
   Date: 2002-05-30
🔍 Found 3 potential bidders for tender: Licitación Abreviada 13/2002
✅ Match #75: Updated 1 records
   Tender: Licitación Abreviada 13/2002
   Buyer: 4-23
   Supplier: R/160122020014
   Quantity: 25500.0
   Date: 2002-05-23
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2002
✅ Match #76: Updated 1 records
   Tender: Licitación Abreviada 1/2002
   Buyer: 4-1
   Supplier: R/213036420012
   Quantity: 200.0
   Date: 2002-04-30
🔍 Found 1 potential bidders for tender: Licitación Abreviada 19/2002
✅ Match #77: Updated 1 records
   Tender: Licitación Abreviada 19/2002
   Buyer: 3-18
   Supplier: R/214402430010
   Quantity: 1.0
   Date: 2002-05-30
🔍 Found 8 potential bidders for tender: Licitación Abreviada 002/2002
✅ Match #78: Updated 1 records
   Tender: Licitación Abreviada 002/2002
   Buyer: 3-3
   Supplier: R/210203560019
   Quantity: 980.0
   Date: 2002-06-03
⚠️  No procurement records found for tender: Licitación Abreviada 01/2002, buyer: 14-1
🔍 Found 3 potential bidders for tender: Licitación Abreviada 15/2002

Processing 2003 tenders:   0%|          | 0/8703 [00:00<?, ?it/s]

⚠️  No procurement records found for tender: Licitación Abreviada 7/2002, buyer: 6-1
⚠️  No procurement records found for tender: Compra Directa 21bis/2003, buyer: 14-1
🔍 Found 1 potential bidders for tender: Compra Directa 10/2003
✅ Match #317: Updated 1 records
   Tender: Compra Directa 10/2003
   Buyer: 4-31
   Supplier: R/213568730016
   Quantity: 161.0
   Date: 2003-01-09
🔍 Found 1 potential bidders for tender: Compra Directa 30055/2003
✅ Match #318: Updated 1 records
   Tender: Compra Directa 30055/2003
   Buyer: 14-3
   Supplier: R/210457190019
   Quantity: 10.0
   Date: 2003-01-02
⚠️  No procurement records found for tender: Licitación Abreviada 1/2002, buyer: 14-4
🔍 Found 2 potential bidders for tender: Licitación Abreviada 8/2002
✅ Match #319: Updated 1 records
   Tender: Licitación Abreviada 8/2002
   Buyer: 4-31
   Supplier: R/213214690010
   Quantity: 51040.0
   Date: 2003-03-05
⚠️  No procurement records found for tender: Licitación Abreviada 100/2003, buyer: 9-1
🔍 Found 7 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #320: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-26
   Supplier: R/210035000015
   Quantity: 50.0
   Date: 2003-01-29
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1157/2002
✅ Match #321: Updated 1 records
   Tender: Licitación Abreviada 1157/2002
   Buyer: 5-8
   Supplier: R/213951980011
   Quantity: 230.0
   Date: 2003-01-09
🔍 Found 1 potential bidders for tender: Licitación Abreviada 941/2002
✅ Match #322: Updated 1 records
   Tender: Licitación Abreviada 941/2002
   Buyer: 5-8
   Supplier: R/212209830014
   Quantity: 40.0
   Date: 2003-01-20
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1103/2002
✅ Match #323: Updated 1 records
   Tender: Licitación Abreviada 1103/2002
   Buyer: 5-8
   Supplier: R/213887110015
   Quantity: 12.0
   Date: 2003-01-09
🔍 Found 1 potential bidders for tender: Licitación Abreviada 20701/2003
✅ Match #324: Updated 1 records
   Tender: Licitación Abreviada 20701/2003
   Buyer: 5-13
   Supplier: R/212363630011
   Quantity: 1.0
   Date: 2003-06-20
⚠️  No procurement records found for tender: Licitación Abreviada 102/2003, buyer: 9-1
🔍 Found 6 potential bidders for tender: Licitación Abreviada 38/2002
✅ Match #325: Updated 1 records
   Tender: Licitación Abreviada 38/2002
   Buyer: 5-5
   Supplier: R/210000100013
   Quantity: 60.0
   Date: 2003-02-06
🔍 Found 2 potential bidders for tender: Licitación Abreviada 5/2003
✅ Match #326: Updated 1 records
   Tender: Licitación Abreviada 5/2003
   Buyer: 4-26
   Supplier: R/213320090013
   Quantity: 11570.0
   Date: 2003-02-06
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1170/2002
✅ Match #327: Updated 1 records
   Tender: Licitación Abreviada 1170/2002
   Buyer: 5-8
   Supplier: R/210252190017
   Quantity: 12.0
   Date: 2003-01-09
🔍 Found 3 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #328: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-7
   Supplier: R/030094340015
   Quantity: 5950.0
   Date: 2003-02-04
🔍 Found 1 potential bidders for tender: Licitación Pública 5/2002
✅ Match #329: Updated 1 records
   Tender: Licitación Pública 5/2002
   Buyer: 4-26
   Supplier: R/170052730015
   Quantity: 684000.0
   Date: 2003-01-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #330: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-11
   Supplier: R/070117450015
   Quantity: 12.0
   Date: 2003-02-05
🔍 Found 1 potential bidders for tender: Licitación Abreviada 984/2002
✅ Match #331: Updated 1 records
   Tender: Licitación Abreviada 984/2002
   Buyer: 5-8
   Supplier: R/213456180014
   Quantity: 12.0
   Date: 2003-01-09
🔍 Found 3 potential bidders for tender: Licitación Abreviada 7/2003
✅ Match #332: Updated 1 records
   Tender: Licitación Abreviada 7/2003
   Buyer: 4-20
   Supplier: R/180055170018
   Quantity: 25210.0
   Date: 2003-02-05
🔍 Found 1 potential bidders for tender: Compra Directa 80002/2003
✅ Match #333: Updated 1 records
   Tender: Compra Directa 80002/2003
   Buyer: 8-8
   Supplier: R/212396340012
   Quantity: 8.0
   Date: 2003-01-23
🔍 Found 4 potential bidders for tender: Licitación Abreviada 25/2003
✅ Match #334: Updated 1 records
   Tender: Licitación Abreviada 25/2003
   Buyer: 4-6
   Supplier: R/210849440017
   Quantity: 306.0
   Date: 2003-01-21
🔍 Found 1 potential bidders for tender: Licitación Abreviada 25/2003
🔍 Found 1 potential bidders for tender: Licitación Pública 4/2002
✅ Match #335: Updated 1 records
   Tender: Licitación Pública 4/2002
   Buyer: 4-26
   Supplier: R/212531360012
   Quantity: 432000.0
   Date: 2003-01-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 05/2002
✅ Match #336: Updated 1 records
   Tender: Licitación Abreviada 05/2002
   Buyer: 2-7
   Supplier: R/213330870011
   Quantity: 1.0
   Date: 2003-01-22
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #337: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 5-5
   Supplier: R/210154140015
   Quantity: 195000.0
   Date: 2003-02-10
🔍 Found 3 potential bidders for tender: Licitación Abreviada 24/2003
✅ Match #338: Updated 1 records
   Tender: Licitación Abreviada 24/2003
   Buyer: 4-6
   Supplier: R/020058040018
   Quantity: 3120.0
   Date: 2003-01-23
⚠️  No procurement records found for tender: Licitación Abreviada 20bis/2002, buyer: 7-1
🔍 Found 4 potential bidders for tender: Licitación Abreviada 6/2003
✅ Match #339: Updated 1 records
   Tender: Licitación Abreviada 6/2003
   Buyer: 4-26
   Supplier: R/210000700010
   Quantity: 12834.0
   Date: 2003-02-11
🔍 Found 1 potential bidders for tender: Licitación Pública 2/2003
✅ Match #340: Updated 1 records
   Tender: Licitación Pública 2/2003
   Buyer: 4-4
   Supplier: R/212477120012
   Quantity: 16425.0
   Date: 2003-02-28
🔍 Found 1 potential bidders for tender: Licitación Abreviada 985/2003
✅ Match #341: Updated 1 records
   Tender: Licitación Abreviada 985/2003
   Buyer: 5-8
   Supplier: R/214076570013
   Quantity: 12.0
   Date: 2003-01-20
🔍 Found 2 potential bidders for tender: Licitación Abreviada 1125/2002
✅ Match #342: Updated 1 records
   Tender: Licitación Abreviada 1125/2002
   Buyer: 5-8
   Supplier: R/213444800012
   Quantity: 12.0
   Date: 2003-01-20
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1031/2002
✅ Match #343: Updated 1 records
   Tender: Licitación Abreviada 1031/2002
   Buyer: 5-8
   Supplier: R/212292340016
   Quantity: 12.0
   Date: 2003-01-20
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #344: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-11
   Supplier: R/213846870015
   Quantity: 12.0
   Date: 2003-02-05
🔍 Found 1 potential bidders for tender: Licitación Abreviada 10bis/2002
🔍 Found 2 potential bidders for tender: Licitación Abreviada 71/2003
✅ Match #345: Updated 1 records
   Tender: Licitación Abreviada 71/2003
   Buyer: 4-4
   Supplier: R/210276180011
   Quantity: 64500.0
   Date: 2003-01-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 23/2003
✅ Match #346: Updated 1 records
   Tender: Licitación Abreviada 23/2003
   Buyer: 4-6
   Supplier: R/210276180011
   Quantity: 1800.0
   Date: 2003-01-15
⚠️  No procurement records found for tender: Licitación Abreviada 6/2003, buyer: 4-20
🔍 Found 5 potential bidders for tender: Licitación Abreviada 4/2003
✅ Match #347: Updated 1 records
   Tender: Licitación Abreviada 4/2003
   Buyer: 4-26
   Supplier: R/210060480017
   Quantity: 480.0
   Date: 2003-02-03
🔍 Found 3 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #348: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-4
   Supplier: R/211573390019
   Quantity: 710.0
   Date: 2003-01-28
🔍 Found 3 potential bidders for tender: Licitación Abreviada 8/2003
✅ Match #349: Updated 1 records
   Tender: Licitación Abreviada 8/2003
   Buyer: 4-20
   Supplier: R/180005470018
   Quantity: 36.0
   Date: 2003-02-20
⚠️  No procurement records found for tender: Licitación Abreviada 101/2003, buyer: 9-1
🔍 Found 1 potential bidders for tender: Licitación Abreviada 5/2002
⚠️  No procurement records found for tender: Licitación Abreviada 4/2003, buyer: 4-13
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #350: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-7
   Supplier: R/030117930018
   Quantity: 50.0
   Date: 2003-02-10
🔍 Found 2 potential bidders for tender: Licitación Pública 21/2003
✅ Match #351: Updated 1 records
   Tender: Licitación Pública 21/2003
   Buyer: 3-4
   Supplier: R/170052730015
   Quantity: 10686.0
   Date: 2003-02-26
🔍 Found 2 potential bidders for tender: Licitación Pública 979/2002
🔍 Found 3 potential bidders for tender: Licitación Abreviada 7/2003
✅ Match #352: Updated 1 records
   Tender: Licitación Abreviada 7/2003
   Buyer: 4-13
   Supplier: R/100101000010
   Quantity: 3100.0
   Date: 2003-01-07
🔍 Found 1 potential bidders for tender: Licitación Abreviada 5/2003
✅ Match #353: Updated 1 records
   Tender: Licitación Abreviada 5/2003
   Buyer: 4-13
   Supplier: R/211523510010
   Quantity: 31950.0
   Date: 2003-01-15
⚠️  No procurement records found for tender: Licitación Abreviada 103/2003, buyer: 9-1
🔍 Found 1 potential bidders for tender: Licitación Pública 22/2003
✅ Match #354: Updated 1 records
   Tender: Licitación Pública 22/2003
   Buyer: 3-4
   Supplier: R/210276180011
   Quantity: 232341.0
   Date: 2003-03-06
🔍 Found 1 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #355: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-13
   Supplier: R/100010300011
   Quantity: 440.0
   Date: 2003-01-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3/2002
🔍 Found 4 potential bidders for tender: Licitación Abreviada 8/2003
✅ Match #356: Updated 1 records
   Tender: Licitación Abreviada 8/2003
   Buyer: 4-13
   Supplier: R/210002810018
   Quantity: 23430.0
   Date: 2003-01-15
🔍 Found 1 potential bidders for tender: Licitación Abreviada 108/2002
✅ Match #357: Updated 1 records
   Tender: Licitación Abreviada 108/2002
   Buyer: 50-1
   Supplier: R/210194590011
   Quantity: 1.0
   Date: 2003-01-29
🔍 Found 1 potential bidders for tender: Licitación Abreviada 6/2003
✅ Match #358: Updated 1 records
   Tender: Licitación Abreviada 6/2003
   Buyer: 4-13
   Supplier: R/100101000010
   Quantity: 7200.0
   Date: 2003-01-27
🔍 Found 5 potential bidders for tender: Licitación Abreviada 21/2002
✅ Match #359: Updated 1 records
   Tender: Licitación Abreviada 21/2002
   Buyer: 10-4
   Supplier: R/210671250019
   Quantity: 200.0
   Date: 2003-01-07
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #360: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-13
   Supplier: R/020058040018
   Quantity: 21000.0
   Date: 2003-01-15
⚠️  No procurement records found for tender: Licitación Abreviada 17/2002, buyer: 10-4
⚠️  No procurement records found for tender: Licitación Abreviada 1/2003, buyer: 9-1
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #361: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 10-4
   Supplier: R/212154850019
   Quantity: 12.0
   Date: 2003-04-28
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3/2002
🔍 Found 3 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #362: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-26
   Supplier: R/210307720012
   Quantity: 1500.0
   Date: 2003-01-30
🔍 Found 1 potential bidders for tender: Licitación Abreviada 950/2002
✅ Match #363: Updated 1 records
   Tender: Licitación Abreviada 950/2002
   Buyer: 5-8
   Supplier: R/214048220011
   Quantity: 12.0
   Date: 2003-01-20
🔍 Found 3 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #364: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 4-7
   Supplier: R/212363900019
   Quantity: 47.0
   Date: 2003-02-19
🔍 Found 1 potential bidders for tender: Licitación Abreviada 3/2002
✅ Match #365: Updated 1 records
   Tender: Licitación Abreviada 3/2002
   Buyer: 10-1
   Supplier: R/212566860011
   Quantity: 12.0
   Date: 2003-01-07
🔍 Found 2 potential bidders for tender: Licitación Abreviada 15/2003
✅ Match #366: Updated 1 records
   Tender: Licitación Abreviada 15/2003
   Buyer: 3-4
   Supplier: R/210002260018
   Quantity: 12.0
   Date: 2003-02-11
🔍 Found 2 potential bidders for tender: Licitación Abreviada 44441/2003
✅ Match #367: Updated 1 records
   Tender: Licitación Abreviada 44441/2003
   Buyer: 5-5
   Supplier: R/210002260018
   Quantity: 4.0
   Date: 2003-01-16
🔍 Found 2 potential bidders for tender: Licitación Abreviada 08/2002
✅ Match #368: Updated 1 records
   Tender: Licitación Abreviada 08/2002
   Buyer: 6-1
   Supplier: R/211065710019
   Quantity: 1.0
   Date: 2003-01-31
🔍 Found 1 potential bidders for tender: Compra Directa 40021/2003
✅ Match #369: Updated 1 records
   Tender: Compra Directa 40021/2003
   Buyer: 8-4
   Supplier: R/212374170017
   Quantity: 9.0
   Date: 2003-02-17
🔍 Found 4 potential bidders for tender: Licitación Abreviada 48/2003
✅ Match #370: Updated 1 records
   Tender: Licitación Abreviada 48/2003
   Buyer: 5-5
   Supplier: R/210000700010
   Quantity: 18515.0
   Date: 2003-03-24
🔍 Found 3 potential bidders for tender: Licitación Abreviada 1/2002
🔍 Found 3 potential bidders for tender: Licitación Abreviada 16/2003
✅ Match #371: Updated 1 records
   Tender: Licitación Abreviada 16/2003
   Buyer: 3-4
   Supplier: R/210308100018
   Quantity: 12.0
   Date: 2003-02-13
🔍 Found 1 potential bidders for tender: Licitación Abreviada 2/2002
🔍 Found 2 potential bidders for tender: Licitación Abreviada 33331/2003
✅ Match #372: Updated 1 records
   Tender: Licitación Abreviada 33331/2003
   Buyer: 5-5
   Supplier: R/212758410014
   Quantity: 1.0
   Date: 2003-01-31
🔍 Found 4 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #373: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 5-5
   Supplier: R/210000700010
   Quantity: 45300.0
   Date: 2003-04-21
🔍 Found 8 potential bidders for tender: Licitación Abreviada 1/2003
✅ Match #374: Updated 1 records
   Tender: Licitación Abreviada 1/2003
   Buyer: 4-24
   Supplier: R/210035000015
   Quantity: 200.0
   Date: 2003-03-18
🔍 Found 2 potential bidders for tender: Licitación Pública 8147/2003
✅ Match #375: Updated 1 records
   Tender: Licitación Pública 8147/2003
   Buyer: 4-1
   Supplier: R/211397780018
   Quantity: 150.0
   Date: 2003-05-09
🔍 Found 5 potential bidders for tender: Licitación Abreviada 36/2003
✅ Match #376: Updated 1 records
   Tender: Licitación Abreviada 36/2003
   Buyer: 4-6
   Supplier: R/020000340019
   Quantity: 974.0
   Date: 2003-01-31
🔍 Found 1 potential bidders for tender: Licitación Abreviada 4802/2003
✅ Match #377: Updated 1 records
   Tender: Licitación Abreviada 4802/2003
   Buyer: 64-1
   Supplier: R/213946060015
   Quantity: 1.0
   Date: 2003-04-22
🔍 Found 3 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #378: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-4
   Supplier: R/211523510010
   Quantity: 3462.0
   Date: 2003-02-26
🔍 Found 1 potential bidders for tender: Licitación Abreviada 5/2002
✅ Match #379: Updated 1 records
   Tender: Licitación Abreviada 5/2002
   Buyer: 11-15
   Supplier: R/160149970013
   Quantity: 12.0
   Date: 2003-01-17
🔍 Found 4 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #380: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 4-28
   Supplier: R/210007470010
   Quantity: 1100.0
   Date: 2003-02-11
🔍 Found 4 potential bidders for tender: Licitación Abreviada 2/2003
✅ Match #381: Updated 1 records
   Tender: Licitación Abreviada 2/2003
   Buyer: 4-28
   Supplier: R/210000700010
   Quantity: 343.0
   Date: 2003-02-10
🔍 Found 1 potential bidders for tender: Licitación Abreviada 8/2003
✅ Match #382: Updated 1 records
   Tender: Licitación Abreviada 8/2003
   Buyer: 4-26
   Supplier: R/210222730013
   Quantity: 2000.0
   Date: 2003-03-17
🔍 Found 1 potential bidders for tender: Licitación Abreviada 20669/2003
✅ Match #383: Updated 1 records
   Tender: Licitación Abreviada 20669/2003
   Buyer: 5-13
   Supplier: R/211485270011
   Quantity: 2000.0
   Date: 2003-02-19
⚠️  No procurement records found for tender: Licitación Abreviada 01/2003, buyer: 53-1
🔍 Found 2 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #384: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 4-4
   Supplier: R/020049970016
   Quantity: 10000.0
   Date: 2003-03-06
🔍 Found 1 potential bidders for tender: Licitación Abreviada 9/2002
🔍 Found 5 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #385: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 4-9
   Supplier: R/050028920011
   Quantity: 415.0
   Date: 2003-02-24
🔍 Found 1 potential bidders for tender: Licitación Pública 44/2003
✅ Match #386: Updated 1 records
   Tender: Licitación Pública 44/2003
   Buyer: 3-4
   Supplier: R/210000750018
   Quantity: 387400.0
   Date: 2003-03-10
🔍 Found 1 potential bidders for tender: Licitación Abreviada 108/2003
🔍 Found 1 potential bidders for tender: Compra Directa 54/2003
✅ Match #387: Updated 1 records
   Tender: Compra Directa 54/2003
   Buyer: 11-1
   Supplier: R/213094250019
   Quantity: 7.0
   Date: 2003-03-06
🔍 Found 6 potential bidders for tender: Licitación Abreviada 3/2003
✅ Match #388: Updated 1 records
   Tender: Licitación Abreviada 3/2003
   Buyer: 4-31
   Supplier: R/210000100013
   Quantity: 34.0
   Date: 2003-03-28
🔍 Found 8 potential bidders for tender: Licitación Abreviada 40/2003
✅ Match #389: Updated 1 records
   Tender: Licitación Abreviada 40/2003
   Buyer: 4-6
   Supplier: R/020069450018
   Quantity: 3128.0
   Date: 2003-02-25
🔍 Found 2 potential bidders for tender: Licitación Abreviada 7/2003
✅ Match #390: Updated 1 records
   Tender: Licitación Abreviada 7/2003
   Buyer: 4-4
   Supplier: R/210000400017
   Quantity: 2400.0
   Date: 2003-04-08
⚠️  No procurement records found for tender: Licitación Abreviada 19/2002, buyer: 53-1
🔍 Found 2 potential bidders for tender: Licitación Abreviada 5/2003
✅ Match #391: Updated 1 records
   Tender: Licitación Abreviada 5/2003
   Buyer: 4-4
   Supplier: R/211573390019
   Quantity: 3821.0
   Date: 2003-03-21
🔍 Found 1 potential bidders for tender: Licitación Abreviada 50/2003
✅ Match #392: Updated 1 records
   Tender: Licitación Abreviada 50/2003
   Buyer: 3-4
   Supplier: R/210001200011
   Quantity: 25000.0
   Date: 2003-03-06
🔍 Found 1 potential bidders for tender: Licitación Pública 4/2002
✅ Match #393: Updated 1 records
   Tender: Licitación Pública 4/2002
   Buyer: 4-31
   Supplier: T/04031
   Quantity: 15000.0
   Date: 2003-03-24
🔍 Found 3 potential bidders for tender: Licitación Abreviada 35/2003
✅ Match #394: Updated 1 records
   Tender: Licitación Abreviada 35/2003
   Buyer: 4-6
   Supplier: R/020001690013
   Quantity: 353.0
   Date: 2003-01-31
🔍 Found 2 potential bidders for tender: Licitación Abreviada 6/2003
✅ Match #395: Updated 1 records
   Tender: Licitación Abreviada 6/2003
   Buyer: 4-4
   Supplier: R/210000400017
   Quantity: 200.0
   Date: 2003-03-26
🔍 Found 3 potential bidders for tender: Licitación Abreviada 38/2003
✅ Match #396: Updated 1 records
   Tender: Licitación Abreviada 38/2003
   Buyer: 4-6
   Supplier: R/020112500018
   Quantity: 18700.0
   Date: 2003-02-13
🔍 Found 1 potential bidders for tender: Compra Directa 257/2003
✅ Match #397: Updated 1 records
   Tender: Compra Directa 257/2003
   Buyer: 13-6
   Supplier: R/211105230012
   Quantity: 1.0
   Date: 2003-07-24
🔍 Found 8 potential bidders for tender: Licitación Pública 34/2003
✅ Match #398: Updated 1 records
   Tender: Licitación Pública 34/2003
   Buyer: 3-4

In [53]:
uruguay_procurement_data_expanded[uruguay_procurement_data_expanded['quantity'].notnull()]

,tender_id,tender_title,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,tender_contractsignaturedate,lot_productCode,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_nuts,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_nuts,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_publications_lastcallfort,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,currency,tender_proceduretype,tender_biddeadline,tender_awarddecisiondate,tender_publications_firstcallfor,lot_localProductCode,lot_localProductCode_type,tender_integrity_winner_ca_share,is_exploded_row,tender_biddeadline_corrected,tender_awarddecisiondate_corrected,tender_publications_firstcallfor_corrected,quantity
1780376,UY_b6fea881320e68ed54ae350f77a0124297bccba5_1,Licitación Abreviada 4/2002,Licitación Abreviada,NaN,1,NaN,0,NaN,NaN,R/211267550012,1,4-4,7ebdf69d-cc8c-4fbf-93ed-501b7a6098cb,JEFATURA DE POLICÍA DE MONTEVIDEO,NaN,NaN,NaN,NaN,R/211267550012,aadb8594-8e34-435c-b41f-d313834d5fc3,PROVEEDORES INDUSTRIALES S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2002-02-20,NaN,2002-02-20,2002,0.0,NaN,50.0,100,100.0,NaN,NaN,OPEN,2012-02-09,2012-02-21,2012-02-21,"0,",CPV2008,99.992287,True,2002-02-08,2002-02-20,2002-02-20,2800.0

In [33]:
uruguay_procurement_data_expanded['tender_awarddecisiondate_corrected'].dtype

dtype('<M8[ns]')

Based on previous analysis, some columns are out by 10 years according to the real data. Going to apply a correction

It appears the `tender_biddeadline` corresponds to the `tenderPeriod` endDate from the JSON data, while the date in `tender_publications_lastcallfort` would relate to the startDate of the tender period. The dates for `tender_biddeadline` are off by 10 years. Going to check that with a Series

In [34]:
uruguay_procurement_data_expanded[(uruguay_procurement_data_expanded['tender_title'] == 'Licitación Abreviada 4/2002') & (uruguay_procurement_data_expanded['buyer_id'] == '4-4')].reset_index(drop = True)

,tender_id,tender_title,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,tender_contractsignaturedate,lot_productCode,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_nuts,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_nuts,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_publications_lastcallfort,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,currency,tender_proceduretype,tender_biddeadline,tender_awarddecisiondate,tender_publications_firstcallfor,lot_localProductCode,lot_localProductCode_type,tender_integrity_winner_ca_share,is_exploded_row,tender_biddeadline_corrected,tender_awarddecisiondate_corrected,tender_publications_firstcallfor_corrected,quantity
0,UY_b6fea881320e68ed54ae350f77a0124297bccba5_1,Licitación Abreviada 4/2002,Licitación Abreviada,NaN,1,NaN,0,NaN,NaN,R/211267550012,1,4-4,7ebdf69d-cc8c-4fbf-93ed-501b7a6098cb,JEFATURA DE POLICÍA DE MONTEVIDEO,NaN,NaN,NaN,NaN,R/211267550012,aadb8594-8e34-435c-b41f-d313834d5fc3,PROVEEDORES INDUSTRIALES S.A.,NaN,NaN,NaN,t,https://catalogodatos.gub.uy/dataset/acce-dato...,NaN,2002-02-20,NaN,2002-02-20,2002,0.0,NaN,50.0,100,100.0,NaN,NaN,OPEN,2012-02-09,2012-02-21,2012-02-21,"0,",CPV2008,99.992287,True,2002-02-08,2002-02-20,2002-02-20,2800.0

## Searching the Paraguayan Catalog
The catalog file can be found <a href="https://www.contrataciones.gov.py/datos/catalogo">here</a> under the 2025 n5 catalog
<br>From previous inspection of the dataset, we only need to take the n4 codes. Everything else returns an error when searching the Paraguayan tender dataset

In [35]:
paraguay_procurement_cols = ['id', 
                            'n4_codigo', 
                            'n4_nombre', 
                            'nombre',
                            'createdDate',
                            'date']
paraguay_public_procurement_catalog = pd.read_csv(paraguayan_procurement_catalog_file_path)
paraguay_public_procurement_num_rows = paraguay_public_procurement_catalog.shape[0]
paraguay_public_procurement_num_cols = paraguay_public_procurement_catalog.shape[1]

print(f'{paraguay_public_procurement_num_rows} rows x {paraguay_public_procurement_num_cols} columns')
paraguay_public_procurement_catalog.head()

307 rows x 12 columns

,id,n1_codigo,n1_nombre,n2_codigo,n2_nombre,n3_codigo,n3_nombre,n4_codigo,n4_nombre,nombre,createdDate,date
0,14111510-9997,14000000,Materiales y Productos de Papel,14110000,Productos de papel,14111500,Papel de imprenta y papel de escribir,14111510,Papeles especiales,Papel para encuadernación,2025-06-12T14:30:08-04:00,2025-10-02T21:46:46-04:00
1,15101506-9996,15000000,"Combustibles Aditivos para combustibles, Lubri...",15100000,Combustibles,15101500,"Petroleo, Destilados y otros tipos de combusti...",15101506,Gasolina,Gasolina sin plomo Ron 88,2025-04-15T11:30:58-04:00,2025-10-02T21:46:46-04:00
2,30141508-9999,30000000,Componentes y Suministros de Fabricacion Estru...,30140000,Aislamiento,30141500,Aislamiento termico,30141508,Aislamiento de mica,Cinta de terminación sin adhesivo,2025-06-02T16:08:44-04:00,2025-10-02T21:46:48-04:00
3,31211803-9988,31000000,Componentes y Suministros de Fabricacion,31210000,Pinturas y tapa poros y acabados,31211800,Disolventes y diluyentes para pinturas,31211803,Disolventes y Diluyentes para pinturas y barnices,Thinner de 18 lts,2025-06-27T08:54:52-04:00,2025-10-02T21:46:49-04:00
4,39111503-9998,39000000,Suministros componentes y accesorios electrico...,39110000,"Iluminacion, artefactos y accesorios",39111500,Iluminacion de interiores y artefactos,39111503,Dispositivos de pared,Panel Led para adosar de 12 W.,2025-05-30T14:47:02-04:00,2025-10-02T21:46:49-04:00

Running the Translations

In [36]:
paraguay_drop_cols = ['id', 'n4_codigo', 'createdDate', 'date']

paraguay_public_procurement_items_translated = translate_country_procurement_catalog(
    paraguay_public_procurement_catalog,
    paraguayan_procurement_catalog_file_name,
    'csv',
    paraguay_drop_cols)

File Found. Loading Dataset

In [37]:
paraguay_public_procurement_catalog[paraguay_public_procurement_catalog['id'].str.contains('82121701')]

,id,n1_codigo,n1_nombre,n2_codigo,n2_nombre,n3_codigo,n3_nombre,n4_codigo,n4_nombre,nombre,createdDate,date
304,82121701-9999,82000000,"Servicios Editoriales de Diseño, Graficos y d...",82120000,Servicios de reproduccion y otros,82121700,Fotocopiado,82121701,Servicios de copias en blanco y negro o de cotejo,Servicios de copias en blanco y negro,2025-08-14T15:22:36-04:00,2025-10-02T21:47:02-04:00

In [38]:
paraguay_public_procurement_items_translated['n4_codigo'] = paraguay_public_procurement_items_translated['n4_codigo'].astype(str)

## Finding Where the Quantity Numbers Exist in the Main National Datasets (From the Paper)

It appears that any dataset with "contract" in the url has the quantity key in it. Creating a list of the records with a link inside the contract column and save it to json to reduce future memory issues.

### Paraguay

In [39]:
paraguay_tender_contract_column = 'tender_publications_lastcontract'
paraguay_tender_contracts_list = []

paraguay_tender_publications_list = paraguay_procurement_data[paraguay_tender_contract_column].to_list()

for tender in tqdm(paraguay_tender_publications_list, desc='Processing Tender Contracts'):
    if 'contract' in tender:
        paraguay_tender_contracts_list.append(tender)

# Enhanced tracking with rate limit management
request_tracking = {
    'successful': {},
    'failed': {},
    'rate_limited': [],
    'total_attempted': 0,
    'start_time': time.time(),
    'last_request_time': 0
}

# Execute with better rate limiting
if 'paraguay_tender_contracts_rate_limited.json' not in os.listdir(generated_data_folder):
    print("🔄 Starting rate-limited API requests...")
    results = await get_tender_json_with_rate_limiting()
    
    # Save results with better tracking
    request_tracking['end_time'] = time.time()
    request_tracking['duration_seconds'] = request_tracking['end_time'] - request_tracking['start_time']
    request_tracking['success_rate'] = len(request_tracking['successful']) / len(paraguay_tender_contracts_list) if paraguay_tender_contracts_list else 0
    request_tracking['total_urls'] = len(paraguay_tender_contracts_list)
    
    # Save tracking data
    # Tracking file shows the results of the successful URLs, as well as the number of failed items and their error codes
    tracking_file_path = os.path.join(generated_data_folder, paraguay_tender_request_metrics_file)
    # This file contains the contracts list
    results_file_path = os.path.join(generated_data_folder, paraguay_rate_limited_data_file)
    # This keeps the URL with the associated tender
    mapping_file_path = os.path.join(generated_data_folder, paraguay_url_mapping_data_file)
    
    # Create URL mapping maintaining original order
    url_to_response_mapping = {}
    successful_responses = []
    
    for i, (url, result) in enumerate(zip(paraguay_tender_contracts_list, results)):
        if result is not None:
            url_to_response_mapping[url] = result
            successful_responses.append(result)
    
    # Save all files
    with open(tracking_file_path, 'w') as f:
        tracking_serializable = {
            'successful_urls': list(request_tracking['successful'].keys()),
            'failed_urls': list(request_tracking['failed'].keys()),
            'rate_limited_urls': request_tracking['rate_limited'],
            'successful_count': len(request_tracking['successful']),
            'failed_count': len(request_tracking['failed']),
            'rate_limited_count': len(request_tracking['rate_limited']),
            'total_attempted': request_tracking['total_attempted'],
            'success_rate': request_tracking['success_rate'],
            'duration_seconds': request_tracking['duration_seconds'],
            'total_urls': request_tracking['total_urls'],
            'detailed_failures': request_tracking['failed']
        }
        json.dump(tracking_serializable, f, indent=2)
    
    with open(results_file_path, 'w') as f:
        json.dump(successful_responses, f, indent=2)
    
    with open(mapping_file_path, 'w') as f:
        json.dump(url_to_response_mapping, f, indent=2)
    
    print(f"\n🎉 FINAL RESULTS")
    print(f"📊 Total URLs: {request_tracking['total_urls']}")
    print(f"✅ Successful: {len(request_tracking['successful'])}")
    print(f"❌ Failed: {len(request_tracking['failed'])}")
    print(f"⚠️  Rate Limited: {len(request_tracking['rate_limited'])}")
    print(f"📈 Success Rate: {request_tracking['success_rate']:.2%}")
    print(f"⏱️  Duration: {request_tracking['duration_seconds']:.1f} seconds")

else:
    print("📁 Loading existing rate-limited data...")
    with open(os.path.join(generated_data_folder, paraguay_rate_limited_data_file), 'r') as f:
        results = json.load(f)
    with open(os.path.join(generated_data_folder, paraguay_url_mapping_data_file), 'r') as f:
        url_to_response_mapping = json.load(f)

print(f'📋 Final results length: {len(results) if "results" in locals() else "No results loaded"}')
print(f'🔗 URL mappings: {len(url_to_response_mapping) if "url_to_response_mapping" in locals() else "No mappings loaded"}')

Processing Tender Contracts:   0%|          | 0/166010 [00:00<?, ?it/s]

📁 Loading existing rate-limited data...
📋 Final results length: 87701
🔗 URL mappings: 54583

In [ ]:
json.loads(results[0])['releases'][0]['contracts'][0]['items'][0]['quantity']

Checking for the quantities of each item

In [ ]:
file_path = os.path.join(generated_data_folder, paraguay_rate_limited_data_file)

non_none_results = []

with open(file_path, 'r') as f:
    paraguay_tender_items = json.load(f)
    
    print(f'Loaded {len(paraguay_tender_items)} items')

    for idx, item in enumerate(paraguay_tender_items):
        try:
            quantity = json.loads(item)['releases'][0]['contracts'][0]['items'][0]['quantity']
            if quantity is not None: 
                non_none_results.append(item)
        except Exception as e:
            print(f'Error extracting quantity for item {idx}: {e}')

Loaded 87701 items
Error extracting quantity for item 467: list index out of range
Error extracting quantity for item 6342: list index out of range
Error extracting quantity for item 9896: list index out of range
Error extracting quantity for item 11980: list index out of range
Error extracting quantity for item 11981: list index out of range
Error extracting quantity for item 12343: list index out of range
Error extracting quantity for item 12344: list index out of range
Error extracting quantity for item 12345: list index out of range
Error extracting quantity for item 12346: list index out of range
Error extracting quantity for item 12347: list index out of range
Error extracting quantity for item 12348: list index out of range
Error extracting quantity for item 27689: list index out of range
Error extracting quantity for item 27690: list index out of range
Error extracting quantity for item 27691: list index out of range
Error extracting quantity for item 27692: list index out of range
Error extracting quantity for item 27693: list index out of range
Error extracting quantity for item 27694: list index out of range
Error extracting quantity for item 27695: list index out of range
Error extracting quantity for item 27696: list index out of range
Error extracting quantity for item 27697: list index out of range
Error extracting quantity for item 27698: list index out of range
Error extracting quantity for item 27699: list index out of range
Error extracting quantity for item 27700: list index out of range
Error extracting quantity for item 27701: list index out of range
Error extracting quantity for item 27702: list index out of range
Error extracting quantity for item 27703: list index out of range
Error extracting quantity for item 27704: list index out of range
Error extracting quantity for item 27705: list index out of range
Error extracting quantity for item 27706: list index out of range
Error extracting quantity for item 28268: list index out of range
Error extracting quantity for item 28269: list index out of range
Error extracting quantity for item 29510: list index out of range
Error extracting quantity for item 29511: list index out of range
Error extracting quantity for item 29512: list index out of range
Error extracting quantity for item 29513: list index out of range
Error extracting quantity for item 29514: list index out of range
Error extracting quantity for item 29515: list index out of range
Error extracting quantity for item 29516: list index out of range
Error extracting quantity for item 29517: list index out of range
Error extracting quantity for item 29518: list index out of range
Error extracting quantity for item 29519: list index out of range
Error extracting quantity for item 33156: list index out of range
Error extracting quantity for item 33157: list index out of range
Error extracting quantity for item 33158: list index out of range
Error extracting quantity for item 33159: list index out of range
Error extracting quantity for item 35543: list index out of range
Error extracting quantity for item 35544: list index out of range
Error extracting quantity for item 35545: list index out of range
Error extracting quantity for item 35546: list index out of range
Error extracting quantity for item 35547: list index out of range
Error extracting quantity for item 35548: list index out of range
Error extracting quantity for item 35549: list index out of range
Error extracting quantity for item 35740: list index out of range
Error extracting quantity for item 35741: list index out of range
Error extracting quantity for item 35742: list index out of range
Error extracting quantity for item 36691: list index out of range
Error extracting quantity for item 36692: list index out of range
Error extracting quantity for item 55164: list index out of range
Error extracting quantity for item 55165: list index out of range
Error extracting quantity for item 55166: list index out of range
Error extracting quantity for item 55167: list index out of range
Error extracting quantity for item 55168: list index out of range
Error extracting quantity for item 58129: list index out of range
Error extracting quantity for item 58130: list index out of range
Error extracting quantity for item 58131: list index out of range
Error extracting quantity for item 58132: list index out of range
Error extracting quantity for item 58133: list index out of range
Error extracting quantity for item 58451: list index out of range
Error extracting quantity for item 58452: list index out of range
Error extracting quantity for item 58453: list index out of range
Error extracting quantity for item 67790: list index out of range
Error extracting quantity for item 67791: list index out of range
Error extracting quantity for item 67792: list index out of range
Error extracting quantity for item 67793: list index out of range
Error extracting quantity for item 67794: list index out of range
Error extracting quantity for item 67795: list index out of range
Error extracting quantity for item 67796: list index out of range
Error extracting quantity for item 67797: list index out of range
Error extracting quantity for item 67798: list index out of range
Error extracting quantity for item 67799: list index out of range
Error extracting quantity for item 67800: list index out of range
Error extracting quantity for item 67801: list index out of range
Error extracting quantity for item 67802: list index out of range
Error extracting quantity for item 67803: list index out of range
Error extracting quantity for item 67804: list index out of range
Error extracting quantity for item 67805: list index out of range
Error extracting quantity for item 67806: list index out of range
Error extracting quantity for item 67807: list index out of range
Error extracting quantity for item 67808: list index out of range
Error extracting quantity for item 67809: list index out of range
Error extracting quantity for item 67810: list index out of range
Error extracting quantity for item 67811: list index out of range
Error extracting quantity for item 67812: list index out of range
Error extracting quantity for item 67813: list index out of range
Error extracting quantity for item 67814: list index out of range
Error extracting quantity for item 67815: list index out of range
Error extracting quantity for item 67816: list index out of range
Error extracting quantity for item 67817: list index out of range
Error extracting quantity for item 67818: list index out of range
Error extracting quantity for item 67819: list index out of range
Error extracting quantity for item 67820: list index out of range
Error extracting quantity for item 67821: list index out of range
Error extracting quantity for item 67822: list index out of range
Error extracting quantity for item 67823: list index out of range
Error extracting quantity for item 78946: list index out of range
Error extracting quantity for item 82960: list index out of range
Error extracting quantity for item 82961: list index out of range
Error extracting quantity for item 82962: list index out of range

In [ ]:
print(f'Number of non-None results: {len(non_none_results)}')

Number of non-None results: 52332

In [ ]:
with open(os.path.join(generated_data_folder, paraguay_rate_limited_data_file), 'r') as f:
    paraguay_tender_contracts_data = json.load(f)
    print(len(paraguay_tender_contracts_data))

87701

### Searching for Catalog Matches

In [ ]:
# Analyze all contract items for matches
all_matches = []
item_analysis = []

warnings.filterwarnings('ignore')

if 'paraguay_catalog_matches.csv' not in os.listdir(generated_data_folder):
    print('File Not Found')
    print('Generate Catalog Matches')
    for i, contract_data in enumerate(tqdm(non_none_results, desc = 'Matching Tenders with Contract Data', total = len(non_none_results))):
        try:
            contract_json = json.loads(contract_data)
            items = contract_json['releases'][0]['contracts'][0]['items']
            
            for j, item in enumerate(items):
                item_description = item.get('description', '')
                item_id = item.get('classification', {}).get('id', '')
                quantity = item.get('quantity', 0)
                
                # Find matches in catalog
                catalog_matches = find_catalog_matches(item_description, paraguay_public_procurement_catalog)
                translated_matches = find_catalog_matches(item_description, paraguay_public_procurement_items_translated)
                
                # Store analysis
                item_info = {
                    'contract_index': i,
                    'item_index': j,
                    'item_id': item_id,
                    'description': item_description,
                    'quantity': quantity,
                    'catalog_matches': len(catalog_matches),
                    'translated_matches': len(translated_matches),
                    'has_matches': len(catalog_matches) > 0 or len(translated_matches) > 0
                }
                item_analysis.append(item_info)
                
                # Store actual matches
                if len(catalog_matches) > 0:
                    for _, match in catalog_matches.iterrows():
                        all_matches.append({
                            'contract_index': i,
                            'item_description': item_description,
                            'item_id': item_id,
                            'catalog_id': match['id'],
                            'catalog_n4_codigo': match['n4_codigo'],
                            'catalog_n4_nombre': match['n4_nombre'],
                            'catalog_nombre': match['nombre'],
                            'match_type': 'original'
                        })
                
                if len(translated_matches) > 0:
                    for _, match in translated_matches.iterrows():
                        all_matches.append({
                            'contract_index': i,
                            'item_description': item_description,
                            'item_id': item_id,
                            'catalog_id': match.get('id', ''),
                            'catalog_n4_codigo': match['n4_codigo'],
                            'catalog_n4_nombre': match['n4_nombre'],
                            'catalog_nombre': match['nombre'],
                            'match_type': 'translated'
                        })

            item_analysis_df = pd.DataFrame(item_analysis)
            matches_df = pd.DataFrame(all_matches)
            if len(matches_df) > 0:
                matches_df.to_csv(os.path.join(generated_data_folder, paraguay_catalog_matches_file), index=False)
        except Exception as e:
            pass
else:
    print('File Found')
    print('Reading in Matches')

    matches_df = pd.read_csv(os.path.join(generated_data_folder, paraguay_catalog_matches_file))
    

# Look for pharmaceutical-related matches
print("\n=== PHARMACEUTICAL-RELATED MATCHES ===")
pharma_keywords = ['medicamento', 'medicina', 'farmaco', 'droga', 'pastilla', 'tableta', 'capsula', 'jarabe', 'antibiotico', 'analgesico']

pharma_matches = matches_df[
    matches_df['catalog_nombre'].str.contains('|'.join(pharma_keywords), case=False, na=False) |
    matches_df['catalog_n4_nombre'].str.contains('|'.join(pharma_keywords), case=False, na=False) |
    matches_df['item_description'].str.contains('|'.join(pharma_keywords), case=False, na=False)
]

print(f"Found {len(pharma_matches)} pharmaceutical-related matches:")

File Found
Reading in Matches

=== PHARMACEUTICAL-RELATED MATCHES ===
Found 4555 pharmaceutical-related matches:

In [ ]:
matches_df

,contract_index,item_description,item_id,catalog_id,catalog_n4_codigo,catalog_n4_nombre,catalog_nombre,match_type
0,1,Computadoras personales (PC) de escritorio,43211508-001,41103506-9994,41103506,Recintos cerrados de reaccion en cadena de la ...,Cartucho para termociclador generador de gotas,original
1,1,Computadoras personales (PC) de escritorio,43211508-001,41103506-9995,41103506,Recintos cerrados de reaccion en cadena de la ...,Tapa para cartucho para termociclador generado...,original
2,1,Computadoras personales (PC) de escritorio,43211508-001,41103506-9994,41103506,Closed Polymerase chain reaction enclosures (PCR),Dring generator thermocycler cartridge,translated
3,1,Computadoras personales (PC) de escritorio,43211508-001,41103506-9995,41103506,Closed Polymerase chain reaction enclosures (PCR),Cartridge cover for drop -generating thermocycler,translated
4,1,Impresora laser blanco y negro,43212105-001,82121701-9999,82121701,Servicios de copias en blanco y negro o de cotejo,Servicios de copias en blanco y negro,original
...,...,...,...,...,...,...,...,...
773651,1610,Equipo detector de gases,26131701-001,41102704-9999,41102704,Equipo de difraccion de rayos X,Dispositivo de Actualizacion para Equipo de Di...,original
773652,1610,Equipo detector de gases,26131701-001,41104815-9997,41104815,Aparatos para el analisis de nitrogeno Kjeldahl,Equipo Destilador Automatico,original
773653,1610,Equipo detector de gases,26131701-001,42294944-9992,42294944,Equipos o accesorios para endoscopia,VIDEO COLONOSCOPIO,original
773654,1610,Equipo detector de gases,26131701-001,42294944-9993,42294944,Equipos o accesorios para endoscopia,VIDEO GASTROSCOPIO,original
773655,1610,Equipo detector de gases,26131701-001,72101510-9994,72101510,"Instalacion, mantenimiento o reparacion de sis...",Desmontaje de cañerías de sistemas de distribu...,original

### Expanding the Original Dataset to Have One lot_productCode per record

In [ ]:
paraguay_product_codes['lot_productCode'] = paraguay_product_codes['lot_productCode'].str.strip(',')

paraguay_product_codes = paraguay_product_codes.assign(lot_productCode = paraguay_product_codes['lot_productCode'].str.split(','))
paraguay_product_codes = paraguay_product_codes.explode('lot_productCode')
paraguay_product_codes

      lot_productCode  count
0        10101502-006      3
1        10101506-001     10
2        10101506-999      3
3        10101507-001      6
4        10101508-001      6
...               ...    ...
20540    95131603-001      1
20541    95131605-001      1
20542   95131605-9999      1
20543    95131702-001      1
20544    95141801-001      5

[20545 rows x 2 columns]

In [ ]:
paraguay_procurement_data_expanded = expand_procurement_data(paraguay_procurement_data)
paraguay_procurement_data_expanded

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row
0,0000d077-12aa-48e5-8393-1f8684a17820,Adquisición de vehículos y maquinarias para la...,NaN,Licitación Pública Nacional,NaN,3,25101507-002,NaN,1.272480e+09,1.724800e+08,Adquisición de vehículos y maquinarias para la...,NaN,NaN,5e46b4f7-3b99-4e5f-ad7f-3dcc351262c7,Gobierno Departamental de Cordillera,NaN,NaN,NaN,NaN,80048600-5,819bbfb3-bacc-427e-946f-0d9b7ba56f8c,MOTORMARKET S.A.,NaN,FERNANDO DE LA MORA,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2017-10-23,https://www.contrataciones.gov.py:443/datos/ap...,2017,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21088.0,21137.0,21047.0,21066.0,25101507.0,CPV2008,True
1,0000d077-12aa-48e5-8393-1f8684a17820,Adquisición de vehículos y maquinarias para la...,NaN,Licitación Pública Nacional,NaN,3,25181709-004,NaN,1.272480e+09,1.100000e+09,Adquisición de vehículos y maquinarias para la...,NaN,NaN,5e46b4f7-3b99-4e5f-ad7f-3dcc351262c7,Gobierno Departamental de Cordillera,NaN,NaN,NaN,NaN,80002612-8,368896ea-2108-493c-815b-fbefc28b7b4b,RIEDER Y CIA. SACI,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2017-10-23,https://www.contrataciones.gov.py:443/datos/ap...,2017,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21088.0,21137.0,21047.0,21066.0,25181709.0,CPV2008,True
2,0000e371-dca5-4760-8c4e-93fd4f82bcf7,"ALQUILER DE MAQUINARIAS Y EQUIPOS, DE COMPUTAC...",NaN,Contratación Directa,NaN,1,80161504-001,NaN,6.300000e+06,6.300000e+06,"ALQUILER DE MAQUINARIAS Y EQUIPOS, DE COMPUTAC...",NaN,NaN,23b37914-6261-48f1-9e72-409adeff2e59,Facultad de Ciencias Economicas / Universidad ...,NaN,NaN,NaN,NaN,3358978-0,da7fbca3-024f-4b9e-b824-635fac3cae6d,DANIEL ELIAS SERVIN CESPEDES,NaN,PILAR,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-07-12,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18785.0,18820.0,18777.0,18777.0,80161504.0,CPV2008,True
3,0000f14e-0fae-44de-99a8-fe84adbce19c,Seguro para Vehiculos,NaN,Contratación Directa,NaN,1,84131503-001,NaN,6.600000e+06,6.600000e+06,Seguro para Vehiculos,NaN,NaN,3f2429eb-1fe6-46d1-94ca-b34c80e3eae6,Facultad de Ciencias Economicas / Universidad ...,NaN,NaN,NaN,NaN,80031893-5,d690b1f3-8193-41e9-bf59-1bd45fa1b185,ASEGURADORA DEL SUR SA SEGUROS GENERALES (ASUR),NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2018-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2018,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,21264.0,21293.0,21210.0,21257.0,84131503.0,CPV2008,True
4,00020730-a5d5-4427-88d8-df38f3de5299,CONSTRUCCIÓN DE PAVIMENTO TIPO EMPEDRADO,NaN,Concurso de Ofertas,NaN,1,72131701-002,NaN,4.986200e+08,4.986200e+08,CONSTRUCCIÓN DE PAVIMENTO TIPO EMPEDRADO,NaN,NaN,c00fd959-35ac-4d46-bb44-25d6f65e573e,Gobierno Departamental de Canindeyú,NaN,NaN,NaN,NaN,2979720-9,a0603bb1-6c78-4e55-b36e-50389cce3506,GENARO ANDRES FARIÑA,NaN,FCO. CABALLERO ALVAREZ,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-08-14,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19211.0,19219.0,19058.0,19193.0,72131701.0,CPV2008,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857788,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,31201502-003,NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008,True
857789,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,39101601-002,NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008,True
857790,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,39111501-002,NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008,True
857791,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,39111501-003,NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008,True
857792,fffff83a-21e8-4587-888e-467d77d90519,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,Contratación Directa,NaN,4,32141107-002,NaN,2.610720e+07,2.610720e+07,ADQUISICIÓN DE ARTÍCULOS ELÉCTRICOS,NaN,NaN,d59fe70b-f6c0-410f-bc79-8155cee8978a,Comisión Nacional de Telecomunicaciones (CONATEL),NaN,NaN,NaN,NaN,80014304-3,2a96439e-8e29-42d8-8ee8-3ee3084da105,MOLMAN S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-07-28,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19884.0,19932.0,19781.0,19877.0,39101605.0,CPV2008,True

Matching the quantities to the tenders

In [ ]:
contract_quantities = {}
contract_unit_prices = {}

original_urls = paraguay_tender_contracts_list 
json_responses = non_none_results

for i, contract_data in enumerate(tqdm(non_none_results, desc = "Building quantity mapping with original URLs")):
    try:
        contract_json = json.loads(contract_data)
        items = contract_json['releases'][0]['contracts'][0]['items']
        
        json_uri = contract_json.get('uri', '')
        
        if i < len(paraguay_tender_contracts_list):
            original_url = paraguay_tender_contracts_list[i]
        else:
            continue
            
        # Initialize contract in dictionary using ORIGINAL URL
        if original_url not in contract_quantities:
            contract_quantities[original_url] = {}

        if original_url not in contract_unit_prices:
            contract_unit_prices[original_url] = {}
            
        # Store all product quantities for this contract
        for item in items:
            product_id = item.get('classification', {}).get('id', '')
            quantity = item.get('quantity', 0)

            unit_price = None

            try:
                unit_price = item['unit']['value']['amount']
            except Exception as e:
                unit_price = None

            if product_id:
                contract_quantities[original_url][product_id] = quantity
            if unit_price is not None:
                contract_unit_prices[original_url][product_id] = unit_price
                
    except Exception as e:
        continue

print(f"Built mapping for {len(contract_quantities)} contracts using original URLs")
print(f"Built mapping for {len(contract_unit_prices)} contracts using original URLs")

Building quantity mapping with original URLs:   0%|          | 0/52332 [00:00<?, ?it/s]

Built mapping for 32709 contracts using original URLs
Built mapping for 32709 contracts using original URLs

Putting the quantities of the data in, then filtering by those which are non-null

In [ ]:
json.loads(non_none_results[0])['releases'][0]['contracts'][0]['items'][0]['unit']['value']['amount']

3126360.0

In [ ]:
paraguay_procurement_data_expanded = quantity_mapping_fixed(paraguay_procurement_data_expanded, contract_quantities)

Mapping Contract Quantities:   0%|          | 0/106123 [00:00<?, ?it/s]

Results:
- Total contract groups checked: 106123
- Contracts with quantity data: 32703
- Rows updated with quantities: 2029

In [ ]:
def unit_price_mapping(df, contract_unit_prices):
	# Assumes df has columns 'tender_publications_lastcontract' and 'lot_productCode'
	unit_prices = []
	for idx, row in df.iterrows():
		contract_url = row.get('tender_publications_lastcontract', None)
		product_code = row.get('lot_productCode', None)
		price = None
		if contract_url in contract_unit_prices:
			price = contract_unit_prices[contract_url].get(product_code, None)
		unit_prices.append(price)
	df['unit_price'] = unit_prices
	return df

paraguay_procurement_data_expanded = unit_price_mapping(paraguay_procurement_data_expanded, contract_unit_prices)

In [ ]:
paraguay_procurement_data_expanded_non_null = paraguay_procurement_data_expanded[paraguay_procurement_data_expanded['quantity'].notnull()].reset_index(drop = True)
paraguay_procurement_data_expanded_non_null

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price
0,00126f3e-8a26-4afb-bc27-9a793ddc7894,Adquisicion de Caña Blanca - Materia Prima,NaN,Acuerdo Nacional,NaN,13,12352401-9999,NaN,7.590835e+09,469169248.0,Adquisicion de Caña Blanca - Materia Prima,NaN,NaN,f52a5bdc-0ec8-4e3a-9fc8-cfca7ff5ef58,Cañas Paraguayas S.A. (CAPASA),NaN,NaN,NaN,NaN,80080575-5,97bf5319-4f42-49ba-8454-40a476be4018,GRUPO CERRO GUY S.R.L.,NaN,PARAGUARI,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19775.0,19809.0,19761.0,19768.0,12352401.0,CPV2008,True,100000.0,3235.0
1,00126f3e-8a26-4afb-bc27-9a793ddc7894,Adquisicion de Caña Blanca - Materia Prima,NaN,Acuerdo Nacional,NaN,13,12352401-9999,NaN,7.590835e+09,323564992.0,Adquisicion de Caña Blanca - Materia Prima,NaN,NaN,f52a5bdc-0ec8-4e3a-9fc8-cfca7ff5ef58,Cañas Paraguayas S.A. (CAPASA),NaN,NaN,NaN,NaN,1630022-0,d94cad6d-c28e-43ff-ac98-dd5d378e3613,ZENON BAEZ VERA,NaN,YUTY,NaN,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19775.0,19809.0,19761.0,19768.0,12352401.0,CPV2008,True,100000.0,3235.0
2,00126f3e-8a26-4afb-bc27-9a793ddc7894,Adquisicion de Caña Blanca - Materia Prima,NaN,Acuerdo Nacional,NaN,13,12352401-9999,NaN,7.590835e+09,323564992.0,Adquisicion de Caña Blanca - Materia Prima,NaN,NaN,f52a5bdc-0ec8-4e3a-9fc8-cfca7ff5ef58,Cañas Paraguayas S.A. (CAPASA),NaN,NaN,NaN,NaN,678946-3,b11d08a7-4c38-42b3-bb7b-9cbb8407e534,FLORENTINO OSMAR GAYOL LARRAMENDIA,NaN,COSTA LIMA,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19775.0,19809.0,19761.0,19768.0,12352401.0,CPV2008,True,100000.0,3235.0
3,00126f3e-8a26-4afb-bc27-9a793ddc7894,Adquisicion de Caña Blanca - Materia Prima,NaN,Acuerdo Nacional,NaN,14,12352401-9999,NaN,7.590835e+09,647129984.0,Adquisicion de Caña Blanca - Materia Prima,NaN,NaN,f52a5bdc-0ec8-4e3a-9fc8-cfca7ff5ef58,Cañas Paraguayas S.A. (CAPASA),NaN,NaN,NaN,NaN,1985249-5,62a1d001-baca-4022-9107-d491ec119b82,CORNELIO MELGAREJO LOVERA,NaN,QUIINDY.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19775.0,19809.0,19761.0,19768.0,12352401.0,CPV2008,True,100000.0,3235.0
4,00126f3e-8a26-4afb-bc27-9a793ddc7894,Adquisicion de Caña Blanca - Materia Prima,NaN,Acuerdo Nacional,NaN,13,12352401-9999,NaN,7.590835e+09,323564992.0,Adquisicion de Caña Blanca - Materia Prima,NaN,NaN,f52a5bdc-0ec8-4e3a-9fc8-cfca7ff5ef58,Cañas Paraguayas S.A. (CAPASA),NaN,NaN,NaN,NaN,1335349-7,c6696b24-8ab9-4fc8-8df8-86dee721877b,NANCY STELA AREVALOS ORTIGOZA,NaN,BORJA,NaN,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-03-27,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19775.0,19809.0,19761.0,19768.0,12352401.0,CPV2008,True,100000.0,3235.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024,98b95e8c-b308-4454-bcb2-642cd0cb0f13,"Adquisicion de papel, cartón e impresos y util...",NaN,Contratación Directa,NaN,1,14111507-003,NaN,4.446360e+07,8318600.0,"Adquisicion de papel, cartón e impresos y util...",NaN,NaN,18d7e52a-305d-4c84-b065-905a6b3cb9bd,Municipalidad de Hohenau,NaN,NaN,NaN,NaN,1662719-9,819c5871-4fd3-4802-9b8a-9a987302c08d,SYLVANA YANETTE PEREZ FERNANDEZ,NaN,ASUNCION (DISTRITO),NaN,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2010-06-03,https://www.contrataciones.gov.py:443/datos/ap...,2010,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18394.0,18416.0,18374.0,18374.0,14111507.0,CPV2008,True,38.0,209000.0
2025,98e1dad9-1abd-4e51-95c8-543f14609c59,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,Contratación Directa,NaN,5,14111704-002,NaN,7.000000e+07,23096000.0,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,NaN,c71066c2-3279-40d0-ab20-ce940fbf8706,Suoc Cordillera / Corte Suprema de Justicia,NaN,NaN,NaN,NaN,2237441-8,c99f1223-8e59-48ce-a851-334ac7379c4d,JOSE LUIS CARRILLO,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-01,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19920.0,19967.0,19787.0,19899.0,14121810.0,CPV2008,True,80.0,85860.0
2026,98e1dad9-1abd-4e51-95c8-543f14609c59,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,Contratación Directa,NaN,5,14111507-003,NaN,7.000000e+07,43800000.0,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,NaN,c71066c2-3279-40d0-ab20-ce940fbf8706,Suoc Cordillera / Corte Suprema de Justicia,NaN,NaN,NaN,NaN,80027183-1,2935f125-d892-46eb-98b0-fd6cc719807f,COPEL S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-01,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19920.0,19967.0,19787.0,19899.0,14111507.0,CPV2008,True,2400.0,21000.0
2027,98e1dad9-1abd-4e51-95c8-543f14609c59,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,Contratación Directa,NaN,5,14111507-002,NaN,7.000000e+07,43800000.0,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,NaN,c71066c2-3279-40d0-ab20-ce940fbf8706,Suoc Cordillera / Corte Suprema de Justicia,NaN,NaN,NaN,NaN,80027183-1,2935f125-d892-46eb-98b0-fd6cc719807f,COPEL S.A.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-01,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19920.0,19967.0,19787.0,19899.0,14111507.0,CPV2008,True,8.0,215000.0
2028,98e1dad9-1abd-4e51-95c8-543f14609c59,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,Contratación Directa,NaN,6,14111507-001,NaN,7.000000e+07,3104000.0,ADQUISICIÓN DE PRODUCTOS DE PAPEL Y CARTON - 2...,NaN,NaN,c71066c2-3279-40d0-ab20-ce940fbf8706,Suoc Cordillera / Corte Suprema de Justicia,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-01,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19920.0,19967.0,19787.0,19899.0,14111525.0,CPV2008,True,800.0,18000.0

### Creating the Full Pharmaceutical Data Frame
Plus calculating the original unit price and inflation-adjusted price

In [ ]:
pharma_matched_ids = pharma_matches['item_id'].unique().tolist()
full_pharmaceutical_df = paraguay_procurement_data_expanded_non_null[paraguay_procurement_data_expanded_non_null['lot_productCode'].isin(pharma_matched_ids)].reset_index(drop = True)

full_pharmaceutical_df['unit_price'] = (full_pharmaceutical_df['unit_price'] / full_pharmaceutical_df['quantity']).astype(float)
# Made to ensure that all inflation adjusted values are greater than 1 PYG
full_pharmaceutical_df = full_pharmaceutical_df[full_pharmaceutical_df['unit_price'] > 2]
full_pharmaceutical_df['inflation_adj_unit_price'] = full_pharmaceutical_df['unit_price'] * (paraguay_inflation_data['2024'].values[0] / full_pharmaceutical_df['tender_year'])
full_pharmaceutical_df = full_pharmaceutical_df[full_pharmaceutical_df['inflation_adj_unit_price'] > 2]
full_pharmaceutical_df

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,NaN,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172502.0,CPV2008,True,5.0,112700.000000,214.942758
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172503.0,CPV2008,True,5.0,112700.000000,214.942758
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-002,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,60.0,2250.683333,4.290396
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103103-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,50.0,18602.320000,35.460929
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,5.0,41771.600000,79.627688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44122107-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,5000.000000,9.536058
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44121905-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,1500.000000,2.860818
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,8,25172504-002,NaN,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.000000,28.279906
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,9,25172504-002,NaN,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,NaN,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.000000,28.279906
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,NaN,Contratación Directa,NaN,6,47131604-003,NaN,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,NaN,NaN,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,NaN,NaN,NaN,NaN,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,NaN,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,20544.0,20579.0,20503.0,20531.0,47121701.0,CPV2008,True,10.0,2600.000000,4.946452

This is done using the inflation adjusted values

In [ ]:
log_inflation_vals = []
calc_errors = 0
num_values = 0


for value in full_pharmaceutical_df['inflation_adj_unit_price']:
    try:
        log_value = np.log(value)
        log_inflation_vals.append(log_value)
        num_values += 1
    except Exception as e:
        calc_errors += 1
        log_inflation_vals.append(None)
        continue

print('Number of successfully computed log values:', num_values)
print('Number of calculation errors:', calc_errors)

Number of successfully computed log values: 371
Number of calculation errors: 0

Rounding the monetary values to 2 d.p.

In [ ]:
full_pharmaceutical_df['unit_price'] = full_pharmaceutical_df['unit_price'].round(2)
full_pharmaceutical_df['inflation_adj_unit_price'] = full_pharmaceutical_df['inflation_adj_unit_price'].round(2)

full_pharmaceutical_df['log_unit_price'] = log_inflation_vals
full_pharmaceutical_df['log_unit_price'] = full_pharmaceutical_df['log_unit_price'].round(2)
full_pharmaceutical_df.head()

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,63212429.0,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,NaN,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,63212429.0,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-002,NaN,121565800.0,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103103-001,NaN,121565800.0,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-001,NaN,121565800.0,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38

In [ ]:
first_call_tender_missing_data = full_pharmaceutical_df[full_pharmaceutical_df['tender_publications_firstcallfor'].isnull()]
last_call_tender_missing_data = full_pharmaceutical_df[full_pharmaceutical_df['tender_publications_lastcallfort'].isnull()]
print(f"There are {len(first_call_tender_missing_data)} missing first call tender dates and {len(last_call_tender_missing_data)} missing last call tender dates")

There are 12 missing first call tender dates and 12 missing last call tender dates

In [ ]:
first_call_tender_missing_data == last_call_tender_missing_data

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price
70,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
71,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
72,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
73,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
74,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
129,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
130,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
131,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
132,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
242,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
243,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True
457,True,True,False,True,False,True,True,False,True,True,True,False,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,True,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,True,True,True,True,True,True,True

It appears the date columns are in an odd format. Transforming them now<br>
Note that as the above missing data is the same from both variables, plus the fact there is a small amount of data in this section, we will remove these data points from the dataset

In [ ]:
full_pharmaceutical_df = full_pharmaceutical_df[full_pharmaceutical_df['tender_publications_firstcallfor'].notnull()]
full_pharmaceutical_df

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,NaN,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-002,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103103-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44122107-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44121905-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,8,25172504-002,NaN,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,9,25172504-002,NaN,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,NaN,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,NaN,Contratación Directa,NaN,6,47131604-003,NaN,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,NaN,NaN,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,NaN,NaN,NaN,NaN,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,NaN,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,20544.0,20579.0,20503.0,20531.0,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60

In [ ]:
full_pharmaceutical_df[full_pharmaceutical_df['tender_biddeadline'].notnull()]

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,NaN,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18702.0,18736.0,18693.0,18693.0,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-002,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103103-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19094.0,19318.0,19065.0,19079.0,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44122107-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44121905-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,18793.0,18920.0,18764.0,18777.0,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,8,25172504-002,NaN,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,9,25172504-002,NaN,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,NaN,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,19942.0,19982.0,19913.0,19922.0,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,NaN,Contratación Directa,NaN,6,47131604-003,NaN,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,NaN,NaN,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,NaN,NaN,NaN,NaN,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,NaN,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,20544.0,20579.0,20503.0,20531.0,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60

In [ ]:
date_cols = [
    'tender_biddeadline',
    'tender_contractsignaturedate',
    'tender_publications_firstcallfor',
    'tender_publications_lastcallfort'
    ]
for col in date_cols:
    
    full_pharmaceutical_df[col] = pd.to_datetime(full_pharmaceutical_df[col], unit = 'd', errors = 'ignore')

In [ ]:
full_pharmaceutical_df

,tender_id,tender_title,tender_proceduretype,tender_nationalproceduretype,tender_supplytype,tender_recordedbidscount,lot_productCode,tender_awarddecisiondate,tender_finalprice,bid_price,lot_title,lot_bidscount,buyer_id,buyer_masterid,buyer_name,buyer_geocodes,buyer_city,buyer_country,buyer_buyertype,bidder_id,bidder_masterid,bidder_name,bidder_geocodes,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_singl,tender_indicator_integrity_adver,tender_indicator_integrity_decis,tender_indicator_integrity_call_,tender_indicator_integrity_proce,tender_indicator_integrity_tax_h,tender_integrity_winner_ca_share,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,NaN,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,Contratación Directa,NaN,1,25172504-002,NaN,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,NaN,NaN,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,NaN,NaN,NaN,NaN,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-002,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103103-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,NaN,Concurso de Ofertas,NaN,1,44103105-001,NaN,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,NaN,NaN,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,NaN,NaN,NaN,NaN,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44122107-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,NaN,Contratación Directa,NaN,1,44121905-001,NaN,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,NaN,NaN,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,NaN,NaN,NaN,NaN,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,NaN,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,8,25172504-002,NaN,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,NaN,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,NaN,Licitación Pública Nacional,NaN,9,25172504-002,NaN,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,NaN,NaN,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,NaN,NaN,NaN,NaN,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,NaN,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,NaN,Contratación Directa,NaN,6,47131604-003,NaN,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,NaN,NaN,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,NaN,NaN,NaN,NaN,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,NaN,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,NaN,NaN,NaN,100,NaN,NaN,NaN,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60

Removing columns with no data

In [ ]:
full_df_columns = full_pharmaceutical_df.columns.tolist()

for col in full_df_columns:
    if full_pharmaceutical_df[col].value_counts().count() == 0:
        full_pharmaceutical_df = full_pharmaceutical_df.drop(col, axis = 1)

In [ ]:
procedure_types = full_pharmaceutical_df['tender_nationalproceduretype'].unique().tolist()
translated_procedure_types = {}

for procedure in procedure_types:
    translation = translator.translate(procedure)
    translated_procedure_types[procedure] = translation

full_pharmaceutical_df['translated_procedure_types'] = full_pharmaceutical_df['tender_nationalproceduretype'].map(translated_procedure_types)
full_pharmaceutical_df

,tender_id,tender_title,tender_nationalproceduretype,tender_recordedbidscount,lot_productCode,tender_finalprice,bid_price,lot_title,buyer_masterid,buyer_name,bidder_id,bidder_masterid,bidder_name,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_call_,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price,translated_procedure_types
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-002,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46,Offer Contest
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103103-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57,Offer Contest
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38,Offer Contest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44122107-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26,Direct Hiring
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44121905-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05,Direct Hiring
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,8,25172504-002,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,9,25172504-002,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,Contratación Directa,6,47131604-003,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,100,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60,Direct Hiring

Calculating the number of items connected to a tender

In [ ]:
num_tender_items = {}

for item in contract_quantities:
    num_tender_items[item] = len(contract_quantities[item])

num_tender_items

{'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/207946-daniel-elias-servin-cespedes-1': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/340654-aseguradora-sur-sa-seguros-generales-asur-1': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/237811-genaro-andres-farina-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/353146-jet-trade-electrodomesticos-s-a-3': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/347241-sancor-seguros-paraguay-s-a-3': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/242696-jorge-nisvaldo-ovando-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/189477-a-m-asociados-5': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/242821-monica-encina-baez-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/212308-carlos-enrique-montiel-careaga-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/216336-artes-graficas-zamphiropolos-sa-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/273066-san-benito-icsa-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/317167-industrial-grafica-br-s-a-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/268739-zenon-baez-vera-19': 42,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/208328-fusion-2000-s-r-l-6': 13,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/204257-edgar-manuel-jesus-garay-sanchez-1': 7,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/287596-data-lab-sa-7': 32,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/316129-gotze-ingenieria-sa-6': 30,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/318301-eduardo-edmundo-rolon-batista-1': 77,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/198443-fredy-dario-lopez-paez-2': 10,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/234527-barcos-rodados-1': 10,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/283038-carimbos-ind-com-s-r-l-1': 10,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/252642-ramon-fretes-fretes-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/263648-margen-constructora-s-a-1': 9,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/212021-overa-s-a-4': 29,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/266669-infocenter-s-a-1': 23,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/363133-mirian-adelaida-hoppe-mandil-4': 27,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/248923-jorge-ramon-escobar-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/344915-gabriel-tiburcio-sanchez-valdez-2': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/266175-la-ley-paraguaya-s-a-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/217398-cecilio-augusto-bareiro-aquino-7': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/214850-alfredo-enrique-lird-caceres-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/235113-elpidio-valeriano-caceres-coronel-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/232156-andrea-gissel-rodriguez-martinez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/245687-ingemant-sa-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/334216-edgar-daniel-valdez-mereles-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/287062-jose-luis-carrillo-6': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/332042-oscar-penayo-bogado-3': 15,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/331711-automotores-maquinaria-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/306371-rolt-plast-srl-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/155286-nilda-felicia-davalos-barreto-6': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/243964-overa-s-a-2': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/334741-mario-raul-ibarrola-adorno-2': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/190578-molman-s-a-3': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/211905-pascual-manuel-villalba-rojas-8': 10,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/216999-movil-parts-srl-1': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/236111-dental-guarani-srl-1': 18,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/245886-moreno-ruffinelli-asociados-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/320618-prosegur-paraguay-s-a-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/313266-automotor-sa-1': 9,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/210864-kurosu-cia-sa-2': 9,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/205640-el-productor-s-a-seguros-1': 9,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/299053-rosalino-zarate-lopez-1': 9,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/266516-facundo-gimenez-torales-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/340685-nelson-erasmo-silva-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/202882-data-systems-sa-emisora-capital-abierto-3': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/317351-aycom-s-r-l-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/190414-oficina-tecnica-comercial-s-a-6': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/303197-data-systems-sa-emisora-capital-abierto-2': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/233583-maria-ramona-barua-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/292077-elvira-carmen-filartiga-rios-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/339923-carlos-ariel-crosta-fernandez-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/363610-parasoft-s-r-l-3': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/352696-remigio-cristobal-albertini-zarate-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/351990-grupo-empresarial-paraguay-s-a-3': 32,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/239401-neumaticos-asuncion-srl-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/338875-maria-fatima-sartorio-vanni-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/277946-jorge-ocampos-velazquez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/352626-felix-ruben-maidana-gonzalez-2': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/323626-fabian-esteban-lischuk-chichik-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/259384-zoraida-fabiola-aguilar-acuna-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/288267-arnaldo-german-osmik-baez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/233928-reinalda-rivas-flores-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/234965-molman-s-a-3': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/213554-ferreteria-internacional-s-a-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/308270-sampa-s-a-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/220729-obyser-s-r-l-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/277883-barrail-hnos-s-a-construcciones-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/235654-rossana-mabel-ruffinelli-fernandez-8': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/331149-s-a-c-i-h-petersen-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/339730-cie-s-a-2': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/359266-neri-javier-caballero-paez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/338057-rebeka-raquel-caceres-saguier-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/223972-hugo-cesar-romero-fernandez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/364564-lincoln-david-rausky-tabacman-3': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/329755-angelica-noemi-paez-baez-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/317585-lucio-martinez-sotelo-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/336547-mirna-beatriz-lugo-munoz-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/373096-erich-michel-wihr-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/277428-ingemant-sa-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/203821-tecnologia-electronica-e-informatica-sa-t-e-i-s-a-5': 15,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/205288-artaza-hnos-com-e-ind-s-a-3': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/192884-time-s-r-l-3': 7,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/325764-hugo-alfredo-roggio-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/352444-rolando-porfirio-amarilla-servian-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/367029-carlos-maria-gimenez-florentin-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/297475-sampa-s-a-3': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/289560-asuncion-tours-s-r-l-2': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/268223-blanca-cabrera-figueredo-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/364271-edgar-daniel-valdez-mereles-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/202283-wilma-concepcion-ruiz-vda-barua-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/229274-ana-nidia-ortiz-dominguez-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/353585-ferreteria-industrial-srl-4': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/311582-yannina-zumahia-notario-galeano-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/339542-amitour-s-a-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/190680-consist-s-r-l-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/365927-constructora-cerro-cora-srl-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/238951-mather-company-srl-28': 211,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/193184-vita-cora-s-a-4': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/263622-gerhard-wiebe-doerksen-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/351916-distribuidora-policlinica-s-a-1': 78,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/260987-sys-s-a-1': 8,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/209465-norma-elizabeth-lopez-giacomi-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/237508-agencia-benkovics-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/246202-silvana-teresita-fleitas-bogarin-1': 19,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/300801-drogueria-italquimica-sociedad-anonima-1': 19,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/203363-comunicaciones-informatica-telefonia-electricidad-srl-1': 19,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/351799-marciano-ariel-espinola-lopez-3': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/365934-ruth-grisselda-pereira-meza-1': 26,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/237084-neufeld-cia-sa-n-e-c-sa-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/205781-angelica-jimenez-samudio-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/279663-tecnosiplan-s-a-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/327175-ada-nelly-concepcion-ferloni-rios-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/234111-shirosawa-company-saic-4': 25,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/367995-omar-ernesto-perez-gauto-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/306268-em-ingenieria-srl-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/347987-blanca-aurora-bogarin-gomez-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/314029-diego-joaquin-rodriguez-barrios-2': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/346277-alfa-s-a-seguros-reaseguros-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/292320-data-systems-sa-emisora-capital-abierto-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/327413-juan-carlos-zuccolillo-galli-1': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/301204-gloria-lorena-marin-torres-1': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/212063-diana-yolanda-ruiz-diaz-martinez-3': 7,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/192887-panfilo-ugarte-ferreira-3': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/241073-delvalle-carreras-arnulfo-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/271327-antonio-ojeda-burgos-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/281569-maximo-andres-mallada-ferreira-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/244351-seguridad-inteligencia-tecnologia-paraguay-sa-sit-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/353171-oli-service-srl-3': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/197057-forma-industria-comercio-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/333229-apolo-11-s-r-l-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/354970-virginia-defrancesco-acosta-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/191056-antonio-maldonado-chavez-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/202679-p-m-y-a-s-a-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/366851-marina-rosalia-salinas-sanchez-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/222409-parasur-sa-3': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/372931-diego-guillermo-franco-vargas-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/227516-edgar-damian-davalos-ayala-5': 23,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/227799-liliana-graciela-sosa-miranda-1': 22,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/251949-telma-celina-villasboa-3': 22,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/316994-alfredo-julian-gaston-britez-1': 22,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/261100-promotora-e-importadora-azul-s-a-2': 22,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/314016-rieder-cia-saci-1': 22,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/232847-caltec-s-r-l-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/222932-romano-paulo-musskopf-1': 5,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/195577-pluscar-sa-3': 6,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/247691-d-d-distribuidora-sa-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/213091-sergio-kempf-both-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/187246-nimia-mabel-anazco-sandoval-1': 4,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/287533-importadora-neumaticos-rodar-srl-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/282943-oli-service-srl-2': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/336279-carlos-alberto-perales-ortellado-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/306472-isaac-rivaldi-arguello-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/358088-casa-boller-s-a-2': 15,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/273697-alcides-sartorio-vanni-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/222988-valdecir-silva-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/224776-t-shirts-srl-1': 1,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/358877-granos-aceites-sociedad-anonima-comercial-e-ndustrial-agropecuaria-1': 41,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/344668-la-ley-paraguaya-s-a-1': 41,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/273737-industrial-grafica-br-s-a-1': 41,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/283066-rumbos-sa-seguros-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/229760-leongino-mendoza-mino-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/356343-francisca-zarate-melgarejo-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/282290-cantero-s-a-1': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/285442-dalmi-srl-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/213062-metal-mad-s-a-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/186644-time-s-r-l-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/277125-s-a-c-i-h-petersen-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/317458-dimafre-s-a-1': 2,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/367281-lubricantes-cauchos-sa-lubricaucho-sa-2': 35,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/196249-seguridad-inteligencia-tecnologia-paraguay-sa-sit-4': 34,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/275483-telef-celular-paraguay-sa-telecel-sa-2': 3,
 'https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/contract/267642-leonicio-dos-santos-rodriguez-1': 3,

In [ ]:
full_pharmaceutical_df['num_tender_items'] = full_pharmaceutical_df['tender_publications_lastcontract'].map(num_tender_items)
full_pharmaceutical_df

,tender_id,tender_title,tender_nationalproceduretype,tender_recordedbidscount,lot_productCode,tender_finalprice,bid_price,lot_title,buyer_masterid,buyer_name,bidder_id,bidder_masterid,bidder_name,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_call_,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price,translated_procedure_types,num_tender_items
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-002,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46,Offer Contest,4
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103103-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57,Offer Contest,4
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38,Offer Contest,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44122107-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26,Direct Hiring,87
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44121905-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05,Direct Hiring,87
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,8,25172504-002,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,9,25172504-002,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,Contratación Directa,6,47131604-003,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,100,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60,Direct Hiring,34

Need to also create the submission period column

In [ ]:
full_pharmaceutical_df['submission_period_days'] = (full_pharmaceutical_df['tender_biddeadline'] - full_pharmaceutical_df['tender_publications_firstcallfor']).dt.days

Calculating Supplier Market Share by using the bid price connected to the bidder name

In [ ]:
bidder_name_market_share_map = full_pharmaceutical_df.groupby('bidder_name')['bid_price'].sum()
bidder_name_market_share_map = bidder_name_market_share_map.to_dict()
bidder_name_market_share_map

{'ADRIANA PATRICIA VALDEZ MENDOZA': 132439168.0,
 'ALTERNATIVA S.A.': 461446016.0,
 'ALTERNATIVE S.A.': 1930700.0,
 'AMADEO VIDAL VINADER RUOTI': 37669000.0,
 'AMERICA NEUMATICOS SA': 6955200.0,
 'AMERICO DE JESUS GARCIA AYALA': 6210000.0,
 'ANDRES ALDERETE RECALDE': 65661700.0,
 'ANDRESA VEGA': 15458400.0,
 'ANSELMA ARZAMENDIA': 63958568.0,
 'AUTO - REPUESTOS DIOVER SA': 800000000.0,
 'AUTOMOTIVE SA IMPORTADORA Y EXPORTADORA': 503063600.0,
 'BARBARA ROSALINA OCAMPO RUIZ DIAZ': 68748000.0,
 'BLANCA GISSELL FERNANDEZ FRANCO': 550363008.0,
 'CARLOS GABRIEL SANCHEZ SARTORIO': 23996300.0,
 'CASA YASY S.A.': 22920000.0,
 'CECILIO GUSTAVO ORTIZ CACERES': 9720000.0,
 'CENTRO DEL NEUMATICO S.A.': 1657160960.0,
 'COMPAÑIA COMERCIAL DEL PARAGUAY SA': 522257340.0,
 'COMPUGRAF INFORMATICA': 3676323.0,
 'COMVENCE S.A.': 433767360.0,
 'CRISTINA AGUILERA ALVARENGA': 168803632.0,
 'Celso Augusto Ochoa Baez': 7932925.0,
 'Cristina Raquel Silva Cabrera': 12008000.0,
 'DALMI SRL': 38225552.0,
 'DAN Y KAR SA': 647580000.0,
 'DATA LAB SA': 1081300.0,
 'DATA SYSTEMS SA EMISORA DE CAPITAL ABIERTO': 531637374.0,
 'DENESIS DAHIANA SANCHEZ CACERES': 90722848.0,
 'DEZETA S.A': 7355049984.0,
 'DISTRIBUIDORA EL COLEGIO IMPORT - EXPORT S.A': 4275000.0,
 'DOCUNET SA': 101790000.0,
 'DOLLY MARIA DAVALOS GONZALEZ': 11263000.0,
 'DREI ASOCIADOS S.R.L.': 182996000.0,
 'Diana Yolanda Ruiz Diaz Martinez': 73240000.0,
 'ELIEZER MANUEL CABALLERO AMARILLA': 13200000.0,
 'ELISEO HILARIO GOMEZ ROMERO': 54692200.0,
 'ELVIO MANUEL VALIENTE MALUF': 13365825.0,
 'ELVIRA CARMEN FILARTIGA RIOS': 46508460.0,
 'EMPORIO FERRETERIA S.R.L.': 4042530.0,
 'ESTACION BAHIA SRL': 6099370496.0,
 'EVER MARCIAL CHAMORRO PEÑA': 7665000.0,
 'FAVIO ANTONIO CANDIA ESCOBAR': 56167000.0,
 'FELIX EDGARDO CANO GIRALA': 5856885.0,
 'FERRETERIA INTERNACIONAL S.A.': 124364800.0,
 'FIRE MASTER SRL': 2953500.0,
 'FONOLUZ S.A.': 883082490.0,
 'FRANCISCO SABINO ROTELA LOPEZ': 13951600.0,
 'FUSION S.A.': 40357000.0,
 'Fatima Naida Villalba de Sosa': 17003600.0,
 'Fernando Rojas': 367710016.0,
 'G y L S.R.L.': 199368318.0,
 'GOLDEN TRADE S.R.L.': 5214660.0,
 'GUADALUPE MARIA LOPEZ VILLAGRA': 37824240.0,
 'GUIDO ANTERO NUÑEZ FLEITAS': 670740064.0,
 'GUILLERMO ENRIQUE BENITEZ VILLALOBOS': 12516100.0,
 'GUSTAVO ADOLFO LEIVA': 10219900.0,
 'GUSTAVO ADOLFO OVIEDO GIMENEZ': 98556656.0,
 'GUSTAVO DANIEL ROJAS AVALOS': 328850656.0,
 'H.D.G. CHIQUITO COMERCIAL': 260550000.0,
 'HADAMI S.A.': 286465812.0,
 'IMPORTADORA DE NEUMATICOS RODAR SRL': 120026040.0,
 'IN DESING S.R.L.': 2157050.0,
 'INDUSTRIAS BP S.A.': 34911312.0,
 'INTELFLY S.A.': 400105424.0,
 'IRMA ALDERETE DUARTE': 8000000.0,
 'J & S S.R.L.': 110156000.0,
 'JOSE LUIS CARRILLO': 333526344.0,
 'JUAN BRAULIO PEREZ GUTIERREZ': 5752000.0,
 'JUAN EDGAR FLEITAS VALDEZ': 1178591460.0,
 'JULIAN CABRERA SARACHO': 1462800.0,
 'Juan Victor Silva Bogado': 71910000.0,
 'LELIA LUISA FERREIRA MEDINA': 10222210.0,
 'LOURDES CONCEPCION MARTINEZ DUARTE': 39643848.0,
 'LUIS ALBERTO CACACE BERNIE': 5251988.0,
 'LUIS GILBERTO GONZALEZ MIERES': 37290000.0,
 'Lourdes Elizabeth Gimenez Bareiro': 2154145.0,
 'MAES S.R.L.': 0.0,
 'MARIA ANTONIA CUELLAR': 92960000.0,
 'MARIA ESTELA FERNANDEZ GONZALEZ': 36898000.0,
 'MASTER SOFT SRL': 2085577173.0,
 'MECANISMOS Y NEGOCIACIONES VARIAS SRL (MENEVA S.R.L.)': 328787572.0,
 'MIGUEL ANGEL D"ECCLESIIS FERREIRA': 6050000.0,
 'MILCIADES RAMON SOSTOA PENAYO': 162208896.0,
 'MIRNA CELESTE CORONEL AGUAYO': 63071940.0,
 'MOLMAN S.A.': 390608246.0,
 'Maria Cristina Molinas Ortega': 1654968.0,
 'NAZARENO COMERCIAL E INDUSTRIAL SRL': 131062488.0,
 'NEGOCIOS INTERNACIONALES & COMUNICACION SACI Y DE SERVICIOS': 168308000.0,
 'NELSON DANIEL MALDONADO GALEANO': 11161325.0,
 'NELSON ROGELIO PEREIRA FLOR': 59983800.0,
 'NIMIO VILLALBA GAUTO': 196108008.0,
 'NORMA BEATRIZ RAMOS': 67800150.0,
 'OFFICE CLIP S.R.L.': 271585656.0,
 'OFFICE COMPU SA': 935958208.0,
 'OFICINA TÉCNICA COMERCIAL S.A.': 11254571776.0,
 'OSCAR LOPEZ DURE': 44203280.0,
 'OXIPAR S.A': 3948000.0,
 'PAOLA CATEURA RODRIGUEZ': 8264000.0,
 'PAPELERA GUAIRA SRL': 1155103842.0,
 'PARASOFT S.R.L.': 14398318.0,
 'PASCUAL MANUEL VILLALBA ROJAS': 4169400.0,
 'PASTOR AYALA ESCURRA': 79780000.0,
 'PINTUPAR SRL': 100981800.0,
 'PIRO`Y S.A.': 79729462.0,
 'PLUSCAR SA': 382090000.0,
 'PRINTEC SA': 799610000.0,
 'PROTECCION INDUSTRIAL PARAGUAYA': 20327400.0,
 'PS LINE SA': 244043504.0,
 'RAMON ISMAEL GAMARRA ESPINOLA': 50982000.0,
 'RBA DISTRIBUIDORA IMPORT. EXPORT. S.A.': 55500000.0,
 'RODOLFO BENJAMIN ORTIGOZA MORALES': 20880000.0,
 'RODRIGO JOEL ZACARIAS VAZQUEZ': 11499304.0,
 'SAS PARAGUAY S.A.': 25451800.0,
 'SDA PARAGUAY SA': 243327000.0,
 'SERVIPRO S.R.L.': 89214000.0,
 'SHIROSAWA COMPANY SAIC': 416303904.0,
 'SILVANA TERESITA FLEITAS BOGARIN': 47819800.0,
 'SOLUTIONS CENTER S.A.': 91931400.0,
 'SYSTEMS @ND NETWORKS SRL': 24060000.0,
 'TECHNO AMERICAN SRL': 6580000.0,
 'TECNOLOGIA PLANIFICADA (TECNOPLAN) SA': 100913048.0,
 'TELEXPAR S.R.L.': 5974100.0,
 'ULISES GUSTAVO LEVRAND PAIRA': 59219200.0,
 'VICENTE SCAVONE & CIA.COMERCIAL E INDUSTRIAL SA': 387192032.0,
 'VICTOR MANUEL CACERES VIDAL': 805908680.0,
 'WON KI CHUNG': 39333656.0,
 'YUTY SOCIEDAD ANONIMA': 218070000.0,
 'ZUNILDA ELISA COUCHONAL DOS SANTOS': 232762524.0}

In [ ]:
full_pharmaceutical_df['supplier_market_share'] = full_pharmaceutical_df['bidder_name'].map(bidder_name_market_share_map)
full_pharmaceutical_df

,tender_id,tender_title,tender_nationalproceduretype,tender_recordedbidscount,lot_productCode,tender_finalprice,bid_price,lot_title,buyer_masterid,buyer_name,bidder_id,bidder_masterid,bidder_name,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_call_,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price,translated_procedure_types,num_tender_items,submission_period_days,supplier_market_share
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,5.752000e+06
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,4.420328e+07
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-002,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46,Offer Contest,4,29.0,1.155104e+09
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103103-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57,Offer Contest,4,29.0,1.155104e+09
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38,Offer Contest,4,29.0,1.155104e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44122107-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26,Direct Hiring,87,29.0,5.974100e+06
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44121905-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05,Direct Hiring,87,29.0,5.974100e+06
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,8,25172504-002,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,6.475800e+08
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,9,25172504-002,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,8.000000e+08
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,Contratación Directa,6,47131604-003,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,100,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60,Direct Hiring,34,41.0,1.700360e+07

Retrieving the Months of the Tenders

In [ ]:
full_pharmaceutical_df['tender_month'] = full_pharmaceutical_df['tender_publications_firstcallfor'].dt.month

Calculating the Share of Contract Value by Supplier per year

In [ ]:
buyer_supplier_annual_analysis = full_pharmaceutical_df.groupby(['buyer_name', 'bidder_name', 'tender_year']).agg({
    'bid_price': 'sum',
    'tender_id': 'count'
}).reset_index()

buyer_supplier_annual_analysis.columns = [
    'buyer_name', 'bidder_name', 'tender_year', 
    'total_contract_value', 'contract_count'
]

# Calculate total spending by each buyer per year
buyer_annual_totals = full_pharmaceutical_df.groupby([
    'buyer_name', 'tender_year'
])['bid_price'].sum().reset_index()
buyer_annual_totals.columns = ['buyer_name', 'tender_year', 'buyer_annual_total']


buyer_supplier_shares = buyer_supplier_annual_analysis.merge(
    buyer_annual_totals, 
    on = ['buyer_name', 'tender_year']
)

buyer_supplier_shares['contract_value_share (%)'] = (
    buyer_supplier_shares['total_contract_value'] / 
    buyer_supplier_shares['buyer_annual_total'] * 100
).round(2)

# Then mapping the market share of the buyer back to the full_pharmaceutical_df
buyer_market_share_map = buyer_annual_totals.set_index(['buyer_name', 'tender_year'])['buyer_annual_total'].to_dict()
full_pharmaceutical_df['buyer_annual_total'] = full_pharmaceutical_df.set_index(['buyer_name', 'tender_year']).index.map(buyer_market_share_map)
buyer_supplier_shares

,buyer_name,bidder_name,tender_year,total_contract_value,contract_count,buyer_annual_total,contract_value_share (%)
0,Administración Nacional de Electricidad (ANDE),CENTRO DEL NEUMATICO S.A.,2014,1.657161e+09,1,2.005731e+09,82.62
1,Administración Nacional de Electricidad (ANDE),IMPORTADORA DE NEUMATICOS RODAR SRL,2014,4.527804e+07,1,2.005731e+09,2.26
2,Administración Nacional de Electricidad (ANDE),PLUSCAR SA,2014,2.778400e+08,1,2.005731e+09,13.85
3,Administración Nacional de Electricidad (ANDE),SAS PARAGUAY S.A.,2014,2.545180e+07,1,2.005731e+09,1.27
4,Administración Nacional de Navegación y Puerto...,DATA SYSTEMS SA EMISORA DE CAPITAL ABIERTO,2015,2.200000e+07,1,3.346875e+08,6.57
...,...,...,...,...,...,...,...
220,Tribunal Superior de Justicia Electoral (TSJE),OFICINA TÉCNICA COMERCIAL S.A.,2010,1.930888e+09,1,2.191438e+09,88.11
221,Tribunal Superior de Justicia Electoral (TSJE),OFICINA TÉCNICA COMERCIAL S.A.,2019,9.323684e+09,2,1.048942e+10,88.89
222,Tribunal Superior de Justicia Electoral (TSJE),ZUNILDA ELISA COUCHONAL DOS SANTOS,2019,7.932270e+07,1,1.048942e+10,0.76
223,Universidad Nacional de Concepción (UNC),AMERICO DE JESUS GARCIA AYALA,2019,6.210000e+06,1,7.228000e+06,85.92
224,Universidad Nacional de Concepción (UNC),NAZARENO COMERCIAL E INDUSTRIAL SRL,2019,1.018000e+06,1,7.228000e+06,14.08

In [ ]:
total_market_value = full_pharmaceutical_df['bid_price'].sum()
supplier_total_values = full_pharmaceutical_df.groupby('bidder_name')['bid_price'].sum()
supplier_market_share_percent = (supplier_total_values / total_market_value * 100).round(2)

full_pharmaceutical_df['supplier_market_share_percent'] = full_pharmaceutical_df['bidder_name'].map(supplier_market_share_percent)
full_pharmaceutical_df['supplier_market_share'] = full_pharmaceutical_df['bidder_name'].map(supplier_total_values)

In [ ]:
full_pharmaceutical_df

,tender_id,tender_title,tender_nationalproceduretype,tender_recordedbidscount,lot_productCode,tender_finalprice,bid_price,lot_title,buyer_masterid,buyer_name,bidder_id,bidder_masterid,bidder_name,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_call_,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price,translated_procedure_types,num_tender_items,submission_period_days,supplier_market_share,tender_month,buyer_annual_total,supplier_market_share_percent
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,5.752000e+06,3,4.995528e+07,0.01
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,4.420328e+07,3,4.995528e+07,0.09
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-002,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103103-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44122107-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26,Direct Hiring,87,29.0,5.974100e+06,5,8.633980e+06,0.01
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44121905-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05,Direct Hiring,87,29.0,5.974100e+06,5,8.633980e+06,0.01
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,8,25172504-002,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,6.475800e+08,7,1.437000e+09,1.33
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,9,25172504-002,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,8.000000e+08,7,1.437000e+09,1.64
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,Contratación Directa,6,47131604-003,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,100,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60,Direct Hiring,34,41.0,1.700360e+07,2,1.700360e+07,0.03

It appears that some cities appear more than once in different forms. Going to replace the duplicates using a list of unique cities to simplify so the model doesn't have problems

In [ ]:
import difflib

unique_cities = [
    'Asunción',
    'Ciudad del Este',
    'Concepción',
    'Coronel Oviedo',
    'Encarnación',
    'Fernando de la Mora',
    'Katueté',
    'Lambaré',
    'Limpio',
    'Luque',
    'Pedro Juan Caballero',
    'Salto del Guairá',
    'San Lorenzo',
    'Santa Cecilia',
    'Villa Elisa',
    'Villarrica',
]

bidder_cities = sorted(full_pharmaceutical_df['bidder_city'].unique().tolist())
print(f"There are {len(bidder_cities)} unique bidder cities")
for city in bidder_cities:
    difflib.get_close_matches(city, unique_cities, )

    print(city)
    if city in unique_cities:
        print(city)
        print(f'{city} found in unique list as {unique_cities[unique_cities.index(city)]}\n')

There are 42 unique bidder cities
ASUNCION
ASUNCION (DISTRITO)
ASUNCIÓN
ASUNCIÓN.
AYOLAS
Asuncion
Asunción
Asunción
Asunción found in unique list as Asunción

Asunción.
CDE
CIUDAD DEL ESTE
CONCEPCION
CONCEPCION (MUNICIPIO)
CORONEL OVIEDO
Ciudad del ESte.
Ciudad el Este
Coronel Oviedo
Coronel Oviedo
Coronel Oviedo found in unique list as Coronel Oviedo

DEL ESTE
ENCARNACION
ENCARNACION (MUNICIPIO)
FERNANDO DE LA MORA
Fernando de la Mora
Fernando de la Mora
Fernando de la Mora found in unique list as Fernando de la Mora

KATUETE
LAMBARE
LAMBARÉ.
LIMPIO.
LUQUE
Lambare
Limpio - Asuncion
Luque
Luque
Luque found in unique list as Luque

PEDRO JUAN CABALLERO (MUNIC.)
SALTO DEL GUAIRÁ.
SAN LORENZO
SAN LORENZO.
SANTA CECILIA
San Lorenzo
San Lorenzo
San Lorenzo found in unique list as San Lorenzo

VILLA ELISA
VILLARRICA
Villa Elisa.
asuncion
ciudad del este
luque
villarrica

In [ ]:
sorted(full_pharmaceutical_df['bidder_city'].tolist())

['ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCION (DISTRITO)',
 'ASUNCIÓN',
 'ASUNCIÓN',
 'ASUNCIÓN.',
 'ASUNCIÓN.',
 'ASUNCIÓN.',
 'AYOLAS',
 'Asuncion',
 'Asuncion',
 'Asuncion',
 'Asuncion',
 'Asuncion',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción',
 'Asunción.',
 'Asunción.',
 'Asunción.',
 'Asunción.',
 'CDE',
 'CDE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CIUDAD DEL ESTE',
 'CONCEPCION',
 'CONCEPCION',
 'CONCEPCION (MUNICIPIO)',
 'CONCEPCION (MUNICIPIO)',
 'CONCEPCION (MUNICIPIO)',
 'CORONEL OVIEDO',
 'CORONEL OVIEDO',
 'CORONEL OVIEDO',
 'Ciudad del ESte.',
 'Ciudad el Este',
 'Coronel Oviedo',
 'Coronel Oviedo',
 'DEL ESTE',
 'ENCARNACION',
 'ENCARNACION',
 'ENCARNACION (MUNICIPIO)',
 'FERNANDO DE LA MORA',
 'FERNANDO DE LA MORA',
 'FERNANDO DE LA MORA',
 'FERNANDO DE LA MORA',
 'FERNANDO DE LA MORA',
 'FERNANDO DE LA MORA',
 'Fernando de la Mora',
 'KATUETE',
 'KATUETE',
 'KATUETE',
 'KATUETE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARE',
 'LAMBARÉ.',
 'LAMBARÉ.',
 'LAMBARÉ.',
 'LIMPIO.',
 'LIMPIO.',
 'LUQUE',
 'LUQUE',
 'LUQUE',
 'LUQUE',
 'Lambare',
 'Lambare',
 'Lambare',
 'Limpio - Asuncion',
 'Luque',
 'Luque',
 'PEDRO JUAN CABALLERO (MUNIC.)',
 'SALTO DEL GUAIRÁ.',
 'SAN LORENZO',
 'SAN LORENZO.',
 'SANTA CECILIA',
 'San Lorenzo',
 'San Lorenzo',
 'San Lorenzo',
 'VILLA ELISA',
 'VILLA ELISA',
 'VILLA ELISA',
 'VILLA ELISA',
 'VILLA ELISA',
 'VILLARRICA',
 'VILLARRICA',
 'VILLARRICA',
 'VILLARRICA',
 'Villa Elisa.',
 'Villa Elisa.',
 'Villa Elisa.',
 'Villa Elisa.',
 'Villa Elisa.',
 'asuncion',
 'asuncion',
 'ciudad del este',
 'luque',
 'villarrica']

Getting the supplier size

In [ ]:
bidder_price = full_pharmaceutical_df.groupby(['bidder_name'])['tender_finalprice'].sum().reset_index()
bidder_price_map = bidder_price.set_index('bidder_name')['tender_finalprice'].to_dict()
full_pharmaceutical_df['supplier_size'] = full_pharmaceutical_df['bidder_name'].map(bidder_price_map)
full_pharmaceutical_df

,tender_id,tender_title,tender_nationalproceduretype,tender_recordedbidscount,lot_productCode,tender_finalprice,bid_price,lot_title,buyer_masterid,buyer_name,bidder_id,bidder_masterid,bidder_name,bidder_city,bidder_country,bid_iswinning,source,tender_publications_lastcontract,tender_publications_firstdcontra,notice_url,tender_year,tender_indicator_integrity_call_,currency,tender_biddeadline,tender_contractsignaturedate,tender_publications_firstcallfor,tender_publications_lastcallfort,lot_localProductCode,lot_localProductCode_type,is_exploded_row,quantity,unit_price,inflation_adj_unit_price,log_unit_price,translated_procedure_types,num_tender_items,submission_period_days,supplier_market_share,tender_month,buyer_annual_total,supplier_market_share_percent,supplier_size
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,5752000.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,1296453-0,f5a77e0b-fc48-4982-a017-953b44fd7297,JUAN BRAULIO PEREZ GUTIERREZ,San Lorenzo,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172502.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,5.752000e+06,3,4.995528e+07,0.01,6.321243e+07
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,Contratación Directa,1,25172504-002,6.321243e+07,44203280.0,ADQUISICIÓN DE CUBIERTAS Y CAMARAS DE AIRE,874f7ecd-16b4-481c-bb3f-aa8e0ca7a255,Municipalidad de Capiatá,2510054-8,f23f9034-3771-45e2-b726-e37268216aa8,OSCAR LOPEZ DURE,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-04-19,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-03-16,2021-04-19,2021-03-07,2021-03-07,25172503.0,CPV2008,True,5.0,112700.00,214.94,5.37,Direct Hiring,10,9.0,4.420328e+07,3,4.995528e+07,0.09,6.321243e+07
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-002,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,60.0,2250.68,4.29,1.46,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37,2.847075e+09
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103103-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,50.0,18602.32,35.46,3.57,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37,2.847075e+09
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,ADQ. DE UTILES DE OFICINA,Concurso de Ofertas,1,44103105-001,1.215658e+08,121565800.0,Contract Amendment: ADQ. DE UTILES DE OFICINA,08fb171c-dadd-4ef1-b70d-a52534f8486c,Comando de la Fuerza Aerea Uoc 4 / Ministerio ...,80022417-5,10da32e8-6bf9-459f-9512-2527a2f013e7,PAPELERA GUAIRA SRL,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2012-05-25,https://www.contrataciones.gov.py:443/datos/ap...,2012,100,PYG,2022-04-12,2022-11-22,2022-03-14,2022-03-28,44121802.0,CPV2008,True,5.0,41771.60,79.63,4.38,Offer Contest,4,29.0,1.155104e+09,3,3.646974e+08,2.37,2.847075e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44122107-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,5000.00,9.54,2.26,Direct Hiring,87,29.0,5.974100e+06,5,8.633980e+06,0.01,1.132531e+07
585,954e5180-2081-48d8-8215-29f86c5b9370,PROVISIÓN DE ÚTILES DE OFICINA,Contratación Directa,1,44121905-001,5.662655e+06,2987050.0,PROVISIÓN DE ÚTILES DE OFICINA,8554d912-22b8-460b-9e74-bb94684e14b3,Caja de Jubilaciones y Pensiones del Personal ...,80025739-1,1ceb5302-ba00-49ea-9a49-d40428c7e433,TELEXPAR S.R.L.,ASUNCION,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2011-10-20,https://www.contrataciones.gov.py:443/datos/ap...,2011,100,PYG,2021-06-15,2021-10-20,2021-05-17,2021-05-30,44121704.0,CPV2008,True,1.0,1500.00,2.86,1.05,Direct Hiring,87,29.0,5.974100e+06,5,8.633980e+06,0.01,1.132531e+07
586,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,8,25172504-002,1.437000e+09,637000000.0,Adquisición de Cubiertas y Cámaras,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80020482-4,ce3f7204-e137-4ad3-beae-be1ab37c9aa2,DAN Y KAR SA,ASUNCION (DISTRITO),PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,6.475800e+08,7,1.437000e+09,1.33,1.901879e+09
587,95f240d9-6041-4914-952e-4c81fbd58c75,Adquisición de Cubiertas y Cámaras,Licitación Pública Nacional,9,25172504-002,1.437000e+09,800000000.0,Contract Amendment: Adquisición de Cubiertas y...,f281a13b-f15b-405c-abe0-d8944d599a04,Policia Nacional / Ministerio del Interior,80028285-0,7d711a2b-fe10-494f-912d-af6dcf467ee6,AUTO - REPUESTOS DIOVER SA,ASUNCIÓN.,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2014-09-16,https://www.contrataciones.gov.py:443/datos/ap...,2014,100,PYG,2024-08-07,2024-09-16,2024-07-09,2024-07-18,25172504.0,CPV2008,True,40.0,14850.00,28.28,3.34,National Public Tender,34,29.0,8.000000e+08,7,1.437000e+09,1.64,1.437000e+09
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Adquisición de artículos y productos de limpieza,Contratación Directa,6,47131604-003,3.151756e+07,17003600.0,Adquisición de artículos y productos de limpieza,7cb27da9-adbc-43d0-8434-ac0b3f7d8b51,Rectorado / Universidad Nacional del Este,2271504-5,cffd22ad-3d53-4192-8588-a9203db914bd,Fatima Naida Villalba de Sosa,ciudad del este,PY,t,https://www.contrataciones.gov.py,https://www.contrataciones.gov.py:443/datos/ap...,2016-05-05,https://www.contrataciones.gov.py:443/datos/ap...,2016,100,PYG,2026-04-01,2026-05-06,2026-02-19,2026-03-19,47121701.0,CPV2008,True,10.0,2600.00,4.95,1.60,Direct Hiring,34,41.0,1.700360e+07,2,1.700360e+07,0.03,3.151756e+07

### Understanding which variables were used in the article

- Dependent Variable - `log_unit_price`
Market Conditions:
- UNSPSC - In the paper, because they are trying to standardise procurement codes, this is used. In our research, we are only using one country, therefore we only use `lot_productCode`
- Country/Territory - because it is only one country now, we are using the `bidder_city` variable
- Year - `tender_year`

Predictors: Directly Influenceable
- Quantity of Goods - `quantity`
- Product Bundling - `num_tender_items`
- Procedure Type - `translated_procedure_types`
- Submission Period - `submission_period_days`
- Decision period per bids number - cannot find this information as the column important to this has no values
- Month - `tender_month`
- Success Rate
- Number of bidders - `tender_recordedbidscount`
- Supplier Market Share - `supplier_market_share`
- Buyer Spending Concentration - `buyer_annual_total`
- Supplier Size - `supplier_size`

Reordering the columns for better readability with respect to the variables we are using

In [ ]:
new_column_order = ['tender_id', 
                    'translated_procedure_types', 
                    'lot_productCode', 
                    'tender_finalprice',
                    'tender_biddeadline',
                    'tender_contractsignaturedate', 
                    'bidder_city',
                    'tender_year',
                    'quantity', 
                    'unit_price', 
                    'inflation_adj_unit_price', 
                    'log_unit_price', 
                    'num_tender_items', 
                    'submission_period_days', 
                    'tender_month',
                    'buyer_annual_total',
                    'tender_recordedbidscount',
                    'supplier_market_share'
                ]

In [ ]:
full_pharmaceutical_df = full_pharmaceutical_df[new_column_order]
full_pharmaceutical_df

,tender_id,translated_procedure_types,lot_productCode,tender_finalprice,tender_biddeadline,tender_contractsignaturedate,bidder_city,tender_year,quantity,unit_price,inflation_adj_unit_price,log_unit_price,num_tender_items,submission_period_days,tender_month,buyer_annual_total,tender_recordedbidscount,supplier_market_share
0,002e70ec-1a15-447b-8d17-c6ccb484b10f,Direct Hiring,25172504-002,6.321243e+07,2021-03-16,2021-04-19,San Lorenzo,2011,5.0,112700.00,214.94,5.37,10,9.0,3,4.995528e+07,1,5.752000e+06
1,002e70ec-1a15-447b-8d17-c6ccb484b10f,Direct Hiring,25172504-002,6.321243e+07,2021-03-16,2021-04-19,ASUNCION,2011,5.0,112700.00,214.94,5.37,10,9.0,3,4.995528e+07,1,4.420328e+07
2,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,Offer Contest,44103105-002,1.215658e+08,2022-04-12,2022-11-22,ASUNCION (DISTRITO),2012,60.0,2250.68,4.29,1.46,4,29.0,3,3.646974e+08,1,1.155104e+09
3,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,Offer Contest,44103103-001,1.215658e+08,2022-04-12,2022-11-22,ASUNCION (DISTRITO),2012,50.0,18602.32,35.46,3.57,4,29.0,3,3.646974e+08,1,1.155104e+09
4,00d5c9db-ca9e-4d2d-897c-4aead4521e4e,Offer Contest,44103105-001,1.215658e+08,2022-04-12,2022-11-22,ASUNCION (DISTRITO),2012,5.0,41771.60,79.63,4.38,4,29.0,3,3.646974e+08,1,1.155104e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,954e5180-2081-48d8-8215-29f86c5b9370,Direct Hiring,44122107-001,5.662655e+06,2021-06-15,2021-10-20,ASUNCION,2011,1.0,5000.00,9.54,2.26,87,29.0,5,8.633980e+06,1,5.974100e+06
585,954e5180-2081-48d8-8215-29f86c5b9370,Direct Hiring,44121905-001,5.662655e+06,2021-06-15,2021-10-20,ASUNCION,2011,1.0,1500.00,2.86,1.05,87,29.0,5,8.633980e+06,1,5.974100e+06
586,95f240d9-6041-4914-952e-4c81fbd58c75,National Public Tender,25172504-002,1.437000e+09,2024-08-07,2024-09-16,ASUNCION (DISTRITO),2014,40.0,14850.00,28.28,3.34,34,29.0,7,1.437000e+09,8,6.475800e+08
587,95f240d9-6041-4914-952e-4c81fbd58c75,National Public Tender,25172504-002,1.437000e+09,2024-08-07,2024-09-16,ASUNCIÓN.,2014,40.0,14850.00,28.28,3.34,34,29.0,7,1.437000e+09,9,8.000000e+08
591,9839e78c-cec2-410b-8e69-edfdbb82c3d1,Direct Hiring,47131604-003,3.151756e+07,2026-04-01,2026-05-06,ciudad del este,2016,10.0,2600.00,4.95,1.60,34,41.0,2,1.700360e+07,6,1.700360e+07

In [ ]:
full_pharmaceutical_df.to_csv(os.path.join(generated_data_folder, 'full_pharmaceutical_data.csv'), index = False)